### ISSUE TITLE
Using `CurlAsyncHTTPClient` for proxy support

### ISSUE THREAD

**Issue by gforsyth** [dask/dask-gateway#103]
At large enterprises / institutions it's often common to have proxy stuff configured via environment variables -- out of the box this causes trouble with the gateway client as it doesn't pay attention to those.

However, telling it to use `CurlAsyncHTTPClient` seems to fix the issue, by adding 

```python
AsyncHTTPClient.configure("tornado.curl_httpclient.CurlAsyncHTTPClient")
``` 

after the initial import in https://github.com/jcrist/dask-gateway/blob/master/dask-gateway/dask_gateway/client.py

Any concerns with making this the default?  According to https://www.tornadoweb.org/en/stable/httpclient.html#module-tornado.httpclient it will require newish version of `libcurl` and `pycurl`

"Currently the minimum supported version of libcurl is 7.22.0, and the minimum version of pycurl is 7.18.2."

**Comment by jcrist** [comment]
JupyterHub does this by default, falling back to the builtin version, I'd be happy to do this as well. At one point the curl client worked fine - I *think* it still does, but there may be a few small fixes needed (the two clients aren't 100% compatible in behavior).

Are you interested in making a PR?

**Comment by gforsyth** [comment]
Happy to -- might take a few days but if you don't mind the delay I can put it together.

**Comment by jcrist** [comment]
Fine by me. Thanks for the interest.
