### ISSUE TITLE
Where to store docker images

### ISSUE THREAD

**Issue by jcrist** [dask/dask-gateway#104]
Currently all docker images for dask-gateway are stored in my docker hub account (https://hub.docker.com/u/jcrist). After moving to the dask org, we probably want to move these somewhere else. Two options:

- Put them in `daskdev`
- Create a new `dask-gateway` org

The first is nice, since all dask things are together. Downside is there's a lot of dask-gateway images, and it might be nice to keep them all organized together.

Right now I'm leaning slightly towards a new org for dask-gateway specific things.

**Comment by jcrist** [comment]
As a data point, JupyterHub has a separate docker org for their images:

- https://hub.docker.com/u/jupyterhub (jupyterhub only)
- https://hub.docker.com/u/jupyter (main jupyter org)

**Comment by TomAugspurger** [comment]
Either works for me.

**Comment by jcrist** [comment]
I'm in the process of moving things to the `daskgateway` org.
