### ISSUE TITLE
Point `gateway.dask.org` to our docs

### ISSUE THREAD

**Issue by jcrist** [dask/dask-gateway#106]
We should add `gateway.dask.org` on cloudflare to point to our docs. @quasiben I believe you have the rights for this? The docs are hosted at https://dask.github.io/dask-gateway/.

**Comment by TomAugspurger** [comment]
dask-ml does something similar. We needed

1. To set `ml.dask.org` in the "Custom domain" field in the GitHub settings for the repository
2. Add a custom CNAME file to the gh-pages branch: https://github.com/dask/dask-ml/blob/gh-pages/CNAME
3. Something on the cloudflare side (I don't recall the details here. Hopefully you have access to see how it's configured).

**Comment by quasiben** [comment]
Yes, add a PR now

**Comment by quasiben** [comment]
cloudflare is all setup -- when #108 is merged I believe things should be functional

**Comment by quasiben** [comment]
confirmed https://gateway.dask.org is up and running -- i think only @jcrist can close

**Comment by jcrist** [comment]
Hmmm, I'm seeing the old docs there, not master.

- https://dask.org/dask-gateway/
- https://gateway.dask.org/

**Comment by jcrist** [comment]
Got this report from github:

 The CNAME `gateway.dask.org` is already taken. Check out https://help.github.com/articles/troubleshooting-custom-domains/#cname-already-taken for more information.

**Comment by jcrist** [comment]
I think this is because @quasiben pushed the cname to his own gh-pages branch in #108, which was outdated, and that's why it's serving there?

**Comment by quasiben** [comment]
that's annoying -- sorry, delete the branch now

**Comment by jcrist** [comment]
Hmmm, still no good. Do you have the right link on cloudflare? Getting a 404 from github now for https://gateway.dask.org/

**Comment by quasiben** [comment]
I've deleted the branch and https://gateway.dask.org is getting a 404 for me.  I suspect this is a DNS caching issue now, maybe waiting a bit should resolve things

**Comment by quasiben** [comment]
I checked just now and everything looks correct as best as I can tell

**Comment by jcrist** [comment]
I had to force the docs to rebuild and that fixed things. Thanks @quasiben! Closing.
