### ISSUE TITLE
Mutualize CI set-up with dask-jobqueue?

### ISSUE THREAD

**Issue by lesteve** [dask/dask-gateway#111]
We have some CI set-up in dask-jobqueue for different job schedulers (SGE, SLURM, PBS, with some more on the way hopefully, e.g. HTCondor and LSF). It feels like we could mutualize part of the CI set-up with `dask-gateway` to ease maintenance. Any opinion on this?

Some differences I noticed (there are likely more):
* `dask-jobqueue` is using `docker-compose` and `dask-gateway` is using single `Dockerfile` images. For `dask-jobqueue`, part of it is historic that was how it was done in `dask-drmaa` originally. Also with `docker-compose`, it feels more like a "real" cluster setup, with a master node and compute nodes, rather than a toy single node setup.
* `dask-jobqueue` is rebuilding the docker image on each CI build whereas `dask-gateway` uses images from dockerhub. I am guessing images are built and pushed automatically but I haven't figured out where it happens

**Comment by jcrist** [comment]
We could do this, but I don't see this duplication as a problem. It's easy to copy around Dockerfiles, and both projects likely have divergent testing requirements. For example, `dask-gateway` is meant to be run as a privileged user, whereas when testing `dask-jobqueue` you probably want to make sure it works fine with user-level permissions. I've also run into issues in the past where a test image was shared between a few projects - adding a new dependency to help test a feature for project 1 led to failures in project 2. It became easier to maintain the testing infrastructure separately for each project. I'm not 100% against sharing CI infrastructure, but having them separate is currently not causing problems and makes it easier to change things in the future.

Answering your questions from above:

We use a single node setup for ease of testing (shared filesystem). In practice this hits all of the things we care to test against without being complicated to manage. The images are built beforehand (manually), and include everything but dask-gateway and its dependencies. This cuts down on CI time, which is nice.

**Comment by lesteve** [comment]
Makes sense, thanks a lot for your input! I'll try to see whether `dask-jobqueue` can reuse some things from `dask-gateway` and feel free to steal from `dask-jobqueue` as well obviously.
