### ISSUE TITLE
Automate chart building with chartpress

### ISSUE THREAD

**Issue by jcrist** [dask/dask-gateway#117]
In #116 we added a setup using chartpress for publishing helm charts to https://dask.org/dask-gateway-helm-repo/. It would be nice to automate this using CI.

The chart naming scheme is:

`dask-gateway-{dask_gateway_server.__version__}-{git tag}`

with the tag removed for releases (using the `--reset` flag).

**Comment by tom-butler** [comment]
Automating chart release would be great.

I just got caught by a typo in the chart which was fixed here: https://github.com/dask/dask-gateway/commit/05d2da2f252434408e61c0566673ae8109a2e124 but there hasn't been an updated release of the chart with this change yet.

**Comment by jhamman** [comment]
see #146 for an initial attempt at setting this up.

**Comment by jcrist** [comment]
Closing in favor of #296
