### ISSUE TITLE
Use an sqlalchemy session per request

### ISSUE THREAD

**Issue by yuvipanda** [dask/dask-gateway#138]
The server currently used one DB session per application (from what I can see). This led to complex perf problems in JupyterHub, since sqlalchemy sort of holds a cache of everything you touch in memory. So creating a new object can be much slower when it is object 1000 vs object 1. This hurts a lot on high scale, since you want this to be a constant time operation.

https://github.com/jupyterhub/jupyterhub/pull/1291 and stuff linked to from there has information on how we ran into this in JupyterHub, and how we worked around it (merged as https://github.com/jupyterhub/jupyterhub/pull/1809). However, I think the right thing to do is to have a DB session per request - this forces you into better architectural patterns, useful both in this case and for HA related stuff. We had too much code that would have needed to be changed - I think gateway server is young enough for this to happen. Makes life a lot better in the long run!

**Comment by jcrist** [comment]
Thanks for looking through the code here. I *think* this doesn't matter for us, since we're not using the ORM, we're using sqlalchemy core only, which doesn't have a `Session` object and doesn't do any caching as described above.

**Comment by yuvipanda** [comment]
Ah boom totally missed that! Great call :)
