### ISSUE TITLE
incorrect scheduler address in namespaced kubernetes

### ISSUE THREAD

**Issue by martindurant** [dask/dask-gateway#163]
When running on GKE (this might be specific). Gateway is in its own namespace called "dask-gateway".

A cluster is successfully started like
```
gw = dask_gateway.Gateway("http://web-public-dask-gateway.dask-gateway",
                         proxy_address="tls://scheduler-public-dask-gateway:8786",
                         auth='jupyterhub')
cluster = gw.new_cluster()
```
but it gets the scheduler address `'gateway://scheduler-public-dask-gateway:8786/xxx'`. This is the wrong host, should be `scheduler-public-dask-gateway.dask-gateway`, and results in timeout on connection/get_client().

**Comment by martindurant** [comment]
Note that the dashboard_link is correctly set (I guess this is not actually fetched from the gateway server).

**Comment by jcrist** [comment]
You need to pass the correct address to the `dask_gateway.Gateway` constructor - currently your `proxy_address` is incorrect. The following should work:

```python
gw = dask_gateway.Gateway(
    "http://web-public-dask-gateway.dask-gateway",
    proxy_address="tls://scheduler-public-dask-gateway.dask-gateway:8786",
    auth='jupyterhub'
)
cluster = gw.new_cluster()
```

**Comment by martindurant** [comment]
Ooops!
Sorry for the noise...
