### ISSUE TITLE
`ssl_context` context error when connecting to existing cluster.

### ISSUE THREAD

**Issue by qntnrbns** [dask/dask-gateway#181]
I am having issues when connecting to existing clusters in the gateway (0.6.0). When I run:

```python
from dask_gateway import Gateway, BasicAuth

from dask.distributed import Client

gateway = Gateway(
    '<web-url>',
    proxy_address="'<scheduler-proxy>',",
    auth=BasicAuth("", "password")
)

cluster = gateway.new_cluster()
existing_cluster = gateway.connect(cluster.name)
client = Client(existing_cluster)
```

I get the following error: 

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-33-c12b00e8db36> in <module>
----> 1 client = Client(existing_cluster)

/anaconda3/envs/py37/lib/python3.7/site-packages/distributed/client.py in __init__(self, address, loop, timeout, set_as_default, scheduler_file, security, asynchronous, name, heartbeat_interval, serializers, deserializers, extensions, direct_to_workers, **kwargs)
    724             ext(self)
    725 
--> 726         self.start(timeout=timeout)
    727         Client._instances.add(self)
    728 

/anaconda3/envs/py37/lib/python3.7/site-packages/distributed/client.py in start(self, **kwargs)
    889             self._started = asyncio.ensure_future(self._start(**kwargs))
    890         else:
--> 891             sync(self.loop, self._start, **kwargs)
    892 
    893     def __await__(self):

/anaconda3/envs/py37/lib/python3.7/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    332     if error[0]:
    333         typ, exc, tb = error[0]
--> 334         raise exc.with_traceback(tb)
    335     else:
    336         return result[0]

/anaconda3/envs/py37/lib/python3.7/site-packages/distributed/utils.py in f()
    316             if callback_timeout is not None:
    317                 future = gen.with_timeout(timedelta(seconds=callback_timeout), future)
--> 318             result[0] = yield future
    319         except Exception as exc:
    320             error[0] = sys.exc_info()

/anaconda3/envs/py37/lib/python3.7/site-packages/tornado/gen.py in run(self)
    733 
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:
    737                         exc_info = sys.exc_info()

/anaconda3/envs/py37/lib/python3.7/site-packages/distributed/client.py in _start(self, timeout, **kwargs)
    982 
    983         try:
--> 984             await self._ensure_connected(timeout=timeout)
    985         except OSError:
    986             await self._close()

/anaconda3/envs/py37/lib/python3.7/site-packages/distributed/client.py in _ensure_connected(self, timeout)
   1039                 self.scheduler.address,
   1040                 timeout=timeout,
-> 1041                 connection_args=self.connection_args,
   1042             )
   1043             comm.name = "Client->Scheduler"

/anaconda3/envs/py37/lib/python3.7/site-packages/distributed/comm/core.py in connect(addr, timeout, deserialize, connection_args)
    216                         timedelta(seconds=min(deadline - time(), 1)),
    217                         future,
--> 218                         quiet_exceptions=EnvironmentError,
    219                     )
    220                     break

/anaconda3/envs/py37/lib/python3.7/site-packages/dask_gateway/comm.py in connect(self, address, deserialize, **connection_args)
     39             raise TypeError(
     40                 "Gateway expects a `ssl_context` argument of type "
---> 41                 "ssl.SSLContext, instead got %s" % ctx
     42             )
     43 

TypeError: Gateway expects a `ssl_context` argument of type ssl.SSLContext, instead got None
```

Do anyone have advice for getting around this?

**Comment by jcrist** [comment]
Try:

```
client = cluster.get_client()
```

In newer versions of dask both should work, but for legacy reasons the `get_client()` exists (previous versions of `dask.distributed` wouldn't pull the `security` attribute off a cluster passed to `Client`).

---

Not sure if this is just from debugging, but you also shouldn't need to use `gateway.connect`, the full snippet should be:

```python
from dask_gateway import Gateway, BasicAuth

gateway = Gateway(
    '<web-url>',
    proxy_address="'<scheduler-proxy>',",
    auth=BasicAuth("", "password")
)

cluster = gateway.new_cluster()
client = cluster.get_client()
```

**Comment by qntnrbns** [comment]
@jcrist I am trying to connect to clusters that already exists. Is there an easy way to do that?

**Comment by jcrist** [comment]
Oh, if you're connecting to an existing cluster then `gateway.connect` is the right way. Commenting on your original snippet from above:

```
# Creates a new cluster
cluster = gateway.new_cluster()

# Connects to the same cluster you just created
# This is not needed, `cluster` and `existing_cluster` are identical
existing_cluster = gateway.connect(cluster.name)
...
```

**Comment by qntnrbns** [comment]
> In newer versions of dask both should work, but for legacy reasons the `get_client()` exists (previous versions of `dask.distributed` wouldn't pull the `security` attribute off a cluster passed to `Client`).

Is there a way to pass the clusters security info into the client easily?

**Comment by jcrist** [comment]
> Is there a way to pass the clusters security info into the client easily?

That's what `get_client` does for you. Is there a reason you want to use the `Client` constructor explicitly? If you must for some reason, you can manually pass the `security` argument to be compatible with older versions of dask:

```
client = Client(cluster, security=cluster.security)
```

But I wouldn't do that, I'd just use `client = cluster.get_client()`. One less import, just a method call.

**Comment by qntnrbns** [comment]
Sorry, I think I jumped ahead of myself a little bit.

Using a similar example

> ```python
> from dask_gateway import Gateway, BasicAuth
> 
> from dask.distributed import Client
> 
> gateway = Gateway(
>     '<web-url>',
>     proxy_address="'<scheduler-proxy>',",
>     auth=BasicAuth("", "password")
> )
> 
> cluster = gateway.new_cluster()
> existing_cluster = gateway.connect(cluster.name)
> client = existing_cluster.get_client()
> ```

`existing_cluster.security` returns `None` and the call to `existing_cluster.get_client()` seems to start a local cluster.

**Comment by jcrist** [comment]
Ah, I see. That does sound like a bug. Looking now. What version of dask-gateway?

**Comment by qntnrbns** [comment]
0.6.0 - the latest

**Comment by qntnrbns** [comment]
If you point me in the right direction, I'd love to try and solve it.

**Comment by jcrist** [comment]
Ah, you're correct. The code works correctly in async mode (where we test it), but doesn't in synchronous mode. The fix would be to move https://github.com/dask/dask-gateway/blob/bf531e22bf5f97c8029d2778743cb5b60eca4095/dask-gateway/dask_gateway/client.py#L763-L764 to the end of [this method](https://github.com/dask/dask-gateway/blob/bf531e22bf5f97c8029d2778743cb5b60eca4095/dask-gateway/dask_gateway/client.py#L806-L817) so that both constructors share this code.

Unfortunately our test infrastructure is setup to mostly test things asynchronously - sync tests are a bit verbose. If you'd like to push a PR without a test fixing this, I can patch a test on afterward. If you're feeling bold, an example synchronous test is here: https://github.com/dask/dask-gateway/blob/bf531e22bf5f97c8029d2778743cb5b60eca4095/dask-gateway/dask_gateway/client.py#L806-L817.

```

**Comment by jcrist** [comment]
> If you can point me in the right direction, I'd love to try and solve it.

I'd love for another contributor to this project! That said, I'm giving a talk on dask-gateway this weekend and would like this bug fixed by then and a bugfix release out. If you don't think you can get a patch in by EOD tomorrow then I'll probably need to take this one on myself (sorry).

**Comment by qntnrbns** [comment]
I probably can’t do it by eod so I’ll sit this one out. But let me know how I can contribute.

**Comment by jcrist** [comment]
Should be fixed by #183. Thanks for filing the issue, this was an unfortunate gap in our test suite. High line coverage != high branch coverage. I'll push a bugfix release tomorrow.

> But let me know how I can contribute.

Sure thing. I may ping you on a few issues as they come up.

**Comment by qntnrbns** [comment]
Thank you!

**Comment by qntnrbns** [comment]
Just to be clear are you going to push a minor version soon or should i just use the commit hash?

**Comment by jcrist** [comment]
Version 0.6.1 has been released. It's available on PyPI, should be on conda-forge shortly. Docker images and helm chart have been updated accordingly.
