### ISSUE TITLE
when using dask-gateway-kerberos 0.6.1 I do get following error TypeError: __init__() missing 1 required positional argument: 'adaptive'

### ISSUE THREAD

**Issue by n1tk** [dask/dask-gateway#185]
Using using dask-gateway-kerberos 0.6.1

`cluster = gateway.new_cluster(worker_cores=1)`

> I do get following error TypeError: __init__() missing 1 required positional argument: 'adaptive'

and from DaskGateway: 

> Config option `adaptive_period` not recognized by `YarnClusterManager`.

followed configuration for dask-gateway for hadoop/Yarn ... 

`YARN
YarnClusterManager
c.YarnClusterManager.adaptive_period= Float(3)
Time (in seconds) between adaptive scaling checks.

A smaller period will decrease scale up/down latency when responding to cluster load changes, but may also result in higher load on the gateway server.`

**Comment by jcrist** [comment]
Can you post the full traceback? Without context on where the error comes from, it's hard to help you debug.

I assume you're using conda, what versions do you have for `dask-gateway` and `dask-gateway-server`?

```shell
$ conda list dask-gateway
```

**Comment by n1tk** [comment]
`In [66]: !conda list dask-gateway
# packages in environment at /opt/continuum/anaconda/envs/anaconda50_py36:
#
dask-gateway              0.6.1                    py36_0    custom
dask-gateway-kerberos     0.6.1                    py36_0    custom
`

> from anaconda side:

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-65-c8c560f72698> in <module>()
----> 1 cluster = gateway.new_cluster()

~/anaconda/envs/anaconda50_py36/lib/python3.6/site-packages/dask_gateway/client.py in new_cluster(self, cluster_options, shutdown_on_close, **kwargs)
    589             cluster_options=cluster_options,
    590             shutdown_on_close=shutdown_on_close,
--> 591             **kwargs,
    592         )
    593

~/anaconda/envs/anaconda50_py36/lib/python3.6/site-packages/dask_gateway/client.py in __init__(self, address, proxy_address, auth, cluster_options, shutdown_on_close, asynchronous, loop, **kwargs)
    759             shutdown_on_close=shutdown_on_close,
    760             asynchronous=asynchronous,
--> 761             loop=loop,
    762         )
    763

~/anaconda/envs/anaconda50_py36/lib/python3.6/site-packages/dask_gateway/client.py in _init_internal(self, address, proxy_address, auth, cluster_options, cluster_kwargs, shutdown_on_close, asynchronous, loop, name)
    851             self.status = "starting"
    852         if not self.asynchronous:
--> 853             self.gateway.sync(self._start_internal)
    854
    855     @property

~/anaconda/envs/anaconda50_py36/lib/python3.6/site-packages/dask_gateway/client.py in sync(self, func, *args, **kwargs)
    310             )
    311             try:
--> 312                 return future.result()
    313             except BaseException:
    314                 future.cancel()

~/anaconda/envs/anaconda50_py36/lib/python3.6/concurrent/futures/_base.py in result(self, timeout)
    430                 raise CancelledError()
    431             elif self._state == FINISHED:
--> 432                 return self.__get_result()
    433             else:
    434                 raise TimeoutError()

~/anaconda/envs/anaconda50_py36/lib/python3.6/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

~/anaconda/envs/anaconda50_py36/lib/python3.6/site-packages/dask_gateway/client.py in _start_internal(self)
    865             self._start_task = asyncio.ensure_future(self._start_async())
    866         try:
--> 867             await self._start_task
    868         except BaseException:
    869             # On exception, cleanup

~/anaconda/envs/anaconda50_py36/lib/python3.6/site-packages/dask_gateway/client.py in _start_async(self)
    883         # Connect to cluster
    884         try:
--> 885             report = await self.gateway._wait_for_start(self.name)
    886         except GatewayClusterError:
    887             raise

~/anaconda/envs/anaconda50_py36/lib/python3.6/site-packages/dask_gateway/client.py in _wait_for_start(self, cluster_name)
    514         while True:
    515             try:
--> 516                 report = await self._cluster_report(cluster_name, wait=True)
    517             except TimeoutError:
    518                 # Timeout, ignore

~/anaconda/envs/anaconda50_py36/lib/python3.6/site-packages/dask_gateway/client.py in _cluster_report(self, cluster_name, wait)
    508         resp = await self._fetch(req)
    509         return ClusterReport._from_json(
--> 510             self._public_address, self.proxy_address, json.loads(resp.body)
    511         )
    512

~/anaconda/envs/anaconda50_py36/lib/python3.6/site-packages/dask_gateway/client.py in _from_json(cls, public_address, proxy_address, msg)
    227             scheduler_address=scheduler_address,
    228             dashboard_link=dashboard_link,
--> 229             **msg,
    230         )
    231

TypeError: __init__() missing 1 required positional argument: 'adaptive'`

**Comment by jcrist** [comment]
You don't have the `dask-gateway-server` installed in this environment, I suspect you have an older version of the server installed and running. The project at this point isn't quite stable with client-server protocol, so they need to be upgraded together, and should have the same version number. As things solidify in future releases this restriction should relax.

**Comment by n1tk** [comment]
Thank you. Based on documentation h[ttps://gateway.dask.org/install-hadoop.html#validate-things-are-working](https://gateway.dask.org/install-hadoop.html#validate-things-are-working) is not listed as a requirement for testing part. 
Should I upgrade `dask-gateway-server` on hadoop cluster as well ?

**Comment by jcrist** [comment]
> Should I upgrade dask-gateway-server on hadoop cluster as well

Yes, you need to make sure that `dask-gateway` and `dask-gateway-server` have the same version. Whether that is upgrading your server or downgrading your client is up to you.

> What about the `c.YarnClusterManager.adaptive_period= Float(3)` in gateway config ? need to be excluded ?

I don't follow what your issue is here with this? Is this an error message you got? Some code you added to your config file? The documentation at https://gateway.dask.org/api-server.html#yarnclustermanager lists the available configuration values you *can* set on a cluster manager, not the ones you need to set. Usually the defaults are sufficient (as is likely true for `adaptive_period` here).

**Comment by n1tk** [comment]
Thank you!!!

Worked with downgrade to `0.3.0` and installing on client environment `dask-gateway-server-kerberos` with same version and all work as expected. 

Will give a try later on with `0.6.1 `versions

**Comment by jcrist** [comment]
Sounds good. I'm going to close this for now, feel free to reopen a new issue if you run into issues later.
