### ISSUE TITLE
Issue when importing Gateway, related to Tornado: ImportError: cannot import name 'future_set_exc_info'

### ISSUE THREAD

**Issue by n1tk** [dask/dask-gateway#187]
From `ipython` all works fine, but from `Anaconda Notebook` I keep getting this issue: 
 `ImportError: cannot import name 'future_set_exc_info'`

> from dask_gateway import Gatew

`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-6-26a1a2a3bd8d> in <module>()
----> 1 from dask_gateway import Gateway

~/anaconda/envs/anaconda50_hadoop/lib/python3.6/site-packages/dask_gateway/__init__.py in <module>()
----> 1 from .client import Gateway, GatewayCluster, GatewayClusterError, GatewayServerError
      2 from .auth import KerberosAuth, BasicAuth
      3 from .options import Options
      4 
      5 # Load configuration

~/anaconda/envs/anaconda50_hadoop/lib/python3.6/site-packages/dask_gateway/client.py in <module>()
     10 
     11 import dask
---> 12 from distributed import Client
     13 from distributed.security import Security
     14 from distributed.utils import LoopRunner, sync, thread_state, format_bytes, log_errors

~/anaconda/envs/anaconda50_hadoop/lib/python3.6/site-packages/distributed/__init__.py in <module>()
      1 from . import config
      2 from dask.config import config
----> 3 from .actor import Actor, ActorFuture
      4 from .core import connect, rpc
      5 from .deploy import LocalCluster, Adaptive, SpecCluster, SSHCluster

~/anaconda/envs/anaconda50_hadoop/lib/python3.6/site-packages/distributed/actor.py in <module>()
      1 import asyncio
----> 2 from tornado import gen
      3 import functools
      4 import threading
      5 from queue import Queue

~/anaconda/envs/anaconda50_hadoop/lib/python3.6/site-packages/tornado/gen.py in <module>()
     98 import types
     99 
--> 100 from tornado.concurrent import (Future, is_future, chain_future, future_set_exc_info,
    101                                 future_add_done_callback, future_set_result_unless_cancelled)
    102 from tornado.ioloop import IOLoop

ImportError: cannot import name 'future_set_exc_info'
`

OR

`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-8-e786bfd11a76> in <module>()
----> 1 from tornado import gen

~/anaconda/envs/anaconda50_hadoop/lib/python3.6/site-packages/tornado/gen.py in <module>()
     98 import types
     99 
--> 100 from tornado.concurrent import (Future, is_future, chain_future, future_set_exc_info,
    101                                 future_add_done_callback, future_set_result_unless_cancelled)
    102 from tornado.ioloop import IOLoop

ImportError: cannot import name 'future_set_exc_info'`

Tried to downgrade tornado version, getting latest one but **ImportError** persist ...

**Comment by jcrist** [comment]
It looks like you have a broken conda environment - `tornado` is failing to import a function defined in `tornado`. Perhaps at some point you installed tornado with `pip` instead of `conda`, which broken things? I recommend deleting and recreating your environment and trying again.

**Comment by n1tk** [comment]
New environment using following config did solve connection from anaconda notebook to dask-gateway. Thank you. 

`env_specs:
  dask_anaconda:
    channels:
      - conda-forge
    packages: 
      - dask-gateway=0.3.0
      - dask-gateway-kerberos=0.3.0
      - dask-gateway-server=0.3.0
      - dask=2.8.1
      - dask-core=2.8.1
      - python=3.6.8
      - pandas=0.23.4
      - anaconda-project
      - ipython
      - ipykernel 
just these packages`

**Comment by jcrist** [comment]
Glad to hear it. Closing.
