### ISSUE TITLE
Testing if scheduler proxy is addressable

### ISSUE THREAD

**Issue by gforsyth** [dask/dask-gateway#188]
Running on K8s and having issues getting the scheduler proxy to proxy-out the scheduler-client connection correctly (ssl connection errors).

I have the scheduler proxy deployed behind an ELB that is terminating TLS (there is a separate ELB for the gateway public web service).  If I `curl <scheduler proxy url>` I get a warning about binary output messing up my terminal -- if I ignore this and add `--output -` to the `curl` I get back a single `P` 

```
$ curl https://<snip> --output -
P
```

Similarly, if I try to `openssl s_client -connect` I get cert info from the ELB and then it ends with a `P`:

```
$ openssl s_client -connect <snip>:443
...
---
Pclosed
```

Mostly this is just about narrowing down to where the failure is, but I'm also confused about the `P`.

**Comment by jcrist** [comment]
> I have the scheduler proxy deployed behind an ELB that is terminating TLS

You shouldn't terminate TLS for the ELB that is proxying the schedulers. TLS handling should be passed through from the client, through the ELB, through the scheduler proxy, to the scheduler.

**Comment by gforsyth** [comment]
Ok -- that was initially to get health checks passing since the ELB didn't like the SSL healthcheck.  That said, a TCP healthcheck works and the actually traffic forwarding can remain under TLS.

After changing it over to TLS `openssl s_client -connect` works.

**Comment by jcrist** [comment]
Glad to hear it.
