### ISSUE TITLE
Easily set PVC with sqlite from helm chart

### ISSUE THREAD

**Issue by yuvipanda** [dask/dask-gateway#190]
When doing continuous deployment, it would be great to not kill people's clusters when we make changes to the gateway. We can do this by setting `c.DaskGateway.stop_clusters_on_shutdown` to `False`. However, this requires a backing database on disk like sqlite3, which requires a PVC to be set up. This is what we do for JupyterHub in the helm chart, and we should do that here too!

**Comment by jcrist** [comment]
Agreed. I'm currently focused on #186, hoping to remove the need for a database completely for kubernetes. However, if you wanted to add this to the helm chart in the meantime I'd be happy to review and merge.

**Comment by yuvipanda** [comment]
That sounds good, @jcrist. I'll try take a shot at this and #189

**Comment by jcrist** [comment]
We no longer make use of a database for our k8s deploy (as of version 0.7.0), so this issue is no longer relevant. Closing.

**Comment by yuvipanda** [comment]
Woop Woop!
