### ISSUE TITLE
Unable to reconnect to running cluster

### ISSUE THREAD

**Issue by bschreck** [dask/dask-gateway#192]
Creating a new cluster is fine:
```
gateway = Gateway('http://mygatewayhost:gatewayport', proxy_address=8776)
cluster = gateway.new_cluster()
client = cluster.get_client()
```
However, connecting to an existing one like:
```
gateway = Gateway('http://mygatewayhost:gatewayport', proxy_address=8776)
cluster = gateway.connect(gateway.list_clusters()[0].name)
client = cluster.get_client()
```

Results in the cluster's `scheduler_address` set to `None` (upon creating a new cluster I see this as `'gateway://mygatewayhost:gatewayport/clusterid'`, and the `Client` then creates a `LocalCluster` object instead of trying to connect to the remote host.

Currently to get around this I call `stop_cluster()` and create a new one.

**Comment by bschreck** [comment]
Bumping this. @jcrist

**Comment by jcrist** [comment]
Hi @bschreck, apologies for the lack of response here. What version of `dask-gateway-server` and `dask-gateway` are you using? This looks like the bug fixed in https://github.com/dask/dask-gateway/pull/183 (version 0.6.1), but it may be something else.

**Comment by jcrist** [comment]
Closing as stale. Feel free to reopen if the issue still exists.
