### ISSUE TITLE
"HTTPClientError: HTTP 403: Use Proxy Server" due to local HTTP_PROXY?

### ISSUE THREAD

**Issue by jkmacc-LANL** [dask/dask-gateway#193]
Dask-gateway feels like a great fit for a project I'm involved in, and I'm excited to try it.  Thank you!

I've followed the [Kubernetes + Helm instructions](https://gateway.dask.org/install-kube.html#install-the-helm-chart) to install the server out in the wild, and I'm getting a `HTTPClientError: HTTP 403: Use Proxy Server` when I [try to connect to the public gateway](https://gateway.dask.org/install-kube.html#connecting-to-the-gateway) from my local machine.  I can instantiate the `gateway` just fine, but I can't `.list_clusters()` or `.new_cluster()` without the error above.

I'm behind a corporate web proxy that I usually handle with an `HTTP_PROXY` environmental variable.  Could this be related to my error?  If so, is there a way for me to handle a local web proxy so that I can connect my local gateway client to the external public gateway?

Thanks again.

**Comment by quasiben** [comment]
The proxy may be related to your error.  You may also ned to configure HTTPS_PROXY as well.  Can you try this ?

**Comment by jcrist** [comment]
This is likely related to #103, the http client we use in the `Gateway` client doesn't respect `HTTP_PROXY`. You *may* be able to hack around this by configuring tornado to use `CurlAsyncHTTPClient` yourself.

```python
import dask_gateway

# Use the curl client instead
from tornado.httpclient import AsyncHTTPClient
AsyncHTTPClient.configure("tornado.curl_httpclient.CurlAsyncHTTPClient")

gateway = dask_gateway.Gateway(...)
...
```

Let me know if this works.

**Comment by jkmacc-LANL** [comment]
Thanks for the response!

@quasiben  `HTTPS_PROXY` was already set, as well.  Thanks for the suggestion, though.  

@jcrist This didn't work.  Thanks also for the suggestion.  I made sure it was run in the order you describe.  Below is the traceback from trying to do `gateway.list_clusters()`.  It may be worth trying to connect from somewhere outside the firewall, which I could do later.

```python
---------------------------------------------------------------------------
HTTPClientError                           Traceback (most recent call last)
<ipython-input-13-f8cbd85b6152> in <module>
----> 1 gateway.list_clusters()

~/anaconda3/envs/dask-gateway/lib/python3.7/site-packages/dask_gateway/client.py in list_clusters(self, status, **kwargs)
    408         clusters : list of ClusterReport
    409         """
--> 410         return self.sync(self._clusters, status=status, **kwargs)
    411 
    412     def get_cluster(self, cluster_name, **kwargs):

~/anaconda3/envs/dask-gateway/lib/python3.7/site-packages/dask_gateway/client.py in sync(self, func, *args, **kwargs)
    310             )
    311             try:
--> 312                 return future.result()
    313             except BaseException:
    314                 future.cancel()

~/anaconda3/envs/dask-gateway/lib/python3.7/concurrent/futures/_base.py in result(self, timeout)
    433                 raise CancelledError()
    434             elif self._state == FINISHED:
--> 435                 return self.__get_result()
    436             else:
    437                 raise TimeoutError()

~/anaconda3/envs/dask-gateway/lib/python3.7/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

~/anaconda3/envs/dask-gateway/lib/python3.7/site-packages/dask_gateway/client.py in _clusters(self, status)
    387         url = "%s/gateway/api/clusters/%s" % (self.address, query)
    388         req = HTTPRequest(url=url)
--> 389         resp = await self._fetch(req)
    390         return [
    391             ClusterReport._from_json(self._public_address, self.proxy_address, r)

~/anaconda3/envs/dask-gateway/lib/python3.7/site-packages/dask_gateway/client.py in _fetch(self, req)
    366                         raise GatewayServerError(msg)
    367                     else:
--> 368                         resp.rethrow()
    369         except HTTPError as exc:
    370             # Tornado 6 still raises these above with raise_error=False

~/anaconda3/envs/dask-gateway/lib/python3.7/site-packages/tornado/httpclient.py in rethrow(self)
    675         """If there was an error on the request, raise an `HTTPError`."""
    676         if self.error:
--> 677             raise self.error
    678 
    679     def __repr__(self) -> str:

HTTPClientError: HTTP 403: Use Proxy Server
```

FWIW, the kubectl logs for the scheduler-proxy pod just give a lot of `Extracting SNI: Error reading TLS record header: EOF`, those for the web-proxy are empty, and those for the gateway seem fine except for one restart for `Reason:       Error` 😄

**Comment by quasiben** [comment]
As a sanity check any you hit the scheduler with HTTP_PROXY env vars and curl ?

**Comment by jkmacc-LANL** [comment]
I'm not *exactly* sure what you mean, it sounds like a good idea:-)

I tried pinging the external IP for `scheduler-public-dask-gateway` and `web-public-dask-gateway` services and get timeouts.  When I `curl` them, I get `Not Found`.

**Comment by jcrist** [comment]
It sounds like you can reach the gateway server with `curl` then, but not our client. To confirm, try curling a valid route like `http://web-proxy-address:port/gateway/api/clusters/ --user alice:fakepassword` (assuming you have the default `DummyAuthenticator` configured). If curl can reach the endpoint then we should be able to get the pycurl client to as well.

>  tried pinging the external IP for scheduler-public-dask-gateway and web-public-dask-gateway services and get timeouts. When I curl them, I get Not Found.

The `scheduler-public-dask-gateway` endpoint is a custom protocol server, and doesn't serve http. You should only try connecting to the `web-public-dask-gateway` endpoint.

**Comment by jkmacc-LANL** [comment]
@jcrist I'm a geophysicist and have only the faintest idea of how these magical pipes and wires work 😉 , so I may need a bit more hand-holding.  My apologies.  

Regarding auth, I'm using "dummy" with something in the the "shared password for all users" config.   

I tried `curl http://<web-public-dask-gateway address> --user alice:<the password in my config>`, and get `Not Found`.

**Comment by jcrist** [comment]
Try

```
curl http://<web-public-dask-gateway address>/gateway/api/clusters/ --user alice:<the password in my config>
```

**Comment by jkmacc-LANL** [comment]
(oops, thanks)  Got `{}`.

**Comment by jcrist** [comment]
Ok, so curl works fine. Now try the following:

```python
import asyncio
from tornado.httpclient import AsyncHTTPClient, HTTPRequest

AsyncHTTPClient.configure("tornado.curl_httpclient.CurlAsyncHTTPClient")

async def test():
    client = AsyncHTTPClient()
    req = HTTPRequest(
        url="http://<web-public-dask-gateway address>/gateway/api/clusters/",
        auth_mode="basic",
        auth_username="alice",
        auth_password="<your-password>"
    )
    resp = await client.fetch(req)
    return resp.body

asyncio.run(test())
```

This should do the same as the `curl` command above, but using `tornado` and `pycurl`.

**Comment by jkmacc-LANL** [comment]
Thanks for the continued help.  
URL and password redacted:

```python
In [1]: %paste
import asyncio
from tornado.httpclient import AsyncHTTPClient, HTTPRequest

AsyncHTTPClient.configure("tornado.curl_httpclient.CurlAsyncHTTPClient")

async def test():
    client = AsyncHTTPClient()
    req = HTTPRequest(
        url="http://<the-url>/gateway/api/clusters/",
        auth_mode="basic",
        auth_username="alice",
        auth_password="<my-password>
    )
    resp = await client.fetch(req)
    return resp.body

asyncio.run(test())

## -- End pasted text --
---------------------------------------------------------------------------
HTTPClientError                           Traceback (most recent call last)
<ipython-input-1-fd883f3f2ffa> in <module>
     15     return resp.body
     16
---> 17 asyncio.run(test())

~/anaconda3/envs/dask-gateway/lib/python3.7/asyncio/runners.py in run(main, debug)
     41         events.set_event_loop(loop)
     42         loop.set_debug(debug)
---> 43         return loop.run_until_complete(main)
     44     finally:
     45         try:

~/anaconda3/envs/dask-gateway/lib/python3.7/asyncio/base_events.py in run_until_complete(self, future)
    581             raise RuntimeError('Event loop stopped before Future completed.')
    582
--> 583         return future.result()
    584
    585     def stop(self):

<ipython-input-1-fd883f3f2ffa> in test()
     12         auth_password="<my-password>"
     13     )
---> 14     resp = await client.fetch(req)
     15     return resp.body
     16

HTTPClientError: HTTP 403: Use Proxy Server
```

**Comment by jkmacc-LANL** [comment]
Note, from JupyterLab, I got `RuntimeError: asyncio.run() cannot be called from a running event loop`, so I switched to IPython.

**Comment by jcrist** [comment]
Hmmm, ok. In the environment you're running this in you do have `HTTP_PROXY` set (same environment variables as the environment you ran the previous curl command)?

If so, perhaps pycurl doesn't detect these automatically (unfortunately undocumented). Can you try manually configuring? Same script as above, but swap the `.configure` command for:

```
defaults = {"proxy_host": ..., "proxy_port": ...}
AsyncHTTPClient.configure("tornado.curl_httpclient.CurlAsyncHTTPClient", defaults=defaults)
```

where `proxy_host` maps to a string of the hostname of your proxy, and `proxy_port` is the integer port (note must be an int *not* a string). An `HTTP_PROXY` environment variable composed of these would look like `http://{proxy_host}:{proxy_port}`.

**Comment by jkmacc-LANL** [comment]
> In the environment you're running this in you do have HTTP_PROXY set?

Yes.  `os.environ['HTTP_PROXY']` shows my proxy.

> Same script as above, but swap the .configure command for...

That did it:  

```python
Out[4]: b'{}'
```

**Comment by jcrist** [comment]
Hmmm, ok. You should be able to do 

```python
defaults = {"proxy_host": ..., "proxy_port": ...}
AsyncHTTPClient.configure("tornado.curl_httpclient.CurlAsyncHTTPClient", defaults=defaults)

at the top of your code, then use dask-gateway as normal and everything *should* work. We'll want to find a way to configure this in the long run so it's not necessary though.

**Comment by jkmacc-LANL** [comment]
Now, i'm getting `HTTPClientError: HTTP 401: Unauthorized`, but I think it's because I don't understand authentication :smile:  Thank you for your help!

**Comment by jcrist** [comment]
Ah, you'll need to specify your password to the gateway client.


```python
import dask_gateway

gateway = dask_gateway.Gateway(
    address_stuff, ...,
    auth=dask_gateway.BasicAuth(password=...)
)
```

To avoid having to specify all of this each time as a user, you can optionally configure it once in your dask configuration file. See https://gateway.dask.org/configuration-user.html for more info.

**Comment by jkmacc-LANL** [comment]
Works!  I was actually using a config file, but a had `dummy` instead of `basic` as the auth type.  Must've copied it incorrectly from the server config file.  Thank you again.

**Comment by jkmacc-LANL** [comment]
(PS:  where do I set `EXTRA_CONDA_PACKAGES` to install extra packages on workers?)

**Comment by jcrist** [comment]
That's specific to the dask-kubernetes default images, and doesn't work with dask-gateway. I recommend building your own docker images with whatever extra packages you may need, or create a new issue where we can discuss further options.
