### ISSUE TITLE
Failing to start new cluster on hadoop 

### ISSUE THREAD

**Issue by n1tk** [dask/dask-gateway#194]
I tried 0.3.0/0.6.0 versions for dask-gateway, dask-gateway-server and worked fine till 2 weeks ago, after that we are getting following error from gateway side:

```
INFO impl.YarnClientImpl: Killed application application_xxxxxxx
```

From cluster side I see following entries in log ... Error generated by skein.ApplicationMaster:

```
Shutting down:Application driver failed with exit code 143. This is often due to the application master memory limit being exceeded. See the diagnostics for more information
```

Note: spark jobs run fine and just dask does have the issue ... 

Found similar issue when need to specify `memoryOverhead/resources` when submitting spark apps:

- https://community.cloudera.com/t5/Support-Questions/Diagnostics-Container-killed-on-request-Exit-code-is-143/td-p/240929
- https://stackoverflow.com/questions/41057311/the-value-of-spark-yarn-executor-memoryoverhead-setting

Also from dask documentation I do recall `$ dask-worker scheduler:8786 --nprocs 8 --nthreads 1`
but no info where to specify or where is the config/spec file for `dask-gateway/dask-gateway-server/skein` ... and this parameters can be modified using dask.distributed and I can modify this parameters after creating the cluster but can't find default parameters without the cluster 'alive'

```
from dask.distributed import Client, progress
client = Client(n_workers=2, threads_per_worker=2, memory_limit='1GB')
```

- https://distributed.dask.org/en/latest/worker.html#thread-pool
- https://docs.dask.org/en/latest/configuration.html

The ask: is option to specify this parameters and how (a sample of the config will work perfectly) and I do recall this output/config `Client: 'tls://xxxxxxx:22082' processes=2 threads=4, memory=2.15 G` as default parameters and how we can change them or adjust based on available resources ? 

more logs:

```
> /opt/continuum/anaconda/envs/anaconda50_dask/lib/python3.6/site-packages/dask_gateway/client.py(526)_wait_for_start()
    524                     raise GatewayClusterError(
    525                         "Cluster %r failed to start, see logs for "
--> 526                         "more information" % cluster_name
    527                     )
    528                 elif report.status is ClusterStatus.STOPPED:

> /opt/continuum/anaconda/envs/anaconda50_dask/lib/python3.6/site-packages/dask_gateway/client.py(885)_start_async()
    883         # Connect to cluster
    884         try:
--> 885             report = await self.gateway._wait_for_start(self.name)
    886         except GatewayClusterError:
    887             raise

> /opt/continuum/anaconda/envs/anaconda50_dask/lib/python3.6/site-packages/dask_gateway/client.py(867)_start_internal()
    865             self._start_task = asyncio.ensure_future(self._start_async())
    866         try:
--> 867             await self._start_task
    868         except BaseException:
    869             # On exception, cleanup

> /opt/continuum/anaconda/envs/anaconda50_dask/lib/python3.6/concurrent/futures/_base.py(384)__get_result()
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

> /opt/continuum/anaconda/envs/anaconda50_dask/lib/python3.6/concurrent/futures/_base.py(432)result()
    430                 raise CancelledError()
    431             elif self._state == FINISHED:
--> 432                 return self.__get_result()
    433             else:
    434                 raise TimeoutError()

> /opt/continuum/anaconda/envs/anaconda50_dask/lib/python3.6/site-packages/dask_gateway/client.py(312)sync()
    310             )
    311             try:
--> 312                 return future.result()
    313             except BaseException:
    314                 future.cancel()

> /opt/continuum/anaconda/envs/anaconda50_dask/lib/python3.6/site-packages/dask_gateway/client.py(853)_init_internal()
    851             self.status = "starting"
    852         if not self.asynchronous:
--> 853             self.gateway.sync(self._start_internal)
    854 
    855     @property

> /opt/continuum/anaconda/envs/anaconda50_dask/lib/python3.6/site-packages/dask_gateway/client.py(761)__init__()
    759             shutdown_on_close=shutdown_on_close,
    760             asynchronous=asynchronous,
--> 761             loop=loop,
    762         )
    763 

> /opt/continuum/anaconda/envs/anaconda50_dask/lib/python3.6/site-packages/dask_gateway/client.py(591)new_cluster()
    589             cluster_options=cluster_options,
    590             shutdown_on_close=shutdown_on_close,
--> 591             **kwargs,
    592         )
    593
```

and from yarn:

```
Log Type: application.driver.log

Log Upload Time: Wed Jan 15 13:27:24 -0500 2020

Log Length: 0


Log Type: application.master.log

Log Upload Time: Wed Jan 15 13:27:24 -0500 2020

Log Length: 2440

20/01/15 13:17:30 INFO skein.ApplicationMaster: Starting Skein version 0.8.0
20/01/15 13:17:30 INFO skein.ApplicationMaster: Running as user n1tk
20/01/15 13:17:30 INFO skein.ApplicationMaster: Application specification successfully loaded
20/01/15 13:17:31 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
20/01/15 13:17:31 WARN shortcircuit.DomainSocketFactory: The short-circuit local reads feature cannot be used because libhadoop cannot be loaded.
20/01/15 13:17:32 INFO skein.ApplicationMaster: gRPC server started at node.example.com:41752
20/01/15 13:17:32 INFO skein.ApplicationMaster: WebUI server started at node.example.com:33113
20/01/15 13:17:32 INFO skein.ApplicationMaster: Registering application with resource manager
20/01/15 13:17:33 INFO skein.ApplicationMaster: Initializing service 'dask.worker'.
20/01/15 13:17:33 INFO skein.ApplicationMaster: Starting application driver
20/01/15 13:27:24 INFO skein.ApplicationMaster: Shutting down: Application driver failed with exit code 143. This is often due to the application master memory limit being exceeded. See the diagnostics for more information.
20/01/15 13:27:24 INFO skein.ApplicationMaster: Unregistering application with status FAILED
20/01/15 13:27:24 INFO skein.ApplicationMaster: Deleted application directory hdfs://node/user/n1tk/.skein/application_1576703975308_0051
20/01/15 13:27:24 INFO skein.ApplicationMaster: WebUI server shut down
20/01/15 13:27:24 INFO skein.ApplicationMaster: gRPC server shut down
```

**Comment by n1tk** [comment]
> does fail to connect to cluster .... 

`[I 2020-01-16 16:15:48.304 DaskGateway] Cluster def4011e1f2748c4ac43932794f41ab4 has started, waiting for connection
[I 2020-01-16 16:16:03.386 DaskGateway] 200 GET /api/clusters/def4011e1f2748c4ac43932794f41ab4?wait (127.0.0.1) 19908.86ms
[I 2020-01-16 16:16:23.903 DaskGateway] 200 GET /api/clusters/def4011e1f2748c4ac43932794f41ab4?wait (127.0.0.1) 20014.82ms
[I 2020-01-16 16:16:44.414 DaskGateway] 200 GET /api/clusters/def4011e1f2748c4ac43932794f41ab4?wait (127.0.0.1) 20007.05ms
[I 2020-01-16 16:17:04.917 DaskGateway] 200 GET /api/clusters/def4011e1f2748c4ac43932794f41ab4?wait (127.0.0.1) 19998.28ms
[I 2020-01-16 16:17:25.437 DaskGateway] 200 GET /api/clusters/def4011e1f2748c4ac43932794f41ab4?wait (127.0.0.1) 20016.45ms
application_1576703975308_0072[I 2020-01-16 16:17:45.958 DaskGateway] 200 GET /api/clusters/def4011e1f2748c4ac43932794f41ab4?wait (127.0.0.1) 20018.37ms
[I 2020-01-16 16:18:06.475 DaskGateway] 200 GET /api/clusters/def4011e1f2748c4ac43932794f41ab4?wait (127.0.0.1) 20007.50ms
[I 2020-01-16 16:18:26.997 DaskGateway] 200 GET /api/clusters/def4011e1f2748c4ac43932794f41ab4?wait (127.0.0.1) 20018.87ms
[I 2020-01-16 16:18:47.519 DaskGateway] 200 GET /api/clusters/def4011e1f2748c4ac43932794f41ab4?wait (127.0.0.1) 20014.10ms
[I 2020-01-16 16:19:08.023 DaskGateway] 200 GET /api/clusters/def4011e1f2748c4ac43932794f41ab4?wait (127.0.0.1) 19999.77ms
[I 2020-01-16 16:19:28.541 DaskGateway] 200 GET /api/clusters/def4011e1f2748c4ac43932794f41ab4?wait (127.0.0.1) 20015.13ms
[I 2020-01-16 16:19:49.064 DaskGateway] 200 GET /api/clusters/def4011e1f2748c4ac43932794f41ab4?wait (127.0.0.1) 20018.27ms
[I 2020-01-16 16:20:09.585 DaskGateway] 200 GET /api/clusters/def4011e1f2748c4ac43932794f41ab4?wait (127.0.0.1) 20013.26ms
[I 2020-01-16 16:20:30.103 DaskGateway] 200 GET /api/clusters/def4011e1f2748c4ac43932794f41ab4?wait (127.0.0.1) 20012.63ms
[I 2020-01-16 16:20:50.624 DaskGateway] 200 GET /api/clusters/def4011e1f2748c4ac43932794f41ab4?wait (127.0.0.1) 20018.27ms
[I 2020-01-16 16:21:11.146 DaskGateway] 200 GET /api/clusters/def4011e1f2748c4ac43932794f41ab4?wait (127.0.0.1) 20013.64ms
[I 2020-01-16 16:21:31.656 DaskGateway] 200 GET /api/clusters/def4011e1f2748c4ac43932794f41ab4?wait (127.0.0.1) 20007.48ms
[I 2020-01-16 16:21:52.178 DaskGateway] 200 GET /api/clusters/def4011e1f2748c4ac43932794f41ab4?wait (127.0.0.1) 20017.66ms
 Cluster def4011e1f2748c4ac43932794f41ab4 has started, waiting for connection[I 2020-01-16 16:22:12.692 DaskGateway] 200 GET /api/clusters/def4011e1f2748c4ac43932794f41ab4?wait (127.0.0.1) 20010.76ms
[I 2020-01-16 16:22:33.213 DaskGateway] 200 GET /api/clusters/def4011e1f2748c4ac43932794f41ab4?wait (127.0.0.1) 20017.06ms
[I 2020-01-16 16:22:53.720 DaskGateway] 200 GET /api/clusters/def4011e1f2748c4ac43932794f41ab4?wait (127.0.0.1) 20003.05ms
[I 2020-01-16 16:23:14.242 DaskGateway] 200 GET /api/clusters/def4011e1f2748c4ac43932794f41ab4?wait (127.0.0.1) 20017.50ms
[I 2020-01-16 16:23:34.751 DaskGateway] 200 GET /api/clusters/def4011e1f2748c4ac43932794f41ab4?wait (127.0.0.1) 20005.36ms
[I 2020-01-16 16:23:55.274 DaskGateway] 200 GET /api/clusters/def4011e1f2748c4ac43932794f41ab4?wait (127.0.0.1) 20019.53ms
[I 2020-01-16 16:24:15.796 DaskGateway] 200 GET /api/clusters/def4011e1f2748c4ac43932794f41ab4?wait (127.0.0.1) 20019.19ms
[I 2020-01-16 16:24:36.317 DaskGateway] 200 GET /api/clusters/def4011e1f2748c4ac43932794f41ab4?wait (127.0.0.1) 20016.70ms
[I 2020-01-16 16:24:56.821 DaskGateway] 200 GET /api/clusters/def4011e1f2748c4ac43932794f41ab4?wait (127.0.0.1) 19999.95ms
[I 2020-01-16 16:25:17.342 DaskGateway] 200 GET /api/clusters/def4011e1f2748c4ac43932794f41ab4?wait (127.0.0.1) 20017.69ms
[I 2020-01-16 16:25:37.865 DaskGateway] 200 GET /api/clusters/def4011e1f2748c4ac43932794f41ab4?wait (127.0.0.1) 20018.13ms
[W 2020-01-16 16:25:43.367 DaskGateway] Cluster def4011e1f2748c4ac43932794f41ab4 startup timed out after 600.0 seconds
[I 2020-01-16 16:25:43.368 DaskGateway] Stopping cluster def4011e1f2748c4ac43932794f41ab4...
[I 2020-01-16 16:25:43.370 DaskGateway] 200 GET /api/clusters/def4011e1f2748c4ac43932794f41ab4?wait (127.0.0.1) 4997.74ms
20/01/16 16:25:43 INFO impl.YarnClientImpl: Killed application application_1576703975308_0072
[I 2020-01-16 16:25:43.801 DaskGateway] Stopped cluster def4011e1f2748c4ac43932794f41ab4
`

**Comment by jcrist** [comment]
Hi @n1tk, apologies for the delayed response here.

> I tried 0.3.0/0.6.0 versions for dask-gateway, dask-gateway-server

Are you saying you were running version 0.3.0 `dask-gateway`, 0.6.0 `dask-gateway-server`? These versions *need* to be the same, having different versions between the client and server (for now) will likely result in failures. I'm surprised anything was working at all.

From looking at the logs, it looks like the gateway server starts up your cluster, but then the cluster never successfully connects to the gateway server, so it's eventually killed after a timeout. This is the "exit code 143" error you're seeing on the `ApplicationMaster`. This is the exit code after YARN kills a job, it's not spark specific.

I recommend upgrading both the server and client to the latest release (0.6.1) and seeing if that fixes your problem.

> The ask: is option to specify this parameters and how (a sample of the config will work perfectly) 

Are you asking how you can let users configure some cluster parameters (like worker cores/memory)? This is doable, but needs to be done in the server configuration. See: https://gateway.dask.org/cluster-options.html.

---

*Aside: In the future when you post logs or tracebacks on github, you can wrap them in three backticks which will format them nicely for reading. I've edited your original posts to do this. For more information on github formatting see https://guides.github.com/features/mastering-markdown/*

**Comment by n1tk** [comment]
Thank you @jcrist 

I will try to upgrade to `0.6.1` to see if the issue gets resolved. 

For:
> Are you saying you were running version 0.3.0 dask-gateway, 0.6.0 dask-gateway-server? 

I'm saying that same issue is present when  `0.3.0 dask-gateway` and `0.3.0 dask-gateway-server` OR when `0.6.0 dask-gateway` and `0.6.0 dask-gateway-server` ...

**Comment by jcrist** [comment]
dask-gateway was completely rewritten in 0.7.0 (we're now on 0.8.0), I recommend trying things out on the latest release and seeing if the problem persists. Closing as stale.
