### ISSUE TITLE
Local Development Cycle With Kubernetes Backend

### ISSUE THREAD

**Issue by droctothorpe** [dask/dask-gateway#196]
Would it be possible to provide some further explanation on what the local development cycle for the gateway server looks like?

[This](https://gateway.dask.org/develop.html) page describes the build process.

[This](https://gateway.dask.org/install-local.html#start-the-gateway-server) page describes the local execution process. 

When attempting the latter, I've been unable to establish communication with the Kubernetes cluster described in my kube config (a local deployment of Docker Desktop Kubernetes). 

I've implemented a local development cycle that leverages [Skaffold](https://skaffold.dev/) in conjunction with Helm. Skaffold watches the source files. When a change is detected, it automatically rebuilds the image (I wrote a Dockerfile to COPY and pip install the source code), stores it locally (no pulling to and from a remote registry), and deploys an updated helm chart. The process takes 12 seconds from saved file to functional deployment. It works, and I'd be happy to contribute it upstream if anyone else finds it useful, but I'm wondering what the existing development cycle when interacting with the Kubernetes backend looks like, and if it's possible to implement a cycle that runs the gateway server directly on the host for improved iteration time. 

Thanks!

**Comment by jcrist** [comment]
The gateway requires bidirectional communication with dask clusters, which usually means it needs to be running in a pod inside the cluster.

When developing locally I've been using the script here: https://github.com/dask/dask-gateway/blob/master/continuous_integration/kubernetes/start.sh, which starts a local cluster using `k3d`, and starts a pod mounting the local dev directory. This can then be used to run tests and develop without rebuilding an image, provided you're only developing the `dask-gateway-server` library. 

Previously very little of the implementation was kubernetes-specific, so more complicated features could be tested using the local-processes backend, but as we move towards a separate kubernetes implementation it would be nice to improve the dev tooling here. I don't have any experience with dev tooling like skaffold, so any recommendations you might have would be nice.

**Comment by mmccarty** [comment]
+1 for Skaffold - Some Googling resulted in an [interesting article with k3s and skaffold](https://devopsspiral.com/articles/k8s/k3d-skaffold/).

@dsludwig - I remember your sweet dev tooling based on skaffold. Is it something you would recommend?

**Comment by droctothorpe** [comment]
Should we close this issue given that [this](https://github.com/dask/dask-gateway/pull/207) PR was merged?

**Comment by jcrist** [comment]
Yeah I think so, thanks for the reminder!
