### ISSUE TITLE
Golang Build Constraints

### ISSUE THREAD

**Issue by droctothorpe** [dask/dask-gateway#197]
In this [line](https://github.com/dask/dask-gateway/blob/master/dask-gateway-server/dask-gateway-proxy/fail_without_go_1_12.go#L1)...

It might make sense to use `// +build "go1.12"` instead in order to specify a minimum version as opposed to an exact version.
 
https://golang.org/pkg/go/build/

**Comment by jcrist** [comment]
I think what we have now is correct? That file is only included on Go versions < 1.12 (https://golang.org/pkg/go/build/#hdr-Build_Constraints). Things build fine for me on go 1.12 and 1.13, and fail on 1.11 which is what we want. Have you ran into a problem with this?

**Comment by droctothorpe** [comment]
I was under the impression that `// +build !go1.12` indicates any version other than `1.12`, versus `go1.12` which indicates 1.12 or newer. If that's not the case (and you're able to build on 1.13 without issue), then feel free to close the issue. Thanks!

**Comment by jcrist** [comment]
> I was under the impression that `// +build !go1.12` indicates any version other than `1.12`, versus `go1.12` which indicates `1.12` or newer.

It does. That file has an intentional error so that the build breaks if you try and build it on earlier than 1.12. Since it's not included on >= 1.12 then the build succeeds on more recent versions only.
