### ISSUE TITLE
Error upgrading helm2-deployed gateway with helm3

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask-gateway#201]
Just as an FYI, not sure if there's anything dask-gateway can actually do about this.

In https://github.com/pangeo-data/pangeo-cloud-federation/issues/542 we upgrade an existing deployment (deployed with helm 2.x and tiller) to helm3. Eventually `helm3 upgrade ...` failed with errors like

```
Error: UPGRADE FAILED: cannot patch "gateway-dev-staging-dask-gateway" with kind Deployment: Deployment.apps "gateway-dev-staging-dask-gateway" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/component":"gateway", "app.kubernetes.io/instance":"dev-staging", "app.kubernetes.io/managed-by":"Helm", "app.kubernetes.io/name":"dask-gateway"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

The "managed-by" field was changing from "Tiller" to "Helm"

```
$ helm3 get manifest dev-staging -n dev-staging --revision=443 | less 
...
  name: gateway-dev-staging-dask-gateway
  labels:
    app.kubernetes.io/name: dask-gateway
    helm.sh/chart: dask-gateway-0.6.1
    app.kubernetes.io/instance: dev-staging
    app.kubernetes.io/version: "0.6.1"
    app.kubernetes.io/managed-by: Tiller

$ helm3 get manifest dev-staging -n dev-staging | less 
  name: gateway-dev-staging-dask-gateway
  labels:
    app.kubernetes.io/name: dask-gateway
    helm.sh/chart: dask-gateway-0.6.1
    app.kubernetes.io/instance: dev-staging
    app.kubernetes.io/version: "0.6.1"
    app.kubernetes.io/managed-by: Helm
```

The workaround is to manually patch those prior to upgrading

```
$ kubectl get deployment/gateway-dev-staging-dask-gateway -n dev-staging -o yaml | sed "s/Tiller/Helm/g" | kubectl replace --force=true -f -
$ kubectl get deployment/scheduler-proxy-dev-staging-dask-gateway -n dev-staging -o yaml | sed "s/Tiller/Helm/g" | kubectl replace --force=true -f -
$ kubectl get deployment/web-proxy-dev-staging-dask-gateway -n dev-staging -o yaml | sed "s/Tiller/Helm/g" | kubectl replace --force=true -f -
```

After that, the helm upgrade succeeded.

Other charts (e.g. jupyterhub) weren't affected by this. Perhaps this field shouldn't be set? https://github.com/dask/dask-gateway/blob/b6b71dc794d369d959a13db8c2ad14ef4ccdca64/resources/helm/dask-gateway/templates/_helpers.tpl#L44

See https://github.com/pangeo-data/pangeo-cloud-federation/issues/542#issuecomment-585880443 for more.

**Comment by jcrist** [comment]
Ugh, yeah, this is the same issue as https://github.com/dask/dask-gateway/pull/147. The helm docs have since been fixed, but this used to also be recommended to be in `matchLabels`. It's fine to be in labels, as it's good for querying, but we can't use it in selectors. Thanks for the report, will fix.

**Comment by TomAugspurger** [comment]
Not relevant anymore.
