### ISSUE TITLE
Does dask-gateway support newer version of dask when using helm to deploy?

### ISSUE THREAD

**Issue by trivid** [dask/dask-gateway#213]
Currently (0.6.1) the dask-gateway image is built with dask=2.8.1 when deployed using helm. [Dockerfile](https://github.com/dask/dask-gateway/blob/master/resources/helm/images/dask-gateway/Dockerfile)
Are newer version of dask supported?

Are there anyway we can override the dask version during helm deployment?

**Comment by droctothorpe** [comment]
I'm not sure if newer versions of Dask are supported, but you can test it pretty simply. 

[Here's](https://github.com/dask/dask-gateway/blob/master/resources/helm/images/dask-gateway/Dockerfile#L11) where the version is specified in the Dockerfile.

You could update the Dockerfile to specify your desired version, build and push an updated image, then update [this](https://github.com/dask/dask-gateway/blob/master/resources/helm/dask-gateway/values.yaml#L60) section of values.yaml to point to your updated image.

**Comment by jcrist** [comment]
dask-gateway 0.6.1 should work fine with the latest release of dask. To use it, build your own image with the desired version of dask - the only thing that matters for us is that `dask-gateway` is installed in the image. Then configure the `image` by setting the following in your helm values file before installing. See our docs for more information on installing with helm: https://gateway.dask.org/install-kube.html.

```yaml
gateway:
  clusterManager:
    image:
      name: YOUR_IMAGE_NAME
      tag: YOUR_IMAGE_TAG
```

**Comment by rokroskar** [comment]
Installing the vanilla dask-gateway helm chart I had to use these requirements in my jupyter notebook:

```
dask==2.8.1
distributed==2.8.1
dask-gateway
msgpack<1.0.0
```

With dask/distributed `2.11.0` I had a number of issues.

**Comment by jcrist** [comment]
Closing as resolved. If there is still more to do here please feel free to reopen.
