### ISSUE TITLE
Standardize and document REST api

### ISSUE THREAD

**Issue by jcrist** [dask/dask-gateway#214]
Much of the REST api came about organically as I was developing. Before the next release, it would be good to go over the existing api and make sure we're happy with the routes and parameter names. We should then document the api and avoid breaking it in the future. This should allow more flexibility between the client and server versions, which are currently tightly coupled.

**Comment by jcrist** [comment]
Ok, I just did a read through of the API, and overall I'm how it's currently written. A few open questions:

- The cluster options specification are currently serialized using a custom spec description format. This could *almost* be implemented using json-schema (http://json-schema.org/), except that field names in json-schema are unordered, and we'd like an order for nicely generating a form. For now I'm tempted to punt on this and leave our custom format - the only consumer of it is the client library, and it's pretty stable.
- Should we version the api? JupyterHub doesn't, but that's not really a good argument not to. If we were to version the api, I'd probably just move `/api` to `/api/v1/` and go from there. Versioning only would be important if we expect client and server versions to vary widely *and* we ever introduce a breaking change in the api. The only downside of versioning the api is that as new versions are added we end up with an increasing number of routes. Right now I'm leaning towards versioning.

cc @gforsyth, @droctothorpe for thoughts.

**Comment by gforsyth** [comment]
> did a read through of the API, and overall I'm happy with how it's currently written.

I agree, I think the API is solid.

> * The cluster options specification are currently serialized using a custom spec description format. This could _almost_ be implemented using json-schema (http://json-schema.org/), except that field names in json-schema are unordered, and we'd like an order for nicely generating a form. For now I'm tempted to punt on this and leave our custom format - the only consumer of it is the client library, and it's pretty stable.

I think it's fine to punt on this.  


> * Should we version the api? JupyterHub doesn't, but that's not really a good argument not to. If we were to version the api, I'd probably just move `/api` to `/api/v1/` and go from there. Versioning only would be important if we expect client and server versions to vary widely _and_ we ever introduce a breaking change in the api. The only downside of versioning the api is that as new versions are added we end up with an increasing number of routes. Right now I'm leaning towards versioning.

I think versioning is a good idea.  Having versions doesn't mean they can't be deprecated later, and there would be a clear upgrade path, so I think the number of routes can have an upper bound.

**Comment by jcrist** [comment]
Cool, I'm going to take care of this today. We're pretty close to being ready to release.

One question I'm having is if we should move the `/api/health` route out of the `/api` path. This is definitely an opinion question, so we just need to pick one and stick with it. The health check is unauthenticated and is unlikely to change in api. It's also not something that a user is likely to interact with directly. A few options:

- `/health` - Top level, unversioned
- `/api/health` - Still marked as api, but unversioned
- `/api/v1/health` - Marked as api, versioned

Right now I'm leaning towards either `/health` or `/api/health`. If no one has thoughts (cc @gforsyth) I'll probably pick one in a few hours and run with it.

**Comment by gforsyth** [comment]
My initial reaction was `/api/health`, but:

I'm thinking of a scenario in which `v1` is deployed and `v2` is being deployed on a separate instance/pod/thing (this is maybe not realistic / possible, just checking).  If that's the case, then versioned health checks might make sense if only to avoid giving false positives because oldThing™ still works while newThing™ is busted.

Even if that is the case, it seems like a far edge case.  I think I'm still in the `/api/health` camp

**Comment by droctothorpe** [comment]
FWIW, I lean towards`/health`.
