### ISSUE TITLE
Add `PodSecurityPolicy` directive for traefik pod

### ISSUE THREAD

**Issue by gforsyth** [dask/dask-gateway#224]
The traefik default pod runs as root for Reasons™: https://github.com/containous/traefik-library-image/issues/38

If a `PodSecurityPolicy` is in place, it will prevent `traefik` from starting (because `root`) -- fix is to add an option to `runAsUser` to the `traefik` spec if `PodSecurityPolicy` is enabled.

**Comment by jcrist** [comment]
Hmmm, perhaps we should just do this by default for all cases.

**Comment by gforsyth** [comment]
That much simpler, I guess
