### ISSUE TITLE
A username with @ --> Invalid k8s label

### ISSUE THREAD

**Issue by consideRatio** [dask/dask-gateway#240]
A user attempting to create a cluster (JupyterHub authentication) with `@` in their username, will experience an error. This is because at some point an invalid Kubernetes resource is being created due to this, the invalid part is a label that has a value with the username, and a Kubernetes label values isn't allowed to contain `@`.

## How I reproduce the issue

```python
from dask_gateway import Gateway
# jupyterhub auth is configured in /etc/dask/gateway.yaml
# my username is erik@example.com
gateway = Gateway(address="http://api-dask-gateway.dask-gateway:8000")
cluster = gateway.new_cluster()
```

## Logs from deploy/api

```
[I 2020-04-09 11:03:16.794 DaskGateway] Creating cluster dask-gateway.c8451c67dc094eb1ad9918b8260c527a for user erik@example.com
[E 2020-04-09 11:03:16.813 aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/opt/conda/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/opt/conda/lib/python3.7/site-packages/dask_gateway_server/routes.py", line 13, in inner
    return await handler(request)
  File "/opt/conda/lib/python3.7/site-packages/dask_gateway_server/routes.py", line 47, in inner
    return await auth.authenticate_and_handle(request, handler)
  File "/opt/conda/lib/python3.7/site-packages/dask_gateway_server/auth.py", line 102, in authenticate_and_handle
    response = await handler(request)
  File "/opt/conda/lib/python3.7/site-packages/dask_gateway_server/routes.py", line 124, in create_cluster
    cluster_name = await backend.start_cluster(user, cluster_options)
  File "/opt/conda/lib/python3.7/site-packages/dask_gateway_server/backends/kubernetes/backend.py", line 343, in start_cluster
    "gateway.dask.org", self.crd_version, config.namespace, "daskclusters", obj
  File "/opt/conda/lib/python3.7/site-packages/kubernetes_asyncio/client/api_client.py", line 166, in __call_api
    _request_timeout=_request_timeout)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes_asyncio/client/rest.py", line 230, in POST
    body=body))
  File "/opt/conda/lib/python3.7/site-packages/kubernetes_asyncio/client/rest.py", line 181, in request
    raise ApiException(http_resp=r)
kubernetes_asyncio.client.rest.ApiException: (422)
Reason: Unprocessable Entity
HTTP response headers: <CIMultiDictProxy('Audit-Id': 'd2c5666f-def5-4989-b221-0f40fce9137c', 'Content-Type': 'application/json', 'Date': 'Thu, 09 Apr 2020 11:03:16 GMT', 'Content-Length': '1018')>
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"DaskCluster.gateway.dask.org \"c8451c67dc094eb1ad9918b8260c527a\" is invalid: metadata.labels: Invalid value: \"erik@example.com\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')","reason":"Invalid","details":{"name":"c8451c67dc094eb1ad9918b8260c527a","group":"gateway.dask.org","kind":"DaskCluster","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: \"erik@example.com\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')","field":"metadata.labels"}]},"code":422}
```

**Comment by gforsyth** [comment]
Hey @consideRatio -- setting the user label is currently hardcoded here:
https://github.com/dask/dask-gateway/blob/master/dask-gateway-server/dask_gateway_server/backends/kubernetes/controller.py#L1072-L1083

What do you think would be the appropriate solution here?  Strip out unsupported characters?

**Comment by consideRatio** [comment]
- We need to encode the username if we store it in labels.
- Base64 is common in k8s, and would work well here except for its trailing `=`.
- Stripping Base64 encoding of its padding is a lossless operation and can be reversed
- Base64 represents 6 bits with a character instead of 8 bits as in ASCII, which means that it will make us use more characters per information.
- Labels are limited to 63 characters, and if we base64 encode ASCII we are limited to 45 characters in practice using base64 encoding.
- Among my JupyterHub dpeloyment with 450 users with various emails, I had one with more than 45 characters. It will happen.

How are these usernames used? do we need to stay lossless?

Base64 can encode to `+` and `/` which are also invalid, and if we use `-`, `.`, or `_` which can be valid within the labels, we risk having issues because they will be invalid if they are at the first or last position.

**Comment by consideRatio** [comment]
This is common in the code base it seems.

```python
        username = cluster["metadata"]["labels"].get("gateway.dask.org/user")
        pod = self.make_pod(namespace, name, username, config, is_worker=True)
```

But since `make_pod`, `make_secret`, `make_service` etc, all use the username to generate a label again rather than for something else, it may not be relevant to be able to extract the username from the label.

**Comment by jcrist** [comment]
Ah, I hadn't realized there were restrictions on label values, my mistake. We use this label to store the user associated with the object. On the `DaskCluster` object we do need a way to get the actual username from the object. The labels were added to other objects (pods, etc...) to make querying all pods for a user easier.

Base64 encoding is appealing, but as you pointed out reduces the max username length.

Right now I'm leaning towards storing the username in the CRD object instead of a label, and dropping (or modifying) the username label for child objects.

**Comment by consideRatio** [comment]
I think the path I'd suggest would be:
1. Make all code be one directional, so going from username to encoded label is okay, but never assume being able to go the other way. This means `make_xxx` functions needs to be modified to accept the encoded value directly instead of taking a username that it then encode.
2. Come up with a one directional unique encoding. It is probably useful to be able to recognize the user even though it isn't the exact username.

**Comment by jcrist** [comment]
> Assuming we do need to retain the username

We do need to retain the username (as I said above). Storing it in the CRD is fine. The labels on the child objects were only added to make querying easier, but if we can't use the username directly then I think username labels are less useful - I'm leaning towards dropping them. All child objects are already labeled with a `gateway.dask.org/cluster` label, so it's possible to take an object, find the associated cluster, and get the username from that.

**Comment by consideRatio** [comment]
@jcrist yepp sounds good, it sounds robust and that is what I think is most important.

**Comment by gforsyth** [comment]
For users of `kubecost`, my understanding (which is _very_ limited on this front) is that it tracks labels and annotations and sticks them into prometheus for tracking usage, etc.  
`kubecost` doesn't appear to be hugely extensible (this is where my limited knowledge is coming in to play) so for organizations that need to track usage on a per-user basis having the username as a label is helpful.

That said, if it breaks for certain username patterns, then leaving it as a label doesn't make sense.

I added it back in using `extra_worker_pod_labels` via a cluster option which works fine on our end -- would example configurations for how to set these things up be helpful in the docs?

**Comment by jcrist** [comment]
Annotations don't have the same restrictions as limits, perhaps we add an annotation with the username? Using kubecost, is it easier to have the organization set the annotation/label convention, or would us providing a standard label be better?

And yeah, config examples are always welcome.

**Comment by consideRatio** [comment]
Ah @jcrist the difference between the [annotations](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#syntax-and-character-set) concept docs and the [labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set) concept docs under the syntax-and-character-set section is indeed that the labels have restrictions on their values while the annotations doesn't! Nice!

> Valid label values must be 63 characters or less and must be empty or begin and end with an alphanumeric character ([a-z0-9A-Z]) with dashes (-), underscores (_), dots (.), and alphanumerics between.

**Comment by jcrist** [comment]
I originally used a label because you can use label selectors to filter objects by users (you can't select by annotation).

> Annotations don't have the same restrictions as limits, perhaps we add an annotation with the username?

On second thought, I think I like not setting this annotation by default, and relying on the user to manage this themselves in the configuration (using e.g. `extra_worker_pod_annotations`). Internally we track the username as part of the CRD object, no need to duplicate it as an annotation if we don't need to.
