### ISSUE TITLE
address / proxy_address in dask-gateway's Gateway constructor

### ISSUE THREAD

**Issue by consideRatio** [dask/dask-gateway#246]
## Background
I'm confused on initialization of `dask_gateway.Gateway`.

__My desired outcomes__
1. `gateway = Gateway(address=..., proxy_address=...)` without errors
2. `cluster = gateway.create_cluster()` without errors
3. `client = cluster.get_client()` without errors
4. `client` links are usable from a browser

__My open questions__
- Will https cause issues?
- Will a path prefix cause issues?

![image](https://user-images.githubusercontent.com/3837114/79038916-966df980-7bdd-11ea-81c9-53e91381cf04.png)

## My setup
- dask-gateway is configured with a prefix `/services/dask-gateway`, which means traefik will trip it.
- jupyterhub is configured to proxy `/services/dask-gateway` to dask-gateway's traefik
- nginx-ingress is configured to terminate TLS for the jupyterhub proxy

__Addresses of relevance__
I've tested that all these work with the `/api/version` endpoint.

- `https://jupyter.example.com/services/dask-gateway`
  - This is accessible by my users' browsers, while the others below will only be accessible from the server they control through jupyterhub.
- `http://proxy-public.jupyterhub/services/dask-gateway`
  - This relies on the `<k8s servicename>.<k8s namespace>` DNS name, and that JupyterHub is configured to pass forward traffic to dask-gateway's traefik.
- `http://traefik-dask-gateway.dask-gateway/services/dask-gateway`
- `http://api-dask-gateway.dask-gateway:8000`
  - Note that the prefix is excluded here, this is because the dask-gateway-server doesn't expect it. It is only expected by treafik which will strip it and pass it onwards.

### Attempt 1

```python
gateway = Gateway(
    address="http://api-dask-gateway.dask-gateway:8000",
    proxy_address="https://jupyter.example.com/services/dask-gateway",
)
cluster = gateway.new_cluster(options)
client = cluster.get_client()
```

Note how this fail by a connection attempt to `gateway://jupyter.example.com/dask-gateway.e809a46ff48742e1add7802ff563b0d2` which seems like **a failure because the prefix isn't passed considered correctly**.

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
/opt/conda/lib/python3.6/site-packages/distributed/comm/core.py in connect(addr, timeout, deserialize, connection_args)
    231             if not comm:
--> 232                 _raise(error)
    233         except FatalCommClosedError:

/opt/conda/lib/python3.6/site-packages/distributed/comm/core.py in _raise(error)
    212         )
--> 213         raise IOError(msg)
    214 

OSError: Timed out trying to connect to 'gateway://jupyter.example.com/dask-gateway.e809a46ff48742e1add7802ff563b0d2' after 10 s: in <dask_gateway.comm.GatewayConnector object at 0x7f4827c9bb70>: ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
<ipython-input-24-07e27b102cb5> in <module>
----> 1 client = cluster.get_client()
      2 client

/opt/conda/lib/python3.6/site-packages/dask_gateway/client.py in get_client(self, set_as_default)
   1026             set_as_default=set_as_default,
   1027             asynchronous=self.asynchronous,
-> 1028             loop=self.loop,
   1029         )
   1030         if not self.asynchronous:

/opt/conda/lib/python3.6/site-packages/distributed/client.py in __init__(self, address, loop, timeout, set_as_default, scheduler_file, security, asynchronous, name, heartbeat_interval, serializers, deserializers, extensions, direct_to_workers, **kwargs)
    719             ext(self)
    720 
--> 721         self.start(timeout=timeout)
    722         Client._instances.add(self)
    723 

/opt/conda/lib/python3.6/site-packages/distributed/client.py in start(self, **kwargs)
    892             self._started = asyncio.ensure_future(self._start(**kwargs))
    893         else:
--> 894             sync(self.loop, self._start, **kwargs)
    895 
    896     def __await__(self):

/opt/conda/lib/python3.6/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    346     if error[0]:
    347         typ, exc, tb = error[0]
--> 348         raise exc.with_traceback(tb)
    349     else:
    350         return result[0]

/opt/conda/lib/python3.6/site-packages/distributed/utils.py in f()
    330             if callback_timeout is not None:
    331                 future = asyncio.wait_for(future, callback_timeout)
--> 332             result[0] = yield future
    333         except Exception as exc:
    334             error[0] = sys.exc_info()

/opt/conda/lib/python3.6/site-packages/tornado/gen.py in run(self)
    733 
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:
    737                         exc_info = sys.exc_info()

/opt/conda/lib/python3.6/site-packages/distributed/client.py in _start(self, timeout, **kwargs)
    990 
    991         try:
--> 992             await self._ensure_connected(timeout=timeout)
    993         except OSError:
    994             await self._close()

/opt/conda/lib/python3.6/site-packages/distributed/client.py in _ensure_connected(self, timeout)
   1047                 self.scheduler.address,
   1048                 timeout=timeout,
-> 1049                 connection_args=self.connection_args,
   1050             )
   1051             comm.name = "Client->Scheduler"

/opt/conda/lib/python3.6/site-packages/distributed/comm/core.py in connect(addr, timeout, deserialize, connection_args)
    241                 backoff = min(backoff, 1)  # wait at most one second
    242             else:
--> 243                 _raise(error)
    244         else:
    245             break

/opt/conda/lib/python3.6/site-packages/distributed/comm/core.py in _raise(error)
    211             error,
    212         )
--> 213         raise IOError(msg)
    214 
    215     backoff = 0.01

OSError: Timed out trying to connect to 'gateway://jupyter.example.com/dask-gateway.e809a46ff48742e1add7802ff563b0d2' after 10 s: Timed out trying to connect to 'gateway://jupyter.example.com/dask-gateway.e809a46ff48742e1add7802ff563b0d2' after 10 s: in <dask_gateway.comm.GatewayConnector object at 0x7f4827c9bb70>: ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by consideRatio** [comment]
## Debugging

Perhaps we should add the ability to override the `gateway.public_address` with an argument to the Gateway() constructor. I found this, which indicates that is intented to be possible.

```python
        if address is None:
            address = format_template(dask.config.get("gateway.address"))
        if address is None:
            raise ValueError(
                "No dask-gateway address provided or found in configuration"
            )
        address = address.rstrip("/")

        public_address = format_template(dask.config.get("gateway.public-address"))
        if public_address is None:
            public_address = address
        else:
            public_address = public_address.rstrip("/")

        if proxy_address is None:
            proxy_address = format_template(dask.config.get("gateway.proxy-address"))
```

**Comment by consideRatio** [comment]
## Attempt 2

```yaml
gateway:
        address: http://api-dask-gateway.dask-gateway:8000
        proxy-address: http://traefik-dask-gateway.dask-gateway/services/dask-gateway
        public-address: https://jupyter.dsp.sandvik.com/services/dask-gateway
```

This led to the same error as I had in Attemp 1 on `cluster.get_client()`.

```
OSError: Timed out trying to connect to 'gateway://jupyter.dsp.sandvik.com:443/dask-gateway.309debbea5894a0aa3e8bfbfae538d1a' after 10 s: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)
```

**Comment by jcrist** [comment]
Yeah, this can be a bit confusing - I think this is more likely a docs issue than an actual bug.

A user of dask-gateway communicates with the server(s) over a couple ways:

- The `Gateway` client sends REST api calls over HTTP(S) to the api server. This is the `address` in the Gateway constructor.
- The `Gateway` client initiates a client->dask-scheduler connection over TLS, using the `gateway://` protocol (our custom client-scheduler proxy scheme). This is the `proxy_address` in the Gateway constructor.
- The user may want to view the dask dashboards using their browser. This is the `public_address`, which is not currently configurable in the constructor (fixable), but is configurable with the dask configuration.

All user connections are intended to pass through `traefik`. Users should never directly interact with the api server or individual dask clusters.

By default, traefik is configured to run both the `http://` and `gateway://` protocols through the same port. Users only need to pass in the address to traefik and everything should work fine.

However, things that speak HTTP *can* have extra proxies in front of them - the JupyterHub proxy for example. In this case users would pass the proxied url as `address` to the `Gateway` constructor (e.g. `https://jupyterhub-url/services/dask-gateway`). But since the JupyterHub proxy doesn't speak the `gateway://` protocol (and thus can't proxy client->scheduler connections), users will need to configure the `proxy_address` to point to the traefik proxy directly.

I *think* the following configuration should work for you:

```yaml
gateway:
  address: https://jupyter.example.com/services/dask-gateway
  proxy-address: gateway://traefik-dask-gateway.dask-gateway:80
```

This will pass all api requests through the jupyterhub proxy. Dashboards will also be viewed through the JupyterHub proxy. Dask client connections will go directly through traefik, which is configured to run on port 80 by default.

Since your users will be interacting with dask-gateway from inside the k8s cluster, you could configure it to send api requests directly to traefik (skipping the JupyterHub proxy middleman). Dashboards would still be viewed through the JupyterHub proxy.

```yaml
gateway:
  address: http://traefik-dask-gateway.dask-gateway/services/dask-gateway
  # the correct proxy_address should be automatically inferred from `address` above,
  # but could also be configured explicitly as
  # proxy-address: gateway://traefik-dask-gateway.dask-gateway:80
  public-address: https://jupyter.example.com/services/dask-gateway
```

This is the configuration I recommend when using with JupyterHub if all requests will be coming from inside the k8s cluster. In this case you could also change the type of the traefik service from `LoadBalancer` to `ClusterIp`.

Please let me know if the above works for you. I think we have the following TODOs from this issue:

- [ ] Better document the different addresses, both generally and in a k8s context
- [ ] Make `public_address` configurable in the `Gateway` constructor

**Comment by consideRatio** [comment]
```yaml
gateway:
  address: http://traefik-dask-gateway.dask-gateway/services/dask-gateway
  # the correct proxy_address should be automatically inferred from `address` above,
  # but could also be configured explicitly as
  # proxy-address: gateway://traefik-dask-gateway.dask-gateway:80
  public-address: https://jupyter.example.com/services/dask-gateway
```

### Error on gateway.get_client()
```
OSError: Timed out trying to connect to 'gateway://traefik-dask-gateway.dask-gateway/dask-gateway.52c145191c524ba8a36cc89ec11d1afd' after 10 s: connect() didn't finish in time
```

### Error cause guessing
1. We failed to explicitly declare the port to use in the gateway protocol, perhaps because http implied port 80 while gateway maybe didn't. Note it was not explicitly written out in `address: http://traefik-dask-gateway.dask-gateway/services/dask-gateway`.
2. We may have failed to consider prefixes? Looking at the ingressroute created along with the DaskCluster resource we can see that it will route `/services/dask-gateway/clusters/` where the /services/dask-cluster is my prefix and /clusters is an added bonus. The middleware to strip /services/dask-cluster/clusters will be applied to any route matching this rule, but not before considering if it matches the rule.

   ```yaml
   apiVersion: traefik.containo.us/v1alpha1
   kind: IngressRoute
   metadata:
     creationTimestamp: "2020-04-14T07:16:51Z"
     generation: 1
     labels:
       app.kubernetes.io/component: dask-scheduler
       app.kubernetes.io/name: dask-gateway
       app.kubernetes.io/version: 0.7.1
       gateway.dask.org/cluster: 52c145191c524ba8a36cc89ec11d1afd
       gateway.dask.org/instance: dask-gateway
     name: dask-gateway-52c145191c524ba8a36cc89ec11d1afd
     namespace: dask-gateway
     ownerReferences:
     - apiVersion: v1
       kind: Pod
       name: dask-gateway-52c145191c524ba8a36cc89ec11d1afd
       uid: 0389a3fb-f942-463f-baec-c8cce4815e13
     resourceVersion: "183436328"
     selfLink: /apis/traefik.containo.us/v1alpha1/namespaces/dask-gateway/ingressroutes/dask-gateway-52c145191c524ba8a36cc89ec11d1afd
     uid: 81616e9e-ab33-4ee9-9e1d-e686f4073f06
   spec:
     entryPoints:
     - web
     routes:
     - kind: Rule
       match: PathPrefix(`/services/dask-gateway/clusters/dask-gateway.52c145191c524ba8a36cc89ec11d1afd/`)
       middlewares:
       - name: clusters-prefix-dask-gateway
         namespace: dask-gateway
       services:
       - name: dask-gateway-52c145191c524ba8a36cc89ec11d1afd
         namespace: dask-gateway
         port: 8787
   ```

**Comment by consideRatio** [comment]
I did some tracing to see how the client's scheduler address that I suspect to be wrong was passed to the client. I think this address needs to have the prefix + /clusters set, as it goes to the traefik pod, which will listen to the prefix and prefix+/clusters paths according to ingressroute objects defined, but it will not listen directly to /myclustername, which is what I think cause the issue I'm observing after explicitly writing out `:80` that took me further.

```python
# I think cluster.get_client() return an invalid scheduler address, so
# this is the trace of code from the call to get_client leading to the returned client

class GatewayCluster:
    # self.scheduler_address is wrong here I think
    def get_client:
        client = Client(self.scheduler_address, ...)

    # so where is self.scheduler_address set?
    def _start_async:
        report = await self.gateway._wait_for_start(self.name)
        self.scheduler_address = report.scheduler_address

class Gateway:
    # _wait_for_start gave us the report that contained scheduler_address!
    def _wait_for_start:
        report = await self._cluster_report(cluster_name, wait=True)

    # ... following _cluster_report!
    def _cluster_report:
        url = "%s/api/v1/clusters/%s%s" % (self.address, cluster_name, params)
        resp = await self._request("GET", url)
        data = await resp.json()
        return ClusterReport._from_json(self._public_address, self.proxy_address, data)

class ClusterReport:
    # _from_json is a class method, not using any knowledge about the specific
    # cluster unless it was passed to it, so if we want to inject some
    # additional information if needed about prefix, it needs to be passed to
    # this function either through the `msg` param or as a dedicated param etc.
    def _from_json(cls, public_address, proxy_address, msg):
        start_time = datetime.fromtimestamp(msg.pop("start_time") / 1000)
        stop_time = msg.pop("stop_time")
        if stop_time is not None:
            stop_time = datetime.fromtimestamp(stop_time / 1000)

        name = msg.pop("name")
        status = ClusterStatus._create(msg.pop("status"))
        scheduler_address = (
            "%s/%s" % (proxy_address, name) if status == ClusterStatus.RUNNING else None
        )

        dashboard_route = msg.pop("dashboard_route")
        dashboard_link = (
            "%s%s" % (public_address, dashboard_route) if dashboard_route else None
        )

        return cls(
            start_time=start_time,
            stop_time=stop_time,
            name=name,
            status=status,
            scheduler_address=scheduler_address,
            dashboard_link=dashboard_link,
            **msg,
        )
```

**Comment by jcrist** [comment]
> Adding :80 was required to avoid a connection timeout issue during the gateway.get_client() call

> We failed to explicitly declare the port to use in the gateway protocol, perhaps because http implied port 80 while gateway maybe didn't

Given the below config, where did you need to add a port?

```yaml
gateway:
  address: http://traefik-dask-gateway.dask-gateway/services/dask-gateway
  public-address: https://jupyter.example.com/services/dask-gateway
```

If `proxy_address` isn't specified in the constructor or the config, we infer it from `address`. The port is taken from the scheme (`http` -> `80`, `https` -> `443`), and the scheme is switched to `gateway`. When I run with the above, I end up with an inferred `proxy_address` of `gateway://traefik-dask-gateway.dask-gateway:80`, which is correct. Are you seeing different behavior?

> We may have failed to consider prefixes? Looking at the ingressroute created along with the DaskCluster resource we can see that it will route /services/dask-gateway/clusters/ where the /services/dask-cluster is my prefix and /clusters is an added bonus.

> I did some tracing to see how the client's scheduler address that I suspect to be wrong was passed to the client. I think this address needs to have the prefix + /clusters set, as it goes to the traefik pod

The client communicates with the scheduler using the `gateway` protocol, which *is not an HTTP protocol*. Both our custom proxy (used for everything but k8s) and traefik (used for k8s) support multiplexing an HTTP proxy and a TCP proxy over the same port. If a non HTTP connection is made (such as client->scheduler requests), the TCP proxy is used. URLs with the `gateway://` scheme are composed of `gateway://{HOST}:{PORT}/{CLUSTER_NAME}`, where `CLUSTER_NAME` is used to negotiate through the TCP proxy for routing (uses the SNI). There's no need for prefixes here because they don't make sense in this context, this isn't an HTTP proxy.

> No matter how I configured proxy_address, the client I got from gateway.get_client() seem to be unaware of the /services/dask-gateway/clusters prefix it would need (right?) while interacting with its specific cluster.

This is a known issue (although I can't find a reference issue, will open). The dashboard URL displayed by distributed's clients doesn't take the cluster object into account in the way we'd like. The dashboard URL on the `GatewayCluster` object does though, and does take `proxy_address` into account.

---

From the above, it looks like you were successfully able to create a client. I'm a bit confused by the above, can you briefly state what issues you're having that haven't been resolved?

**Comment by consideRatio** [comment]
@jcrist thanks for your work and thorough responses Jim! Here are some digging of mine.

### public_address in das
`proxy_address` works as intended and I get a good link from the GatewayCluster widget representation. This address does not propagate all the way to dask.distributed's Client widget representation though.

This is now represented by #247.

### Explicit `proxy_address` `:80`
No matter if I explicitly include http and `:80` in the `address` configuration of the Gateway constructor, I end up with the same issue on cluster.get_client(), which is that it attempts and fails to connect to `gateway://....` without `:80`.

Only by explicitly specifying `proxy_address="gateway://traefik-dask-gateway.dask-gateway:80"` this issue is resolved.

I created #251 to represent this.

### Failure for Scheduler/Client to align with DaskCluster/Controller

I experienced a timeout from my client when trying to use the dask cluster with 0 workers active even though I had 0-5 adapt configured. A new pod was created, but it was not starting fast enough (~10 sec?) so I got a Timeout.

This led me to conclude something was wrong still. This wasn't an optimal UX.

### GatewayCluster widget inconsitent with actual pods
After my images had been pulled and pods could start quickly, I reset my state by deleting clusters etc. Then:
1. I created a new cluster and choose to adapt 0-5 workers in it.
1. I ran a job with a client to the cluster that finished in 20 seconds and I had 5 workers according to the client for a while, and then 0 again.
1. I observed that I still had 5 pods, and my DaskCluster had 5 replicas.
   - The controller is in my mind thereby doing its job, it ensures 5 replicas of the workers.
   - There is something wrong though, because the scheduler knew to delete a worker, but that didn't lead to a change in the DaskCluster resource, so the controller didn't remove any pods.
1. I decided to try run my job again, would it add five new pods? It turns out no, it would instead error with a Timeout like if my workers failed to get started fast enough.
1. I tried adapting to 6/6, that added one worker, and the client could observe 1 worker while there was 6 replicas according to the DaskCluster resource and I saw 6 pods.
1. I ran my workload, and ended up doing work using a single worker.
1. I tried adapting to 0-3 workers, but kept seeing 6 pods, and this were the logs of the controller, while the DaskCluster resource were updated to 1 replica.
   ```
   [D 2020-04-14 17:33:11.857 KubeController] Event - MODIFIED cluster dask-gateway.c047a173d45247dd81f232ab60d692ca
   [I 2020-04-14 17:33:11.857 KubeController] Reconciling cluster dask-gateway.c047a173d45247dd81f232ab60d692ca
   [I 2020-04-14 17:33:11.862 KubeController] Finished reconciling cluster dask-gateway.c047a173d45247dd81f232ab60d692ca
   ```
1. I tried running my workload, and it seems that my client never registered more than one replica at best.

This may be two separate issues. Hmm... or not?

1. The controller fail to align correctly with the DaskCluster resource and never successfully delete surplus pods what the DaskCluster resource indicate it doesn't need.
2. Workers that the scheduler has used once isn't reused later if adapted away, except perhaps one single worker.

### Cluster adapt 0-5 can trigger as if it were 1-5

If I have a fresh cluster and press adapt 0-5, it doesn't create a worker for me, but I have ended up in a state where just going from 0-0 to 0-5 would add back a replica in the DaskCluster resource. I think the scheduled ended up thinking it kept needing one. This is a state I failed to reproduce quickly with a new cluster.

**Comment by consideRatio** [comment]
I let this become an issue with too much diverging discussion.

I'll close this an open a new, where I copy the relevant open discussion topics with regards on how to improve something further.
