### ISSUE TITLE
Support resource limits for an individual cluster

### ISSUE THREAD

**Issue by jcrist** [dask/dask-gateway#249]
Previously we supported configuring limits *per user*. These included:
- Max clusters per user
- Max cores per user
- Max memory per user

These were dropped in the refactor, as most backends have a native way of managing resource (cpu/memory) limits. 

- Kubernetes has [ResourceQuota](https://kubernetes.io/docs/concepts/policy/resource-quotas/)
- YARN, PBS, SLURM, etc... have queues

Supporting them in the gateway also complicated the implementation - most decisions are made at the *cluster level*, but limits on cores/memory were handled at the *user level*.

However, using the backend's native method does impose some restrictions on gateway configuration that may not be desirable for certain admins/users. For example, in Kubernetes, `ResourceQuota` objects are associated with a namespace. If you want to have limits per user, each user would need their own namespace.

I don't think going back to the old model is tenable, as I'd prefer to keep all cluster decisions local to information about a single cluster (rather than global information about multiple clusters). But, we can support some simpler limits natively fairly easily. These would include:

- Max workers per cluster
- Max cores per cluster
- Max memory per cluster

These limits would exist on the `ClusterConfig` object, and could thus be influenced by [user-specific cluster options](https://gateway.dask.org/cluster-options.html). So you could change limits on cluster size per user (or per group, etc...).

**Comment by jcrist** [comment]
cc @jhamman, @TomAugspurger

**Comment by jcrist** [comment]
One question I have is what we should do for scale attempts above this limit. For adapt, we can limit the bounds based on the limits, so no errors would bubble up to the user. But say a user has a cluster limited to 10 workers - if they run

```python
cluster.scale(15)
```

should this:
- Error informatively
- Request 10 workers and warn the user about the limit
- Quietly request 10 workers

Same for

```python
cluster.adapt(minimum=15)
```

**Comment by gforsyth** [comment]
> * Error informatively

This would be ok, although I think my preference is for option 2.

> * Quietly request 10 workers

I think this will cause lots of users to report that something is broken to their cluster admins.

**Comment by TomAugspurger** [comment]
Thanks.

Just for context, creating a namespace per user may not be ideal for something like pangeo's binder, where Jupyterhub users are created automatically. I don't have a good sense for how cheap it is to create and destroy users.

Max workers / cores per cluster would solve most of our needs I think. I'm not especially concerned about a single user making many clustesr.

**Comment by scottyhq** [comment]
This would be a really helpful addition @jcrist. In particular Max cores per cluster and
Max memory per cluster. For the case of scaling above limits, raising a warning to a user and requesting the limit seems ideal.

**Comment by jcrist** [comment]
I've started work on this in #266.
