### ISSUE TITLE
Timeout error due to slow scaleup from zero workers -> Not great UX

### ISSUE THREAD

**Issue by consideRatio** [dask/dask-gateway#253]
I experienced a timeout from my dask.distributed.Client when trying to use the dask cluster with 0 workers active even though I had 0-5 adapt configured. A new pod was created, but it was not starting fast enough (~10 sec?) so I got a Timeout.

This can be reproduced by for example adding an init container that sleeps for 10 seconds to the worker pod, or create it on a new node so it get stuck pulling an image. I found it to be a bit problematic error as compared to having the client say it gave up waiting for the scheduler to provide an initial worker or similar.

I wasn't sure if this was an issue for dask/distributed or dask/gateway. But I'm now starting to think it is dask/distributed. Is this correct? I failed to spot an open issue there about this, but it was quite hard since there were 400 open issues. If I could get verification it is a dask/distributed issue rather than dask/gateway I'll look more in that repo instead.

**Comment by jcrist** [comment]
I've never seen a timeout error from a cluster while waiting for a scale up to succeed. The scheduler should hang out waiting for workers forever. If you're seeing different behavior, could you post some code demonstrating the error and where it occurs? This shouldn't have anything to do with dask-gateway itself, if there is a problem here it would be in `distributed`.

**Comment by jcrist** [comment]
Closing, as this is an error with `distributed` rather than dask gateway. I haven't been able to reproduce this issue, if you have a reproducible example please file an issue there.
