### ISSUE TITLE
Failure in Running Demo Locally

### ISSUE THREAD

**Issue by mahorad** [dask/dask-gateway#267]
Tried running the demo locally according to the given instructions but noticed the container stops after a few seconds.
So, the following is the last part of the logs of the running container while running the demo's `start-demo.sh`.

`Using /opt/miniconda/lib/python3.7/site-packages
Finished processing dependencies for dask-gateway==0.7.1
+ popd
/working /
+ pushd dask-gateway-server
/working/dask-gateway-server /working /
+ python setup.py build_go develop
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'build_go'`

**Comment by jcrist** [comment]
Apologies for the late reply here. That demo was old and unmaintained, and has been removed in #301.

If you're looking to try things out, I recommend [running locally](https://gateway.dask.org/install-local.html). Closing.
