### ISSUE TITLE
Unable to download dask-gateway

### ISSUE THREAD

**Issue by kyprifog** [dask/dask-gateway#269]
Following the instructions here:

https://gateway.dask.org/install-kube.html

yielded the following:

```
helm upgrade --install \
>     --namespace $NAMESPACE \
>     --version $VERSION \
>     --values path/to/your/config.yaml \
>     $RELEASE \
>     daskgateway/dask-gateway
Error: failed to download "daskgateway/dask-gateway" (hint: running `helm repo update` may help)
```

Regardless of the repo being updated.   Looking on helm, it does not appear there is a dask-gateway helm chart listed there.

**Comment by jcrist** [comment]
Hm, looks like we have a typo in our docs.

```
helm repo add dask-gateway https://dask.org/dask-gateway-helm-repo/`
```

should be

```
helm repo add daskgateway https://dask.org/dask-gateway-helm-repo/
```

Would you care to submit a PR fixing this?
