### ISSUE TITLE
Some config not passed to workers

### ISSUE THREAD

**Issue by chrisroat** [dask/dask-gateway#270]
I have a k8s cluster with jhub and dask-gateway.  I am trying various ways to pass configs of tolerations and user-selected cluster options.  I'm not having luck with the tolerations, and have partial success with cluster options.

First, I've tried tolerations via `worker.extraPodConfig.tolerations` in my values yaml, which is reproduced below.  In the GCP console, I do not see my tolerations in the pod's yaml, nor do the pods schedule. 

Second, on the user options with c.Backend.cluster_options, the cores & memory seem to take, but my worker_extra_pod_config for gpu requests does not.  (Is it possible to pass in a custom "--resources" command line flag via this method?)

As an addendum to the second piece: is it possible to have worker_cores passed to the limits/requests (as it is now), but NOT to the --nthreads command line?   The reason would be for "dask hostile" processes that run multi-threaded under the hood (via shell command).

```
gateway:
  # These addresses need to be set for correct jhub<-->dask-gateway communication. See:
  # https://github.com/pangeo-data/pangeo-cloud-federation/issues/584#issuecomment-621471832
  address: http://traefik-dask-gateway.starmap/services/dask-gateway
  public-address: https://jupyter.example.com/services/dask-gateway

  backend:
    image:
      name: <img>
      tag: v0.0.3
      pullPolicy: Always

  worker:
    extraPodConfig:
      tolerations:
        - key: "k8s.dask.org/dedicated"
          value: "worker"
          effect: "NoSchedule"
        - key: "nvidia.com/gpu"
          value: "present"
          effect: "NoSchedule"

  extraConfig: |
    from dask_gateway_server.options import Options, Integer, Float

    def options_handler(options):
        return {
            "worker_cores": options.worker_cores,
            "worker_memory": int(options.worker_memory * 2 ** 30),
            "worker_extra_pod_config": {
                "resources": {
                    "limits": {
                        "nvidia.com/gpu": options.num_gpus,
                    },
                    "requests": {
                        "nvidia.com/gpu": options.num_gpus,
                    },
                },
            },
        }

    c.Backend.cluster_options = Options(
        Integer("worker_cores", default=2, min=1, max=7, label="Worker Cores (0-7)"),
        Integer("worker_memory", default=4, min=1, max=7, label="Worker Memory (0-7 GiB)"),
        Integer("num_gpus", default=0, min=0, max=1, label="Worker GPUs (0-1)"),
        handler=options_handler,
    )
```

**Comment by chrisroat** [comment]
This came down to a combination of indentation and incorrect values.

The worker toleration issue was solved by indenting the `worker:` stanza in, so that it falls inside `backend:`.

The resources issue was solved by using `worker_extra_container_config` instead of `worker_extra_pod_config`.

**Comment by AndreaGiardini** [comment]
Hi @chdoig 

```
As an addendum to the second piece: is it possible to have worker_cores passed to the limits/requests (as it is now), but NOT to the --nthreads command line? The reason would be for "dask hostile" processes that run multi-threaded under the hood (via shell command).
```
Did you find a solution for this?

The nthreads seems to be hardcoded here: https://github.com/dask/dask-gateway/blob/f72400bb2f0198c7a762cd33abc597ab07d899c8/dask-gateway-server/dask_gateway_server/backends/db_base.py#L1445-L1462

**Comment by bug-developer021** [comment]
hi @chrisroat!  Can u give the full config of dask gateway?  I'm also have a k8s cluster with jhub and  dask gateway, and I don't know how to integrate GPU support with dask gateway. The backend image you used is rapidsai?
