### ISSUE TITLE
Guidance on building Gateway-compatible Docker images

### ISSUE THREAD

**Issue by darothen** [dask/dask-gateway#273]
Hey there - I've been able to build out and configure some infrastructure with Dask-Gateway to support some workflow / data processing automation. In order to take things a step further, I followed the documentation to provide overridable `cluster_options` to my Gateway server - specifically, I want to be able to specify different images for users to provide for their particular workflow. The configuration all works beautifully, here's a minimum example pulling from the docs and Pangeo Cloud Federation code:

``` 
  gateway: 
    extraConfig: |
      from dask_gateway_server.options import Options, String

      def option_handler(options):
          if ":" not in options.image:
              raise ValueError("When specifying an image you must also provide a tag")
          return {
              "image": options.image,
          }

      c.KubeBackend.cluster_options = Options(
          String("image", default="daskgateway/dask-gateway:0.7.1", label="Image"),
          handler=option_handler
      )
```

I can easily then spin-up a cluster, say using the `pangeo/base-notebook` image:

``` python
cluster = GatewayCluster("http://my/cluster/address", image="pangeo/base-notebook:latest")
```

All works beautifully, except I can't find any guidance on what constitutes a "usable" image from this sort of workflow. I've tried to reverse-engineer things buy looking at the daskgateway/dask-gateway:0.7.1 image and the pangeo/base-notebook:latest image in the example, but it's eluding me. 

Can anyone who has successfully built out a custom image that played nicely with dask-gateway share an example, or possible contribute some documentation? Happy to collaborate and write some of the docs with you if you can point me to some resources that I could learn from.

**Comment by darothen** [comment]
Oh - I don't believe that the `latest` tag for daskgateway/dask-gateway build. Whenever I spin up a cluster using it, my Pods immediately die. Unsure what the issue is... the 0.7.1 tag works fine.

**Comment by TomAugspurger** [comment]
@darothen did you see https://medium.com/pangeo/managing-environments-5604d848367a? That gives some guidance & background on how we're doing things for pangeo's binder.

>  I can't find any guidance on what constitutes a "usable" image from this sort of workflow.

Can you clarify your question a bit? Is it something like "what version of dask-gateway is required?"

> Can anyone who has successfully built out a custom image that played nicely with dask-gateway share an example, or possible contribute some documentation?

All the images at https://github.com/pangeo-data/pangeo-docker-images work with pangeo-binder & the pangeo jupyterhubs. The setup there is perhaps a bit complex for your needs, but the key thing is that we include the `pangeo-notebook` conda metapackage in the environment, which ensures a compatible version of dask-gateway.

**Comment by darothen** [comment]
Hey @TomAugspurger sorry for the vague question. I think my question is really two parts:

1. Is there a specific set of packages or libraries that should be pre-installed in an image that will be used as a worker in a dask-gateway context? e.g. obviously it needs dask-gateway and dask, but anything else? If a user didn't want to use the pangeo-notebook conda metapackage, is there, say, a requirements.txt that could be pip-installed to ensure it would work? Or is there other software that should be installed and available in the Docker image to be used as a worker?

2. Should a Docker image that will be used here have any specific entrypoint or cmd arguments? 

Sorry if these are very basic questions... I've been a consumer of these products and package for a long time and am shifting into hacker/developer. The good news is like 90% of things just "work" as I hack them without any crazy intervention, digging through code/docs, etc - the foundation is super strong, which is exactly why I'm doing some customization for my person use.

**Comment by gforsyth** [comment]
> 1. Is there a specific set of packages or libraries that should be pre-installed in an image that will be used as a worker in a dask-gateway context? e.g. obviously it needs dask-gateway and dask, but anything else? If a user didn't want to use the pangeo-notebook conda metapackage, is there, say, a requirements.txt that could be pip-installed to ensure it would work? Or is there other software that should be installed and available in the Docker image to be used as a worker?

Definitely need `dask-gateway`, `dask`, `distributed` and their dependencies.  The other thing to pay attention to is to keep the versions of those libraries consistent between the workers and the (for example) notebook environment you are using to connect.

**Comment by droctothorpe** [comment]
[Here](https://github.com/dask/dask-gateway/blob/master/dask-gateway/Dockerfile) is the Dockerfile used for the worker pods. 

You can encourage users to use this Dockerfile as a base, customize it (by adding packages for example), and pass the new image in through the options object. 

Does that answer your question? 

Note, this Dockerfile is also used for the scheduler and inherits from the [base image](https://github.com/dask/dask-gateway/blob/master/dask-gateway/Dockerfile).

**Comment by darothen** [comment]
@droctothorpe yes - that is perfect. Thanks!

**Comment by erl987** [comment]
I want to reopen this ticket because I run into similar issues. Generally, it is possible to use the Docker image `daskgateway/dask-gateway` as a base for the worker/scheduler image. However, this is a very strong limitation in my opinion:

* in our case we cannot base our Docker images on a third-party software that is only used in a part of the use-cases (the application in question cannot be fully installed by `pip` but needs some other steps as well)
* the image of `dask-gateway` installs its own miniconda and is based on CentOS, this causes trouble when migrating from a regular miniconda base-image which seems to be slightly different

I would have expected that it is sufficient to add some packages to the image to get it working with dask-gateway as a worker.

I tried to simply install `dask-gateway`, `dask` and `distributed` into our regular image with `pip`, but I do only get `dask_gateway.client.GatewayClusterError: Cluster 'default.6f22d403a02d4832add03ddef7a0c902' failed to start, see logs for more information`. The versions of the three packages are identical on client and image.

So there seems to be something else required that I miss?

**Comment by droctothorpe** [comment]
@erl987 we built all of our images from scratch (in order to adhere to questionable enterprise requirements).

If you're going to build your own image from scratch, you're going to want to port over the steps in both the [base image](https://github.com/dask/dask-gateway/blob/95dadf039a5ed91d90ec0dce158e3df35c6e05c1/resources/helm/images/dask-gateway-base/Dockerfile) and [the images that inherit from it](https://github.com/dask/dask-gateway/tree/95dadf039a5ed91d90ec0dce158e3df35c6e05c1/resources/helm/images).

**Comment by erl987** [comment]
Thanks, I'll try to combine our and your base image.

**Comment by erl987** [comment]
Hi,

I am now trying for quite a while to get a simple custom worker image running on a Kubernetes cluster. It works as long as I use the default image for the scheduler/worker.

But even if I simply copy the image for ` dask/dask-gateway` from Github to build and deploy it (with the link posted by you above), the creation of a new cluster with this code fails:

```
from dask_gateway import Gateway
gateway = Gateway("http://ip")
cluster = gateway.new_cluster()
```

This is the error:
```
dask_gateway.client.GatewayClusterError: Cluster 'default.0d3301b33cdf450c974003bbc6424037' failed to start, see logs for more information
```

It is unfortunately rather hard to get this log from the failed pod.

I am quite confused about the `Dockerfile` for `dask-gateway`. On Github this file is actually missing in the *latest* branch. It seems to have disappeared after version 0.6.1 - this is the last tag that has it.

I assume that the Dockerfile has changed in the meanwhile and by using the latest (i.e. quite old one) I get from Github, I get a mismatch.

Further, on `hub.docker.com`, the *latest* image of `dask-gateway-base` is 10 months old, while the version 0.7.1 available there is only 2 months old. Is there the *latest* image missing? (https://hub.docker.com/r/daskgateway/dask-gateway-base/tags)


I would appreciate any hints.

/Ralf
