### ISSUE TITLE
Error installing dask-gateway helm chart

### ISSUE THREAD

**Issue by vinhdiesal** [dask/dask-gateway#275]
I'm having issues installing `dask-gateway` helm chart. 
I followed the revised version of the helm installation procedure: 
`helm repo add daskgateway https://dask.org/dask-gateway-helm-repo/`
`helm repo update`
```
helm upgrade --install \
>     --namespace $NAMESPACE \
>     --version $VERSION \
>     --values path/to/your/config.yaml \
>     $RELEASE \
>     daskgateway/dask-gateway
```
At first I got the following error: `Error: open path/to/your/config.yaml: no such file or directory`
so I deleted this portion and now I have the following error: 
```
Error: validation failed: [unable to recognize "": no matches for kind "IngressRoute" in version "traefik.containo.us/v1alpha1", unable to recognize "": no matches for kind "Middleware" in version "traefik.containo.us/v1alpha1"]
```
Please help with this issue. 
Thanks,

**Comment by jcrist** [comment]
> At first I got the following error: Error: open path/to/your/config.yaml: no such file or directory
so I deleted this portion

`path/to/your/config.yaml` is a stand-in for your custom values file. Usually users want to override some of the default settings.

> `Error: validation failed: [unable to recognize "": no matches for kind "IngressRoute" in version "traefik.containo.us/v1alpha1", unable to recognize "": no matches for kind "Middleware" in version "traefik.containo.us/v1alpha1"]`

Are you using helm 2? This error indicates the CRD objects weren't installed properly. If you're using helm 2 you may need to manually create the objects in this directory: https://github.com/dask/dask-gateway/tree/master/resources/helm/dask-gateway/crds.

Something like `kubectl create -f dask-gateway/crds/*.yaml` should work.

**Comment by vinhdiesal** [comment]
Thanks installation was successful after I performed `kubectl create -f dask-gateway/crds/*.yaml`

One quick question before I close, I have multiple machines connected on the kubernetes cluster, but somehow on the `kubernetes cluster` I see the dask-gateway pods are installed only on one node which is the master, when I create the cluster will it utilize all the machines? I'm trying to perform parallel computing on different nodes.

**Comment by jcrist** [comment]
That's configuration specific, but in the absence of any restrictions like taints/tolerations things should balance out. This has nothing to do with dask-gateway specifically, and is related to the k8s scheduler. See https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/ for more information.
