### ISSUE TITLE
Problems with getting API-dask-Gateway Pod to start

### ISSUE THREAD

**Issue by vinhdiesal** [dask/dask-gateway#276]
I'm trying to create a `dask cluster` on existing `Kubernetes` using `dask gateway`
I used the default `values.yaml` as a baseline and added the following code to `extraConfig:`
```
extraConfig: |
from dask_gateway_server.options import Options, Integer, Float, String

       def option_handler(options):
           return {
              "worker_cores": options.worker_cores,
              "worker_memory": "%fG" % options.worker_memory,
              "image": options.image,
       }

        c.Backend.cluster_options = Options(
            Integer("worker_cores", 2, min=1, max=4, label="Worker Cores"),
            Float("worker_memory", 4, min=1, max=8, label="Worker Memory (GiB)"),
            String("image", default="daskgateway/dask-gateway:latest", label="Image"),
            handler=option_handler,
       )
```
I performed helm installation based on this updated `values.yaml` file and everything runs except the API-Dask-Gateway pod. Without this `extraConfig` it runs fine, but I don't get options for clusters. Please help.
Thanks, 
Vinh

**Comment by jcrist** [comment]
In what way does it fail? Do you see an error from helm? In the pod logs? If so, what is that error?

**Comment by vinhdiesal** [comment]
I attached the following screenshot of the Kubernetes Dashboard. The API-Dask-Gateway is not running when I applyu the `extra config`.
![Screenshot from 2020-06-18 17-56-41](https://user-images.githubusercontent.com/47830328/85085578-25befc80-b18d-11ea-9d63-55d8000081d1.png)
Because of this, when in my `jupyter notebook` when I try to connect to the `Gateway` as follows:
I get stuck when trying to list the options: 
![Screenshot from 2020-06-18 18-01-47](https://user-images.githubusercontent.com/47830328/85085823-d3321000-b18d-11ea-81fc-3ec5bc3e598d.png)
How can I fix the problems so I can start using my cluster?

**Comment by droctothorpe** [comment]
If the API pod is not running, requests from the client will fail. 

Look into why the API pod is failing. Until that pod is up, bringing Jupyter into the equation only complicates things / obfuscates the underlying problem. 

```bash
kubectl describe pod api-dask-gateway-<random>
kubectl logs api-dask-gateway-<random>
```

**Comment by vinhdiesal** [comment]
When I performed a `microk8s kubectl logs/describe api-daskgateway` I get the following message: 
```Error from server (NotFound): pods "api-dask-gateway" not found```
When I click right click on logs on the `API-dask-gateway` I get the following error:
`https://192.168.1.108:10250/containerLogs/dask-gateway/api-dask-gateway-6b77676999-n8lgl/gateway?tailLines=5000×tamps=true: dial tcp 192.168.1.108:10250: connect: connection refused`

I need some help to find out why the API pod is failing. 
It appears to fail when I try to create a cluster using the `extraconfig` in the `values.yaml`. If I use the default `value.yaml` without the `extraconfig`. 
This is the `extra config` code block: 
```
extraConfig: |
from dask_gateway_server.options import Options, Integer, Float, String

       def option_handler(options):
           return {
              "worker_cores": options.worker_cores,
              "worker_memory": "%fG" % options.worker_memory,
              "image": options.image,
       }

        c.Backend.cluster_options = Options(
            Integer("worker_cores", 2, min=1, max=4, label="Worker Cores"),
            Float("worker_memory", 4, min=1, max=8, label="Worker Memory (GiB)"),
            String("image", default="daskgateway/dask-gateway:latest", label="Image"),
            handler=option_handler,
       )
```

**Comment by vinhdiesal** [comment]
I also tried to create a cluster in jupyter notebook per the tutorial as follows: 
`cluster = gateway.new_cluster(worker_cores=2, environment="tensorflow")`
`cluster = GatewayCluster(worker_cores=2, environment="tensorflow")`
But either way it seems to not understand `worker_cores and environment`.

**Comment by droctothorpe** [comment]
That's not the full pod name. 

`kubectl get pods` to see a list of pods. 

`kubectl describe <full pod name>` to get more specific info about the failure.

**Comment by droctothorpe** [comment]
In your screenshot from the gui, you can see a CrashLoopBackOff in the status. Fix that problem. Leave the client out. It will not work regardless of what options you pass through if the API pod is down.

**Comment by vinhdiesal** [comment]
I posted on this website, because I don't know how I would fix the problem. 
I typed in `microk8s kubectl get pods` i get: 
`No resources found in default namespace.`

Please provide some assistance.

**Comment by droctothorpe** [comment]
You're in the `default` namespace. You want to list pods in the namespace that Dask gateway is deployed in, which is the `dask-gateway` namespace. Include `-n dask-gateway` in your request. Also, lookup kubens.

**Comment by droctothorpe** [comment]
Also, if you're just experimenting on your local machine, I recommend using Docker Desktop Kubernetes over MicroK8s.

**Comment by vinhdiesal** [comment]
`kubectl describe api-dask-gateway` results in 
`error: the server doesn't have a resource type "api-dask-gateway-6b77676999-n8lgl"`

**Comment by droctothorpe** [comment]
You have to pass `-n dask-gateway` to the describe subcommand as well. And make sure to use the full pod name.

**Comment by vinhdiesal** [comment]
Docker Desktop doesn't work on Ubuntu machines and I have a couple machines in a cluster, `microk8s` seems so work pretty well.

**Comment by vinhdiesal** [comment]
```
kubectl describe api-dask-gateway-6b77676999-n8lgl -n dask-gateway
``` 
results in the same error: 
```
error: the server doesn't have a resource type "api-dask-gateway-6b77676999-n8lgl"
```

**Comment by droctothorpe** [comment]
kubectl describe pod

**Comment by vinhdiesal** [comment]
```
Name:         api-dask-gateway-6b77676999-n8lgl
Namespace:    dask-gateway
Priority:     0
Node:         192.168.1.108/192.168.1.108
Start Time:   Thu, 18 Jun 2020 17:53:54 -0700
Labels:       app.kubernetes.io/component=gateway
              app.kubernetes.io/instance=dask-gateway
              app.kubernetes.io/managed-by=Tiller
              app.kubernetes.io/name=dask-gateway
              app.kubernetes.io/version=0.7.1
              gateway.dask.org/instance=dask-gateway
              helm.sh/chart=dask-gateway-0.7.1
              pod-template-hash=6b77676999
Annotations:  checksum/configmap: 291cab9564d6abd24d6642dd604d666d55c4c9513281bd76b1e4b9d213120bcc
              checksum/secret: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b
Status:       Running
IP:           10.1.88.6
IPs:
  IP:           10.1.88.6
Controlled By:  ReplicaSet/api-dask-gateway-6b77676999
Containers:
  gateway:
    Container ID:  containerd://932b34d0957681bc7350eb89b9e41a873e24b80edeef1ff3089a91925b034ec2
    Image:         daskgateway/dask-gateway-server:0.7.1
    Image ID:      docker.io/daskgateway/dask-gateway-server@sha256:fc3258a5b81c9c3bbf3ce1acdd503e73f4f4304702627623ebb0d373ace6bd51
    Port:          8000/TCP
    Host Port:     0/TCP
    Command:
      dask-gateway-server
      --config
      /etc/dask-gateway/dask_gateway_config.py
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 18 Jun 2020 18:45:38 -0700
      Finished:     Thu, 18 Jun 2020 18:45:38 -0700
    Ready:          False
    Restart Count:  15
    Environment:    <none>
    Mounts:
      /etc/dask-gateway/ from configmap (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from api-dask-gateway-token-zvkj7 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  configmap:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      api-dask-gateway
    Optional:  false
  api-dask-gateway-token-zvkj7:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  api-dask-gateway-token-zvkj7
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                    From                    Message
  ----     ------     ----                   ----                    -------
  Normal   Scheduled  <unknown>              default-scheduler       Successfully assigned dask-gateway/api-dask-gateway-6b77676999-n8lgl to 192.168.1.108
  Normal   Pulled     52m (x5 over 53m)      kubelet, 192.168.1.108  Container image "daskgateway/dask-gateway-server:0.7.1" already present on machine
  Normal   Created    52m (x5 over 53m)      kubelet, 192.168.1.108  Created container gateway
  Normal   Started    52m (x5 over 53m)      kubelet, 192.168.1.108  Started container gateway
  Warning  BackOff    3m20s (x231 over 53m)  kubelet, 192.168.1.108  Back-off restarting failed container
```

**Comment by droctothorpe** [comment]
Great. You can see in the event log that it pulled the image successfully but that the container failed to start properly. 

Now post the output of `kubectl -n dask-gateway logs api-dask-gateway-6b77676999-n8lgl`.

**Comment by vinhdiesal** [comment]
```
Error from server: Get https://192.168.1.108:10250/containerLogs/dask-gateway/api-dask-gateway-6b77676999-n8lgl/gateway: dial tcp 192.168.1.108:10250: connect: connection refused
```

**Comment by vinhdiesal** [comment]
this is the part I don't get, the other pods on 192.168.1.108 are working fine, so i don't understand the connection issues, there's no firewall.

**Comment by droctothorpe** [comment]
Everything works without a hitch when you remove the cluster options from `values.yaml`?

**Comment by vinhdiesal** [comment]
yes

**Comment by droctothorpe** [comment]
Are you able to pull logs from the other pods?

**Comment by droctothorpe** [comment]
Hard to troubleshoot without access to the logs. I recommend looking into that specific error message to identify why the handshake is failing. [Here's](https://stackoverflow.com/questions/49707999/kubernetes-unable-to-retrieve-logs) a starting point.

**Comment by vinhdiesal** [comment]
Here's the latest log reports of the `microk8s` if it helps.
[inspection-report-20200618_190130.tar.gz](https://github.com/dask/dask-gateway/files/4802060/inspection-report-20200618_190130.tar.gz)

**Comment by jcrist** [comment]
Apologies, I don't have time tonight to continue responding after this (I'll get back to y'all in the morning if the problem persists). The issue here is likely the python code added in `extraConfig` being malformatted, leading the config loading to fail, so the pod cycles.

From the way you've pasted it above, it looks like you probably have an uneven indent structure. Try to format your yaml exactly as shown here: https://gateway.dask.org/install-kube.html#using-extraconfig.

If you want, you can use `helm template` to render [this template](https://github.com/dask/dask-gateway/blob/master/resources/helm/dask-gateway/templates/gateway/configmap.yaml) locally to see if it looks like valid python code.

**Comment by droctothorpe** [comment]
Ha was about to follow up about that. Thanks, Jim.

Your code:
```python
extraConfig: |
from dask_gateway_server.options import Options, Integer, Float, String

       def option_handler(options):
           return {
              "worker_cores": options.worker_cores,
              "worker_memory": "%fG" % options.worker_memory,
              "image": options.image,
       }

        c.Backend.cluster_options = Options(
            Integer("worker_cores", 2, min=1, max=4, label="Worker Cores"),
            Float("worker_memory", 4, min=1, max=8, label="Worker Memory (GiB)"),
            String("image", default="daskgateway/dask-gateway:latest", label="Image"),
            handler=option_handler,
       )
```

Example code:
```
extraConfig: |
from dask_gateway_server.options import Options, Integer, Float, String

def option_handler(options):
    return {
        "worker_cores": options.worker_cores,
        "worker_memory": "%fG" % options.worker_memory,
        "image": options.image,
    }

c.Backend.cluster_options = Options(
    Integer("worker_cores", 2, min=1, max=4, label="Worker Cores"),
    Float("worker_memory", 4, min=1, max=8, label="Worker Memory (GiB)"),
    String("image", default="daskgateway/dask-gateway:latest", label="Image"),
    handler=option_handler,
)
```

This will probably fix it -- but you should probably look into why you can't access pod logs at some point either way.

**Comment by vinhdiesal** [comment]
wow you guys are amazing. Thanks you so much for helping me correct the problem with a quick turn around, I will remember to keep note of the white spaces.
