### ISSUE TITLE
dask cli scheduler idle timeout confusion

### ISSUE THREAD

**Issue by georgeBacon23** [dask/dask-gateway#279]
**What happened**:

idle-timeout passed to scheduler via dask-cli not respected.   

**What you expected to happen**:

From the name, I expected that if a scheduler is not given work for the idle-timeout period, then it would automatically shutdown. From the code, it's looks like after the scheduler has been given tasks, the timeout is ignored.

I may have misunderstood the meaning of the parameter, but if so a bit more explanation in the docs would be helpful. I also may have misunderstood the source.

**Minimal Complete Verifiable Example**:

The relevant source:

```python
async def check_idle(self):
        while True:
            await asyncio.sleep(self.idle_timeout / 4)
            if any(ws.processing for ws in self.scheduler.workers.values()):
                return
            if self.scheduler.unrunnable:
                return

            last_action = (
                self.scheduler.transition_log[-1][-1]
                if self.scheduler.transition_log
                else self.scheduler.time_started
            )

            if self.loop.time() - last_action > self.idle_timeout:
                logger.warning(
                    "Cluster has been idle for %.2f seconds, shutting down",
                    self.idle_timeout,
                )
                await self.gateway.shutdown()

```

**Anything else we need to know?**:

Again this may be the intended behavior, but if so the naming and documentation is a bit unclear to me.

**Comment by jcrist** [comment]
Apologies for the delayed response here, I've been on hiatus from dask work for the last month. This was indeed a bug, fixed in #287. Thanks for the excellent issue report!
