### ISSUE TITLE
Monitoring with Prometheus and Grafana

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask-gateway#280]
I'm looking into adding monitoring for pangeo, and would like to add a few metrics for Dask Gateway. I'm very new to prometheus and grafana, so apologies for any mistakes. Here are some rambling thoughts as I work through things. https://github.com/TomAugspurger/pangeo-cloud-federation/blob/metrics/gke/values.yaml has some helm configuration
for the pangeo deployment I'm testing on.

I notice a couple of questions immediately:

1. Dask exposes prometheus metrics at `scheduler-address/metrics`, but Dask Gateway's schedulers are
   ephemeral. How do we dynamically notify grafana / prometheus that it should add a datasource at an address?
   Should Dask-Gateway act as a broker here?
2. In my setup I'm using JupyterHub auth. Will all prometheus requests need to go through JupyterHub
   to access the dashboard?

I'll continue to post here as I work through things.

cc @droctothorpe (who mentioned prometheus in https://github.com/dask/dask-gateway/pull/258) and @consideRatio

**Comment by consideRatio** [comment]
1. Prometheus can watch the k8s services and inspect if they have annotations about scraping, if they do, prometheus will scrape metrics from the k8s service exposed pods. So, my main question is if the ephemeral schedulers get a k8s services created for them? If so, can they be annotated?

2. Grafana is what expose dashboards, and it in turn will probe prometheus for data to show in the dashboards. So, grafana user -> grafana web interface -> prometheus as one possible data source for created dashboards in grafana. So, grafana will need to manage a userbase of its own, but you can configure it to work against a OAuth2/OpenID Connect identity provider of your choice. The network connectivity to grafana could be done in various ways, one way is to create an ingress resource that together with the ingress controller provides an entrypoint. A setup I manage have it setup like that with nginx-ingress+cert-manager giving that entry HTTPS as well.

**Comment by TomAugspurger** [comment]
> So, my main question is if the ephemeral schedulers get a k8s services created for them? If so, can they be annotated?

They do indeed. So they would need something like

```yaml

**Comment by TomAugspurger** [comment]
Ah, that might run into https://github.com/dask/dask-gateway/issues/274 when using via helm. I'll try applying it manually first.

**Comment by TomAugspurger** [comment]
Hey, cool, that did it!

![Screen Shot 2020-06-24 at 10 29 35 AM](https://user-images.githubusercontent.com/1312546/85585443-a191cc80-b605-11ea-988c-b6e71a9b61a7.png)

Not the most impressive chart but it's something :)

For reference, I added the annotation manually with

```
kubectl -n metrics annotate service dask-gateway-9175cdffbe5c4c48bd469214522ca714 prometheus.io/scrape='true' prometheus.io/path='/metrics'
```

**Comment by TomAugspurger** [comment]
Seems like we can achieve the same thing by setting the annotations on the pod, rather than the service. This can be done through helm by setting


```yaml
dask-gateway:
  gateway:
    extraConfig:
      metrics: |
        c.KubeClusterConfig.scheduler_extra_pod_annotations = {"prometheus.io/scrape": "true"}
        c.KubeClusterConfig.worker_extra_pod_annotations = {"prometheus.io/scrape": "true"}

```

**Comment by TomAugspurger** [comment]
Another status update:

This was added to pangeo at https://github.com/pangeo-data/pangeo-cloud-federation/pull/626. Things mostly work, at least for the scheduler.

It seems like prometheus can't connect to the *worker*s though. If I make a request to `http://scheduler-address:8787/metrics` from within the kubernetes network, things are fine. But for workers

```
jovyan@hub-7d5f489b8b-zrmm9:/srv/jupyterhub$ curl http://10.36.7.17:8787/metrics  # that's the worker's IP
curl: (7) Failed to connect to 10.36.7.17 port 8787: Connection refused
```

not sure why that is yet.

**Comment by TomAugspurger** [comment]
Hmm I wonder if it's because we start the scheduler with a `--dashboard-address` at https://github.com/dask/dask-gateway/blob/5ae7c8a40f3e337c0581e7c005b04b83e67535a6/dask-gateway/dask_gateway/dask_cli.py#L509.

Workers are not started with `--dashboard-address`: https://github.com/dask/dask-gateway/blob/5ae7c8a40f3e337c0581e7c005b04b83e67535a6/dask-gateway/dask_gateway/dask_cli.py#L587-L595, which I think picks a random port for the dashboard.

**Comment by TomAugspurger** [comment]
And I think this compounds with https://github.com/dask/dask-gateway/blob/5ae7c8a40f3e337c0581e7c005b04b83e67535a6/dask-gateway-server/dask_gateway_server/backends/kubernetes/controller.py#L1142-L1147

where we declare that the dashboard is running on :8787. I'll try putting together a PR to pass these values through...

**Comment by TomAugspurger** [comment]
Actually does the kubernetes backend worker starting interact at all with `dask_gateway.dask_cli.start_worker`? It seems it might be independent.

**Comment by TomAugspurger** [comment]
For reference, this was implemented for pangeo in https://github.com/pangeo-data/pangeo-cloud-federation/pull/626/ and https://github.com/pangeo-data/pangeo-cloud-federation/pull/648. The key bit was setting the `prometheus.io/scrape: 'true'` annotation on all the pods.

**Comment by AndreaGiardini** [comment]
Hey @TomAugspurger 
Which dashboard to you use? This is the only one I found https://grafana.com/grafana/dashboards/11522
Is there any community-maintained one?

**Comment by TomAugspurger** [comment]
Just that one.

**Comment by AndreaGiardini** [comment]
How can i contribute to it?

Maybe it makes sense to have it in the dask-gateway repository so that we 
can make it easy to edit from contributors?

**Comment by TomAugspurger** [comment]
I don’t think that putting it in dask-gateway makes sense. Other deployments would benefit from it too.

If there’s interest we can create a separate repository in the Dask organization that contains the grafana Chart source.

**Comment by AndreaGiardini** [comment]
FYI I added multi cluster support here: https://grafana.com/grafana/dashboards/13378

Maybe adding it to https://github.com/dask/helm-chart could make sense?
