### ISSUE TITLE
Google Cloud IAP-compatible Auth for dask-gateway/pangeo deployment

### ISSUE THREAD

**Issue by darothen** [dask/dask-gateway#281]
Hey all, @saranicole and I are running a pangeo cluster on a domain protected by [Google Cloud IAP](https://cloud.google.com/iap). With a bit of finagling and improvements to the [pangeo-cloud-federation](https://github.com/pangeo-data/pangeo-cloud-federation) helm chart (which we plan on publishing in a blog post for the community very shortly), we were able to get everything working save for one final issue: we haven't found a way for users to access the gateway services API exposed via JupyterHub.

Working through the issue and manually re-constructing the requests generated by the dask-gateway client to interact with the dask-gateway-server, here's what we believe is happening:

1. To get through IAP, requests get seeded with a a special **Authorization** header; a good example of how this is constructed can be found [here](https://cloud.google.com/iap/docs/authentication-howto)
2. This header has a conflicting structure to the headers expected by the `GatewayAuth` sub-classes currently available in the library
3. Even when we use a `BasicAuth` based configuration, things don't work perfectly because the `BasicAuth` injects a new **Authorization** header into the request that conflicts with the IAP's expectations

We've manually worked through custom requests and have a catch-22: if we use the IAP authorization, we can't authenticate with the dask-gateway-server using any of the available `Authenticator`s, but we if use the correct built-in `Auth`, then we can't get past the IAP.

We were hoping for some advice on next steps to try. If there are simple hacks folks can think of then great! If we need to build a new type of `Authenticator` and corresponding `Auth` into the library, then that's fine too - we're open to contributing some sort of special Google OAuth-based `Authenticator.

**Comment by jcrist** [comment]
Hi @darothen. I'm not familiar with IAP, but from what I understand from the docs, its auth model only comes into affect for requests coming from outside the proxy - services inside the cluster should be free to use whatever auth headers they want.

If you want to use IAP *and* have the dask-gateway api be available from outside the cluster (so you could create and connect to a dask cluster from a client running outside the cluster) then we'd need to figure out an auth solution, but if your client is running inside the k8s cluster then no client->dask-gateway requests should have to go through the IAP proxy.

Here's a poor ascii diagram:

```
        IAP Boundary
           |
browser -> | -> jupyterhub proxy -> notebook session
           |          |              ^             ^
           |          |              |             |
           |          |              |             | Gateway client comms
           |          |              | dask        |
           |          | dashboard    | Client      |
           |          | from         | comms       v
           |          | browser      |           dask-gateway-api ---------> jupyterhub api
           |          |              |                server        auth
           |          |              |                 ^            requests
           |          |              v                 | 
           |          +---------> dask cluster <-------+ 
```

If you never need to create a dask cluster with the client running outside the k8s cluster, then the existing auth solutions should work (if my understanding of IAP is correct) - the trick is making sure all internal communications only go through internal routes.

**Comment by darothen** [comment]
Thanks for the feedback @jcrist! That's actually quite the nice ASCII diagram, it really helps clarify the communication paths here. We'll do a deeper dive on making sure all the internal communications are going through internal routes and report back what we find.

**Comment by darothen** [comment]
@jcrist I'm going to close for now; we were able to re-direct to the internal API address in the cluster and things seem to work fine.

In the future we may consider contributing that Google OAuth feature to the library as an enhancement.

**Comment by jcrist** [comment]
Glad you figured things out!
