### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by jcrist** [dask/dask-gateway#289]
I'm getting back into dask-gateway development, and would like to get a release out soon-ish (within the next week or so). My current todo list is:

- ~#217?~
- ~Maybe #274 & #189 ?~
- ~Whatever helm chart improvements the pangeo folks want to get in in the next week-ish~

Thoughts @TomAugspurger? Apologies for stepping out for a month btw, still figuring out the state of things now that I'm back.

**Comment by TomAugspurger** [comment]
#217 may be blocked by https://github.com/dask/distributed/pull/3239. I wasn't able to get CI passing there.

I don't think either of #274 and #189 are super high-priority for pangeo.

**Comment by jcrist** [comment]
> #217 may be blocked by dask/distributed#3239. I wasn't able to get CI passing there.

Hmmm, that's unfortunate. It's not detrimental if the client isn't closed cleanly on cluster shutdown, but it isn't great either. I might put that off for now then. Is there anything else that would be good to get in this release for the pangeo deployment?

**Comment by TomAugspurger** [comment]
Nope, the mapping field and the user limits were the last things on our wishlist I think :)

**Comment by jcrist** [comment]
0.8.0 has now been released, closing.
