### ISSUE TITLE
Dask gateway 0.7.1 : no matches for kind "IngressRoute" in version "traefik.containo.us/v1alpha1",

### ISSUE THREAD

**Issue by ctr26** [dask/dask-gateway#297]
Hi all,

I can't use helm3 yet on my cluster, so I've tried installing the last helm2 distribution of dask gateway. When I try version 0.7.1 I get an error from traefik.

Any advice welcome

Craig

```
RELEASE=dask-gateway
NAMESPACE=dask-gateway
VERSION=0.7.1
```

```
helm upgrade --install \
    --namespace $NAMESPACE \
    --version $VERSION \
    $RELEASE \
    daskgateway/dask-gateway`
```

`Error: validation failed: [unable to recognize "": no matches for kind "IngressRoute" in version "traefik.containo.us/v1alpha1", unable to recognize "": no matches for kind "Middleware" in version "traefik.containo.us/v1alpha1"]`

**Comment by droctothorpe** [comment]
That error message indicates that you need to install the Custom Resource Definitions that Traefik relies on. They're located [here](https://github.com/dask/dask-gateway/blob/bfb771cec733571bf9090349316cfce6ca9d1b1d/resources/helm/dask-gateway/crds/traefik.yaml). 

I'm not sure why the chart isn't handling that for you. As a troubleshooting step, you can try running `kubectl apply -f /resources/helm/dask-gateway/crds/traefik.yaml` before installing the Helm chart.

**Comment by jcrist** [comment]
Helm 2 won't automatically install crds for you (we rely on the [helm 3 mechanism for this](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#install-a-crd-declaration-before-using-the-resource)). To handle this via helm 2 you'll need to manually install the CRDs as @droctothorpe described above.

> I can't use helm3 yet on my cluster

Would mind briefly explaining why? We decided to drop helm 2 support in the latest release (0.8.0) for exactly this reason, with the hope that most users would have already transitioned to helm 3. Apologies if this wasn't a good assumption.

**Comment by ctr26** [comment]
> Helm 2 won't automatically install crds for you (we rely on the [helm 3 mechanism for this](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#install-a-crd-declaration-before-using-the-resource)). To handle this via helm 2 you'll need to manually install the CRDs as @droctothorpe described above.
> 
> > I can't use helm3 yet on my cluster
> 
> Would mind briefly explaining why? We decided to drop helm 2 support in the latest release (0.8.0) for exactly this reason, with the hope that most users would have already transitioned to helm 3. Apologies if this wasn't a good assumption.

I've set up the rest of my cluster to use helmfile and gitlab ci to deploy. Swapping in helm 3 causes an error and it's inability to create namespaces is a condition I need to code for. Ok

**Comment by ctr26** [comment]
https://github.com/helm/helm/pull/7648

Looks like create namespace is back in for helm 3

**Comment by jcrist** [comment]
Ah, good to know, I didn't know helm 3 previously had that restriction.

Since the dask-gateway helm chart is helm 3 only, is there anything left for us to do here?
