### ISSUE TITLE
Update options handler signature to include `user` as argument

### ISSUE THREAD

**Issue by droctothorpe** [dask/dask-gateway#306]
I want to add conditional BYOC (bring your own container) support for "power" users. 

My code looks something like this:
```python
def options_handler(options):
    if user in byoc_group: # <----
        return {
            "worker_cores": options.worker_cores,
            "worker_memory": int(options.worker_memory * 2 ** 30),
            "worker_extra_pod_annotations": {"iam.amazonaws.com/role": options.role},
            "worker_extra_pod_labels": {"gateway.dask.org/user": options.user},
            "scheduler_extra_pod_labels": {"gateway.dask.org/user": options.user},
            "image": options.image,
        }
    else:
        return {
            "worker_cores": options.worker_cores,
            "worker_memory": int(options.worker_memory * 2 ** 30),
            "worker_extra_pod_annotations": {"iam.amazonaws.com/role": options.role},
            "worker_extra_pod_labels": {"gateway.dask.org/user": options.user},
            "scheduler_extra_pod_labels": {"gateway.dask.org/user": options.user},
        }
```

The thing that I'm trying to figure out is how to pass the `user` into the `options_handler` function. It can't be a parameter, otherwise someone who doesn't have BYOC privileges can plug in the username of someone who does (assuming they knew it).

Any suggestions would be greatly appreciated. Thank you!

**Comment by jcrist** [comment]
I can't find the issue, but somewhere previously I commented that we might change the options handler interface to take in the `user` as a parameter to handle this use case. Right now you can kind of do this by returning a different `Options` object per user that stashes the user in a closure, but that's not nice to write or intuitive.

```python
def cluster_options(user):
    def options_handler(options):
        # user is available in the closure
        ...
    return Options(..., handler=options_handler)
```

We'd want to do this in a way that the old signature would raise a deprecation warning and still work for a bit.

**Comment by droctothorpe** [comment]
Awesome. Thank you, Jim!

**Comment by jcrist** [comment]
I'd like to keep this open, as updating the signature here is something I'd like to actually do.

**Comment by droctothorpe** [comment]
I could take a stab at this if it helps. No pressure.
