### ISSUE TITLE
Dask Schedulers Not Cleaned Up

### ISSUE THREAD

**Issue by jrdzha** [dask/dask-gateway#314]
While dealing with [this problem](https://stackoverflow.com/questions/63984003/dask-client-fails-to-connect-to-cluster-when-running-inside-a-docker-container), I found that if a cluster is not able to fully connect, while a scheduler is created, it is not cleaned up when this failure happens.

While testing for my original problem, this has left a number of dask schedulers just floating in my cluster.

**Comment by jcrist** [comment]
Thanks for the issue report. Previously errors when shutting down clients would prevent the cluster from being properly cleaned up. Should be fixed by #332.
