### ISSUE TITLE
Unable to connect to Dask-Gateway from a Docker Container

### ISSUE THREAD

**Issue by jrdzha** [dask/dask-gateway#316]
I am running Dask Gateway in a Kubernetes namespace. I am able to connect to the Gateway using the following code, while not running in a Docker container.

    from dask.distributed import Client
    from dask_gateway import Gateway

    gateway = Gateway('http://[redacted traefik ip]')
    cluster = gateway.new_cluster()

However, when I run the same code from a Docker container, I get this warning after `gateway.new_cluster()`.

    distributed.comm.tcp - WARNING - Closing dangling stream in <TLS  local=tls://[local ip]:51060 remote=gateway://[redacted ip]:80/dask-gateway.e71c345decde470e8f9a23c3d5a64956>

What is the cause for this? I have also tried running this with `--net=host` on the Docker container, that resulted in the same error.

**Additional Info**: This doesn't appear to be a Docker networking issue... I am able to use the Coiled clusters from within a Docker container, but not the Dask-Gateway clusters...

- Dask-Gateway version: 0.8.0

**Comment by jrdzha** [comment]
For additional information, it appears that the initial outgoing connection from the docker container to the traefik pod succeeds. A dask-scheduler is successfully spun up in the cluster. However, the connection drop (timeout?) that prevents further interactions.

**Comment by jcrist** [comment]
Hi @jrdzha, apologies for the delayed response here. My first guess is that you have a mismatch of dask/distributed versions between your container image and the rest of the cluster. Can you compare the version of dask you're using in your scheduler/worker images with the version of dask used in your client image (the one that fails to connect)? In distributed 2.23.0 a breaking change was added to the comms, so either all nodes need to be running `distributed` >= 2.23.0, or < 2.23.0, you can't mix them.

If you're using the same version of `dask` and `distributed` across all nodes, then we'll have to dig deeper. There's no reason why connecting from a docker container should be different than from outside a container.

**Comment by jcrist** [comment]
Closing as stale, feel free to reopen if the issue persists.
