### ISSUE TITLE
AWS ECS Backend

### ISSUE THREAD

**Issue by kinghuang** [dask/dask-gateway#317]
I'm interested in having an AWS ECS backend, particularly with Fargate support. It would be useful in my environment to be able to have Dask Gateway create clusters on demand backed by ECS.

Is there any documentation available about developing new backends?

**Comment by jcrist** [comment]
There is not (apologies). Backends generally take two forms:

- Subclass from [`DBBackendBase`](https://github.com/dask/dask-gateway/blob/7beea93d014c4e32ce719a2eccd38a24f8e32b7d/dask-gateway-server/dask_gateway_server/backends/db_base.py#L560), and implement methods for starting/stopping processes. The state of each process will be stored in a database managed by the api server. Note that this option only supports running one instance of the gateway at a time (robustness is achieved through persistence in the DB, but you don't get "scalability" (although benchmarks show it can still scale to 100s of clusters in a single instance). Most backends take this approach.
- Subclass from [`Backend`](https://github.com/dask/dask-gateway/blob/7beea93d014c4e32ce719a2eccd38a24f8e32b7d/dask-gateway-server/dask_gateway_server/backends/base.py#L32) and implement methods for starting/stopping processes, as well as querying and storing process state. This is much more complicated, but if ECS has an efficient queryable store about all the processes dask-gateway would be managing anyway, this may make more sense. The Kubernetes backend takes this route. This also may allow running more than one instance of the gateway api server.

My guess is that the second is probably the "correct" way to do this for ECS, but the first is likely easier. The base classes have decent docstrings, and the implementations subclassing from them hopefully provide some examples of how things should work.

If you don't mind me asking, what are you hoping to get from dask-gateway that you can't achieve with dask-cloudprovider?

**Comment by kinghuang** [comment]
> If you don't mind me asking, what are you hoping to get from dask-gateway that you can't achieve with dask-cloudprovider?

🤦‍♂️ I can't believe I've never heard of dask-cloudprovider! At a glance, it looks like FargateCluster or ECSCluster should suffice. Thanks for mentioning it!

**Comment by jcrist** [comment]
No problem! Glad to hear it. Is this issue resolved then?

**Comment by kinghuang** [comment]
Yeah, I'll consider this resolved for now. Thanks, again!

**Comment by quasiben** [comment]
@kinghuang you might also be interested in this PR https://github.com/dask/dask-cloudprovider/pull/129 which bring support to raw AMIs -- though ECSCluster/Fargate are probably best

**Comment by AndrewHannigan** [comment]
@jcrist I'd like to still make the case for an ECS backend for dask gateway.  Funny enough this is actually for a Prefect use case.  I need to use dask gateway because admins would prefer to not get my process ability to allocate resources, standard use case for gateway I assume.  But we want to use ECS because at this point everything we do is essentially through ECS with fargate already, so this makes things a lot easier to manage.

**Comment by AndrewHannigan** [comment]
https://github.com/dask/dask-gateway/issues/358
