### ISSUE TITLE
Add ability to modify worker cores and memory size in gateway dialog

### ISSUE THREAD

**Issue by kyprifog** [dask/dask-gateway#320]
It would be convienient to be able to modify the worker core and memory size in this dialog

<img width="361" alt="image" src="https://user-images.githubusercontent.com/991756/94958304-4cdfd680-04bd-11eb-8d01-bd0de0e98a98.png">

**Comment by jcrist** [comment]
It looks like you're using the [dask-labextension](https://github.com/dask/dask-labextension), which is separate from dask-gateway. This isn't a dask-gateway issue as much as a dask-labextension issue.

See https://github.com/dask/dask-labextension/issues/135 and https://github.com/dask/dask-gateway/issues/55 for more discussion.

Also note, that dialog is for scaling an active cluster - active clusters have fixed per-worker cores and memory, you currently can't change the size of a worker after the cluster is running.

**Comment by kyprifog** [comment]
I'll make an issue for dask-labextension next, but wouldn't you need to modify something in the neighborhood of here in order to support such a change?  https://github.com/dask/dask-gateway/blob/master/dask-gateway-server/dask_gateway_server/routes.py#L94

**Comment by jcrist** [comment]
I'm not sure I follow. There's some work we could do on the dask-labextension side to better expose the extra configuration options that dask-gateway exposes. The required steps for exposing that are partially documented in #55. There's a few ways we could go about doing this, but I wouldn't expect any of them to require changes to dask-gateway itself.

**Comment by kyprifog** [comment]
Thanks, this is what I was looking for:  https://github.com/dask/dask-gateway/pull/54
