### ISSUE TITLE
GCP Authentication Either Through Google Oauth or IAP?

### ISSUE THREAD

**Issue by rileyhun** [dask/dask-gateway#340]
We are trying to deploy dask gateway into a production environment on GCP, and the only road block would be applying some hardened security measures for authenticating to the proxy server. We would really like to leverage IAP or Google Oauth. Any idea on how to implement this?

**Comment by droctothorpe** [comment]
Implement a custom authenticator class by inheriting from the base [Authenticator](https://github.com/dask/dask-gateway/blob/master/dask-gateway-server/dask_gateway_server/auth.py#L49) class. 

You can use the three existing authentication implementations as a reference for how to do that:
* [Simple](https://github.com/dask/dask-gateway/blob/c3f6db1df8cd8bc320ba092ea75a82db0bb74b74/dask-gateway-server/dask_gateway_server/auth.py#L177)
* [Kerberos](https://github.com/dask/dask-gateway/blob/c3f6db1df8cd8bc320ba092ea75a82db0bb74b74/dask-gateway-server/dask_gateway_server/auth.py#L212)
* [JupyterHub](https://github.com/dask/dask-gateway/blob/c3f6db1df8cd8bc320ba092ea75a82db0bb74b74/dask-gateway-server/dask_gateway_server/auth.py#L281)

Once you've defined and injected your custom authenticator class, either through `extraConfig` in `values.yaml` or through the [extensions](https://github.com/dask/dask-gateway/blob/09526b1de9308cb6bc61351d1562db8ca14e78f8/resources/helm/dask-gateway/extensions/README.rst) directory, specify [custom](https://github.com/dask/dask-gateway/blob/master/resources/helm/dask-gateway/values.yaml#L50) auth and pass your subclass name through `values.yaml`. 

IMHO, and I'm not a maintainer so take this with a grain of salt, a Google Oauth authentication implementation is a good candidate for an upstream contribution.

**Comment by rileyhun** [comment]
> Implement a custom authenticator class by inheriting from the base [Authenticator](https://github.com/dask/dask-gateway/blob/master/dask-gateway-server/dask_gateway_server/auth.py#L49) class.
> 
> You can use the three existing authentication implementations as a reference for how to do that:
> 
> * [Simple](https://github.com/dask/dask-gateway/blob/c3f6db1df8cd8bc320ba092ea75a82db0bb74b74/dask-gateway-server/dask_gateway_server/auth.py#L177)
> * [Kerberos](https://github.com/dask/dask-gateway/blob/c3f6db1df8cd8bc320ba092ea75a82db0bb74b74/dask-gateway-server/dask_gateway_server/auth.py#L212)
> * [JupyterHub](https://github.com/dask/dask-gateway/blob/c3f6db1df8cd8bc320ba092ea75a82db0bb74b74/dask-gateway-server/dask_gateway_server/auth.py#L281)
> 
> Once you've defined and injected your custom authenticator class, either through `extraConfig` in `values.yaml` or through the [extensions](https://github.com/dask/dask-gateway/blob/09526b1de9308cb6bc61351d1562db8ca14e78f8/resources/helm/dask-gateway/extensions/README.rst) directory, specify [custom](https://github.com/dask/dask-gateway/blob/master/resources/helm/dask-gateway/values.yaml#L50) auth and pass your subclass name through `values.yaml`.
> 
> IMHO, and I'm not a maintainer so take this with a grain of salt, a Google Oauth authentication implementation is a good candidate for an upstream contribution.

Thanks I'll have to review what you said - it's a little confusing, but does implementing custom authentication through a base Authenticator class in Dask Gateway work similarly to how it works for JupyterHub? [1]

[1] https://stackoverflow.com/questions/54636656/how-do-i-use-google-iap-for-authenticating-to-jupyterhub

**Comment by droctothorpe** [comment]
Happy to help. It's very similar. The DG architecture is inspired by JH and there's a lot of overlap (though IMHO DG has made some notable architectural enhancements).
