### ISSUE TITLE
separate backend images for scheduler and worker

### ISSUE THREAD

**Issue by chrisroat** [dask/dask-gateway#343]
Is it feasible to have different images for scheduler and worker?  By default it seems fine to have them the same, but it seems useful to have a lightweight scheduler even if the worker has large dependencies.

**Comment by jcrist** [comment]
I'm not sure I see a solid use case for this. Docker images are usually cached per-layer on nodes - if your schedulers and workers are running in the same node pool there should be little added benefit here. Even if they're not sharing the same node pool, I'm not sure the extra bandwidth cost to download an image is worth the added complication (both for our code, and for users trying to manage compatibility across workers/scheduler/client). I'd need to see a strong argument for this before adding support.

**Comment by droctothorpe** [comment]
+1 to what Jim said. 

Another approach which avoids the drawbacks mentioned above and provides dramatically improved time to availability for both schedulers, and (more importantly) workers, would be to implement an optional image pre-puller daemonset much like [JupyterHub does](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/tree/master/jupyterhub/templates/image-puller).

**Comment by chrisroat** [comment]
Fair enough.  Our workers are pre-emptible, so we'd never co-locate them with schedulers.  Our worker image has unfortunately gotten large, which is why I asked.  (I have other approaches to pursue, like creating different images per dask cluster).  No worries if it's too much complexity. 

To mitigate the slow scheduler startup, we just pre-start about a handful of auto-scaling clusters (with zero min size) and store a mapping from our custom names (like "io" or "cpu" or "gpu") to the UUID.  The clients then connect using the custom names.  There is some savings because schedulers share nodes, but since it's all at cluster startup it does not matter.

**Comment by droctothorpe** [comment]
FWIW, I think an image pre-puller is still your best bet for improved scheduler start up time, even if your workers are not colocated.

If you don't want to go through the trouble of a more involved addition to the existing helm chart (though IMHO ( and, as always, I defer to Jim on this) this is a great candidate for an upstream contribution), something like this should work out of the box:

https://github.com/itaysk/kube-imagepuller

Just bear in mind that you'll need to update the daemonset anytime you update your scheduler/worker image (which is another argument in favor of adding an optional pre-puller to the DG helm chart).
