### ISSUE TITLE
Unable to Connect to Cluster - Timeout

### ISSUE THREAD

**Issue by rileyhun** [dask/dask-gateway#345]
**What happened**:

I deployed dask gateway using a helm chart on Google Kubernetes Engine. The Traefik proxy server is using an Internal Load Balancer. I am able to create a new cluster via Dask Gateway without any issues, but when I try connecting to the cluster, I get an OSError indicating a timeout. 

**What you expected to happen**:

I expected to be able to connect to the cluster

**Error**:

```
Task exception was never retrieved
future: <Task finished coro=<connect.<locals>._() done, defined at /opt/conda/lib/python3.7/site-packages/distributed/comm/core.py:288> exception=CommClosedError()>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/distributed/comm/core.py", line 297, in _
    handshake = await asyncio.wait_for(comm.read(), 1)
  File "/opt/conda/lib/python3.7/asyncio/tasks.py", line 435, in wait_for
    await waiter
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/distributed/comm/core.py", line 304, in _
    raise CommClosedError() from e
distributed.comm.core.CommClosedError
```

```
OSError: Timed out trying to connect to 'gateway://172.20.192.20:80/dask-gateway.d70fac7bd718405fae755e7813ec3b90' after 10 s: Timed out trying to connect to 'gateway://172.20.192.20:80/dask-gateway.d70fac7bd718405fae755e7813ec3b90' after 10 s: connect() didn't finish in time
```

**Minimal Complete Verifiable Example**:
```
cluster = gateway.new_cluster(options)
cluster.get_client()
```

**Anything else we need to know?**:

There is a case on StackOverflow with nearly the exact same issue as mine:

https://stackoverflow.com/questions/64347182/how-to-debug-a-commclosederror-in-dask-gateway-deployed-in-kubernetes

**Environment**:

- Helm chart: 0.8.0

**Comment by rileyhun** [comment]
I'll try using a different version of the helm chart and see if the error goes away.

**Comment by dgerlanc** [comment]
Use an older version of `dask` and `distributed`. I believe this is an error related to an upgrade in the communications protocol for `distributed`. These are the pinned versions of the dependencies for the current docker images:

```yaml
  - python=3.7.7
  - dask=2.21.0
  - distributed=2.21.0
  - cloudpickle=1.5.0
  - toolz=0.10.0
```

**Comment by rileyhun** [comment]
> Use an older version of `dask` and `distributed`. I believe this is an error related to an upgrade in the communications protocol for `distributed`.
> 
> These are the pinned versions of the dependencies for the current docker images:
> 
> ```yaml
>   - python=3.7.7
>   - dask=2.21.0
>   - distributed=2.21.0
>   - cloudpickle=1.5.0
>   - toolz=0.10.0
> ```
> 
> Also, see [#316 (comment)](https://github.com/dask/dask-gateway/issues/316#issuecomment-702947730).

Thanks Daniel - I'll give it a try.

**Comment by zonca** [comment]
thanks @dgerlanc I think this is the issue affecting me as well (Stackoverflow question), I was using dask `2.25.0`

Can you please point me to the DockerFile used to build the `daskgateway/dask-gateway` container? I found https://github.com/dask/dask-gateway/blob/master/resources/helm/example-images/Dockerfile but I don't see any pinning there.

**Comment by dgerlanc** [comment]
I believe this is `Dockerfile` that the release is built off of: https://github.com/dask/dask-gateway/blob/0.8.0/dask-gateway/Dockerfile

Note that the version on `master` is different: https://github.com/dask/dask-gateway/blob/master/dask-gateway/Dockerfile

**Comment by rileyhun** [comment]
So I started off by downgrading the following packages: `dask`, `distributed`, `cloudpickle` and `toolz`. I still ran into the same issue. 

Then I downgraded the helm version to 0.7.1. Again, still ran into the same issue. 

The last thing I tried was downgrading dask-gateway to 0.7.1 for the client and that seemed to resolve the issue.

**Comment by droctothorpe** [comment]
You're [dask](https://anaconda.org/conda-forge/dask) and [distributed](https://anaconda.org/anaconda/distributed) versions should be aligned across your workers, schedulers, Gateway API, and client. Use the Gateway API versions as your source of truth. 

For [8.0](https://github.com/dask/dask-gateway/blob/0.8.0/dask-gateway/Dockerfile):
```python
dask==2.21.0
distributed==2.21.0
```

For [master](https://github.com/dask/dask-gateway/blob/master/dask-gateway/Dockerfile):
```python
dask==2.28.0
distributed==2.28.0
```
 
If you're building a custom scheduler/worker image, unpin everything but `dask` and `distributed`, `conda install`, then pin with the solved versions.

**Comment by zonca** [comment]
ok, I confirm it is working also with `dask_gateway 0.8.0` `dask 2.25.0` `distributed 2.25.0`

**Comment by jcrist** [comment]
Yeah, there was a breaking change in the dask protocol in distributed 2.23.0 - all nodes in a cluster either need to be < 2.23.0, or >= 2.23.0. The last default dask-gateway image used 2.21.0, so if your client is running >= 2.23.0 you'd get a connection error. Switching to a custom image for the dask workers/scheduler with a newer version of dask should resolve things (as y'all have found above).

I hope to get a new release out in the next week or so, after which the default image should work again. Hopefully we've documented how to use a custom image well enough (see https://gateway.dask.org/install-kube.html#using-a-custom-image), so you should be able to resolve this yourself in the meantime.

Closing as resolved.

**Comment by jcrist** [comment]
> I hope to get a new release out in the next week or so

Dask-Gateway 0.9.0 has been released. Available on PyPI now, conda-forge should be up soon.

**Comment by rileyhun** [comment]
> > I hope to get a new release out in the next week or so
> 
> Dask-Gateway 0.9.0 has been released. Available on PyPI now, conda-forge should be up soon.

Thanks so much for the quick turnaround! Really appreciate it!
