### ISSUE TITLE
Dask Workers Keep Exiting Using Custom Docker Image

### ISSUE THREAD

**Issue by rileyhun** [dask/dask-gateway#347]
**What happened**:

I needed to bake in some additional python packages to the dask-gateway docker file. I pushed the docker image to google cloud container registry, and use this image as the default image for the dask workers. 

Unfortunately, the dask workers die and they rebuild themselves, continuously. 

The error is as follows:
```
PermissionError: [Errno 13] Permission denied: '/home/dask/dask-worker-space
```

**What you expected to happen**:
I expected the dask workers running on kubernetes pods to be stable and RUNNING without starting and stopping abruptly

**Minimal Complete Verifiable Example**:

config.yaml
```
  extraConfig:
    clusteroptions: |
      from dask_gateway_server.options import Options, Integer, Float, String

      c.KubeClusterConfig.idle_timeout = 3600

      def option_handler(options):
        return {
        "worker_cores": options.worker_cores,
        "worker_memory": "%fG" % options.worker_memory,
        "image": options.image,
        }

      c.Backend.cluster_options = Options(
        Integer("worker_cores", 2, min=1, max=8, label="Worker Cores"),
        Float("worker_memory", 4, min=1, max=16, label="Worker Memory (GiB)"),
        String("image", default="gcr.io/PROJECT_ID/CONTAINER_REPO:latest", label="Image"),
        handler=option_handler,
      )
```

dockerfile
```
FROM daskgateway/dask-gateway:0.9.0

ADD certs /certs/

RUN pip --no-cache-dir install --upgrade cloudpickle dask-ml scikit-learn \
nltk gensim spacy keras asyncio google-cloud-storage SQLAlchemy snowflake-sqlalchemy google-api-core gcsfs pyarrow mlflow \
tensorflow prefect hvac aiofile google-cloud-logging

```

**Anything else we need to know?**:

I deployed this on google kubernetes engine. I don't have any problem when I use the dockerfile from dockerhub as opposed to a custom dockerfile

**Environment**:

- Dask Gateway Version: 0.9.0
- Python version: 3.7.7
- Install method: Helm

**Comment by rileyhun** [comment]
Here's an update:

I ran a little experiment - I created an empty dockerfile that strictly uses the dockerhub  image as the base image and nothing else, then pushed to gcr. 

I still encounter the same issue with the nodes dying and rebuilding themselves. 

example Dockerfile:

```
FROM daskgateway/dask-gateway:0.8.0
```

**Comment by droctothorpe** [comment]
Instead of inheriting from `daskgateway/dask-gateway`, I recommend using the reference Dockerfile that Jim provided:

https://github.com/dask/dask-gateway/blob/master/resources/helm/example-images/Dockerfile#L64

**Comment by rileyhun** [comment]
Okay, thanks @droctothorpe - I will try that now

**Comment by rileyhun** [comment]
Hi @droctothorpe,

I can confirm that this approach doesn't work either. It's a very perplexing and frustrating issue. The nodes just quickly die.

**Comment by jcrist** [comment]
Hi @rileyhun, using either the example dockerfile or inheriting from the provided default image should work for what you're doing, I wouldn't expect a difference there.

You say you're using version 0.9.0, but have also commented 0.8.0 above. Note there was a breaking change in the 0.9.0 release - dask worker/scheduler images packaged using version 0.8.0 will not work with the 0.9.0 helm chart (and vice-versa - dask worker/scheduler images packaged using version 0.9.0 will not work with the 0.8.0 helm chart). Can you confirm you're not mixing versions between the gateway server and the worker/scheduler images?

If you're sure you're not mixing versions, can you confirm what version you're using? Can you provide a full traceback from a failing worker/scheduler node?

**Comment by rileyhun** [comment]
Hi @jcrist,

Thanks for your assistance!

I am absolutely positive that I'm being consistent with my versioning. In my original post, I was using 0.9.0 across both helm charts and dockerfiles for both dask workers & dask gateway server, so then in my second attempt, I tried using 0.8.0 afterwards. 

Here is the error logs from stackdriver:

![Uploading Screen Shot 2020-11-06 at 2.26.15 PM.png…]()

**Comment by rileyhun** [comment]
When I ssh into the docker container, there's no dask-worker-space in the /home/dask/ directory. Is that normal behaviour?

**Comment by rileyhun** [comment]
Any update on this?
