### ISSUE TITLE
Can dask-gateway work with JupyterHub service prefix?

### ISSUE THREAD

**Issue by rcthomas** [dask/dask-gateway#350]
From the documentation I see that dask-gateway can leverage JupyterHub authentication.  I see it also mentioned that dask-gateway can run as a Hub service, but I haven't seen in the docs or issues anything about configuring the service prefix?  In particular,

https://jupyterhub.readthedocs.io/en/stable/reference/services.html#writing-your-own-services

"When you run a service that has a url, it will be accessible under a `/services/` prefix, such as `https://myhub.horse/services/my-service/`. For your service to route proxied requests properly, it must take `JUPYTERHUB_SERVICE_PREFIX` into account when routing requests. For example, a web service would normally service its root handler at '/', but the proxied service would need to serve `JUPYTERHUB_SERVICE_PREFIX`."

Is that something that would need to be added?  Is there an easy way to prefix all the routes (or is it more complicated than that)?

**Comment by TomAugspurger** [comment]
Setting `gateway.prefix` should do the trick, as in https://github.com/dask/helm-chart/blob/master/daskhub/values.yaml#L59-L64 (that's all under a `dask-gateway` key, since the daskhub helm chart is wrapping dask-gateway's chart). Does that answer the question?

**Comment by rcthomas** [comment]
My original thinking was that I have CHP already running because Hub, and if I'm going to run `dask-gateway` behind it why do I need another proxy.  But if the proxy is how you're prefixing the routes, maybe I should just try it.

**Comment by consideRatio** [comment]
I'll go for a close at this point, this works!
