### ISSUE TITLE
Client Unable to Connect to Dask Gateway Cluster

### ISSUE THREAD

**Issue by rileyhun** [dask/dask-gateway#354]
**What happened**:

I ran into some sort of connection error connecting to the cluster created through Dask Gateway. Before, I was using an internal load balancer for the traefik proxy, and everything was working quite dandy. Later, I switched to using an internal ingress for the traefik proxy and this is when I started encountering this error. Not sure if switching to an ingress on GCP is the source of the error though.

**What you expected to happen**:

I expected to be able to connect to the cluster

**Minimal Complete Verifiable Example**:
```
client = cluster.get_client()
client
```

```
OSError: Timed out trying to connect to 'gateway://172.20.192.52:80/dask-gateway.4243788b41fb4c9da1d1979c9bc1215e'  after 10 s: Timed out trying to connect to 'gateway://172.20.192.52:80/dask-gateway.4243788b41fb4c9da1d1979c9bc1215e' after 10 s: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1091)
```

**Environment**:

- Helm chart: 0.9.0
- Python version: 3.7.8

**Comment by jcrist** [comment]
Dask-Gateway communicates over both
- http(s) for api requests and dashboards (for which an ingress would work great)
- tcp for dask client <-> scheduler comms (for which k8s ingresses don't currently work afaik)

> Not sure if switching to an ingress on GCP is the source of the error though.

K8s ingresses are generally only for http traffic, and likely won't handle the tcp traffic that dask client -> scheduler connections use. An ingress could be used for handling the API and dashboard requests, but if your clients are connecting from outside the k8s cluster then you'd still need something else to expose the TCP connections so an ingress doesn't seem worth it.
