### ISSUE TITLE
How to check a cluster's k8s Logs in Dask Gateway?

### ISSUE THREAD

**Issue by rileyhun** [dask/dask-gateway#355]
I tried checking the documentation and there doesn't seem to be any instruction on how to access the logs of a cluster generated by Dask Gateway. 

For me, I can just use the `kubectl logs` command, but that might not be so intuitive for our users. Is there a function we can use to view the logs of the dask workers?

**Comment by jcrist** [comment]
There is not, but there could be. See #77 for more information.

**Comment by jcrist** [comment]
There is `Client.get_scheduler_logs` and `Client.get_worker_logs`, which can be used to view the logs from *running* schedulers and workers, but not stopped schedulers and workers (for which we'd need something like #77).
