### ISSUE TITLE
Can't connect to deployed Dask cluster in k8s

### ISSUE THREAD

**Issue by mauricioalarcon** [dask/dask-gateway#356]
**What happened**:
I deployed a new Dask cluster as explained [here](https://docs.dask.org/en/latest/setup/kubernetes-helm.html#helm-install-dask-for-mulitple-users). I can see and use my cluster from the provided Jupyter Notebook which is created as part of the Helm Chart, using the typical recipe

```python
from dask_gateway import GatewayCluster
cluster = GatewayCluster()
client = cluster.get_client()
cluster.scale(2)
# then I can use this client to submit to the cluster
f = client.submit(inc, 7.2)
```

Now, I can see listed the  `proxy-public` and the `traefik-dhub-dask-gateway` as one of my services, but **only** the `proxy-public` has an `EXTERNAL-IP`

```
NAME                                    TYPE           CLUSTER-IP     EXTERNAL-IP      PORT(S)                      AGE
proxy-public                            LoadBalancer   10.3.245.29    104.zzz.yyy.xxx   80:30447/TCP                 66m
traefik-dhub-dask-gateway               ClusterIP      10.3.241.129   <none>            80/TCP                       66m
```

I've been trying to connect to the cluster as follows, based on this [documentation](https://gateway.dask.org/usage.html#usage)

```python
def get_gateway():
    import os
    os.environ["JUPYTERHUB_API_TOKEN"] = "f206000844a60da8b48e40f6c91c3f2a88a1xxxxxxxx"
    gateway = Gateway(address="http://104.zzz.yyy.xxx/services/dask-gateway",
                      auth="jupyterhub"
    clusters = gateway.list_clusters()
```
This one always returns as `401` 
```python
  File "/Users/xxxx/PycharmProjects/motive_data/venv/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 946, in raise_for_status
    headers=self.headers)
aiohttp.client_exceptions.ClientResponseError: 401, message='Unauthorized', url=URL('http://104.zzz.yyy.xxx/services/dask-gateway/api/v1/clusters/')
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x12038a310>
```
I've also modified the `traefic` service so that's exposed as `LoadBalancer` with a public ip and then trying the following

```python
def get_gateway():
    import os
    os.environ["JUPYTERHUB_API_TOKEN"] = "f206000844a60da8b48e40f6c91c3f2a88a1xxxxxxxx"
    gateway = Gateway(address="http://104.zzz.yyy.xxx/services/dask-gateway",
                      auth="jupyterhub",
                      proxy_address="http://104.155.yyy.xx")
    clusters = gateway.list_clusters()
```

And this yields to exactly the same result

I'm using a generated `token-1` for jupyterhub as explained [here](https://docs.dask.org/en/latest/setup/kubernetes-helm.html#helm-install-dask-for-mulitple-users) and while debugging and I can see that the `Authorization` header is set and sent with this token. But again, it always return as `401`

When I use the `token-2` it changes the response code to `500` but I can't seem to find more information on the logs.

What is that that I'm doing wrong? 

**What you expected to happen**:

Connect to the gateway to request cluster creation on my k8s environment.

**Anything else we need to know?**:

Posted this same issue on stackoverflow but it hasn't gained any traction. [here](https://stackoverflow.com/questions/65098875/how-am-i-supposed-to-connect-to-a-dask-gateway-deployed-in-kubernetes-from-an-ou)

**Environment**:

- Dask version: 2.30.0
- Daskhub version: daskhub-4.5.5
- Python version: 3.8
- Operating System: Ubuntu
- Install method: Helm chart following this [documentation](https://docs.dask.org/en/latest/setup/kubernetes-helm.html#helm-install-dask-for-mulitple-users)

**Comment by droctothorpe** [comment]
If you're trying to interact with DG using something other than DaskHub's Jupyter notebook server, I recommend following the vanilla DG installation instructions [here](https://gateway.dask.org/install-kube.html#) as opposed to the DaskHub installation instructions.

**Comment by mauricioalarcon** [comment]
@droctothorpe Thank you very much, the vanilla DG way solved my issue.
