### ISSUE TITLE
k8s deployed dask-gateway - How can I configure the log level for the workers?

### ISSUE THREAD

**Issue by mauricioalarcon** [dask/dask-gateway#357]
**What happened**:

I'm using the vanilla dask-gateway to install on [k8s](https://gateway.dask.org/install-kube.html#); it's not clear to me how can I configure the `log_level` for the workers, I see that the `default_values.yaml` [here](https://github.com/dask/dask-gateway/blob/master/resources/helm/dask-gateway/values.yaml) exposes entries for `gateway` the `controller` and `traefik` but not for the workers.

Before we were adjusting this through `LocalCluster(silence_logs=logging.DEBUG,..`

What is the easiest way to enable `DEBUG` for my workers?

**What you expected to happen**:
Enable DEBUG log level for workers to ease debugging code issues.

**Anything else we need to know?**:
I'm using a custom worker image so I can install custom pip packages.

**Environment**:

- Dask version: 2.30.0
- Dask Gateway: 0.90.0
- Python version: 3.8
- Operating System: 
- Install method (conda, pip, source): Dask-gateway k8s as described [here](https://gateway.dask.org/install-kube.html#)

**Comment by jcrist** [comment]
We don't expose a log-level configuration like you get for `LocalCluster` (the way people want to use logging for a large distributed system like dask-gateway is too varied for us to expose a single option). We leave this entirely handled by [dask's configuration](https://docs.dask.org/en/latest/configuration.html), and outside of dask-gateway. See https://docs.dask.org/en/latest/debugging.html#logs for reference on how to configure in general.

For simple configuration changes, you could do this via an environment variable in both the scheduler and worker pods:

```
DASK_DISTRIBUTED__LOGGING__DISTRIBUTED="debug"
```

How this gets in your worker/scheduler pods is up to you. You could add it to your docker image, add it to [c.KubeClusterConfig.environment](https://gateway.dask.org/api-server.html#c.KubeClusterConfig.environment) in your dask-gateway configuration, or expose `environment` as a [cluster option](https://gateway.dask.org/cluster-options.html) so users can set environment variables like this themselves.

**Comment by mauricioalarcon** [comment]
Thank you @jcrist this solved my issue.
