### ISSUE TITLE
Allow single-threaded running of workers

### ISSUE THREAD

**Issue by erl987** [dask/dask-gateway#362]
# Missing feature
I don't find any way to run the Dask workers single-threaded using `dask-gateway` (on Kubernetes). This is required because the Python package used on the workers by me is not thread-safe (some old underlying FORTRAN-code). This is certainly a common use case.

# Context
`dask` / `distributed` themselves offers free configuration to allow multi-threading or not: https://docs.dask.org/en/latest/scheduling.html

So it is just something like this:

```
from dask.distributed import Client

client = Client(address=SCHEDULER_URI, processes=True, n_workers=NUM_LOCAL_WORKERS, threads_per_worker=1)
```

However, if using `dask-gateway`, I do not find any hint on how to do this. In fact, if searching the documentation, there is no single hit for "thread" or similar keywords. A question on Stackoverflow did not get any results: https://stackoverflow.com/questions/65107333/how-to-run-single-threaded-workers-with-dask-gateway

Actually, the `dask-gateway` is starting the workers multi-threaded:
```
from dask_gateway import GatewayCluster

cluster = GatewayCluster(address=cluster_gateway_address)
client = cluster.get_client()
```

This is resulting in:
```
distributed.nanny - INFO -         Start Nanny at: 'tls://10.0.0.84:42257'
distributed.worker - INFO -       Start worker at:      tls://10.0.0.84:36645
distributed.worker - INFO -          Listening to:      tls://10.0.0.84:36645
distributed.worker - INFO -          dashboard at:             10.0.0.84:8787
distributed.worker - INFO - Waiting to connect to: tls://dask-64c3b5e1bdca47749bcce9572481daa9.default:8786
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          2
distributed.worker - INFO -                Memory:                    3.22 GB
distributed.worker - INFO -       Local Directory: /home/dask/dask-worker-space/dask-worker-space/worker-vd_dpnn0
distributed.worker - INFO - -------------------------------------------------
```

I tried this, but it does not seem to work:
```
from dask_gateway import GatewayCluster

cluster = GatewayCluster(address=CLUSTER_GATEWAY_URL, processes=True, n_workers=NUM_WORKERS, threads_per_worker=1)
client = cluster.get_client()
```

It results in:
```
ValueError: Unknown fields ['n_workers', 'processes', 'threads_per_worker']
```

# Suggested solution
It should be possible to configure `dask-gateway` regarding threads/processes in the same way as `dask` and `distributed`, at least multi-threading should be possible to switch off.

Or is this already possible right now? In this case the documentation should clearly describe this.

/Ralf

**Comment by AndreaGiardini** [comment]
Hey @erl987 
This Pul request is related to this: https://github.com/dask/dask-gateway/pull/353
