### ISSUE TITLE
[kubernetes] Cannot specify threads per worker

### ISSUE THREAD

**Issue by bolliger32** [dask/dask-gateway#364]
[This line](https://github.com/dask/dask-gateway/blob/e409f0e87f45e0a51fd7c009b5ec010bc5253bf1/dask-gateway-server/dask_gateway_server/backends/kubernetes/controller.py#L1055) fixes the threads per worker to the cpu request. There are use cases where you might not want this behavior. For example, say you are mapping a workflow that requires a lot of memory and can make use of other multithreading functionality (e.g. OpenMP) across multiple inputs. You may want your pod to have, say, 4 CPUs. But you may want to allow OpenMP to use 4 threads while only letting dask control a single thread. As the code stands right now, you have to enable 4 dask threads and thus your big workflow would run out of memory trying to run on 4 inputs simultaneously.

Would it make sense to add in a ``threads_per_worker`` config option, which defaults to being equal to `str(int(config.worker_cores_limit))`?

I'm mentioning this in the Kubernetes context b/c that's the backend we're using when running into this issue, but you might want it for other backends as well?

**Comment by AndreaGiardini** [comment]
There is an open PR already : https://github.com/dask/dask-gateway/pull/353

**Comment by bolliger32** [comment]
awesome, thanks @AndreaGiardini ! That's exactly what I'm looking for.

**Comment by erl987** [comment]
Relates also to issue #362.
