### ISSUE TITLE
Dask Gateway client makes two requests for authenticated endpoints

### ISSUE THREAD

**Issue by txu0393** [dask/dask-gateway#367]
It seems like the client first sends an unauthenticated request to Gateway APIs, and only tries sending an authenticated request after the first requests returns with a 401 status.

Is there a reason why it needs to send 2 requests? Why not just send the authenticated request on the first run?

Code:
https://github.com/dask/dask-gateway/blob/master/dask-gateway/dask_gateway/client.py#L396-L403

Suggested replacement:
```
headers, context = self.auth.pre_request(resp)
resp = await session.request(method, url, json=json, headers=headers,**self._request_kwargs)
self.auth.post_response(resp, context)
```
and modify `GatewayAuth.pre_request(self, resp)` to return `None, None`

**Comment by TomAugspurger** [comment]
@consideRatio can you clarify if this is standard practice for requests to JupyterHub endpoints? I recall seeing it elsewhere, but I'm not sure where.

**Comment by jcrist** [comment]
Not all auth protocols are efficient (looking at you, kerberos). Just like with a browser, it's fairly standard to make an unauthenticated request first, and only authenticate if a 401 is received. In practice this should only happen once for a `Gateway` client (after which a cookie is used for a session). Is this an issue for you, or just something you noticed while reading the code?

**Comment by txu0393** [comment]
For me, it's mostly the latter. I was looking through the logs produced by Dask Gateway server and there were a lot of 401 responses. At first, I thought we had some sort of misconfiguration or instability somewhere but it seems like this is the intended behavior.
It doesn't seem to cause any functional issues anywhere so this issue can be closed.

**Comment by txu0393** [comment]
Closing because this is working as intended
