### ISSUE TITLE
Allow only specific JupyterHub users to create clusters

### ISSUE THREAD

**Issue by kyri-petrou** [dask/dask-gateway#369]
Hello,

We use dask-gateway with Jupyterhub (using Jupyterhub authentication), both using Kubernetes backends. The Jupyterhub deployment uses the Zero to JupyterHub helm chart, along with a custom generic oauth authenticator.

We want is to be able to restrict the usage of dask-gateway to a specific subset of the users. Furthermore, it would be good if we could define cluster limits depending on the user group. It seems that this feature does not exist or it is not documented currently.

Furthermore, it is unclear how user information is passed to the options handler. Is it possible to define what groups each user belongs to in the Z2JH helm chart? Or do the groups need to be passed by the authenticator?

**Comment by droctothorpe** [comment]
There are probably other ways to do this but you can implement your own auth class and either pass in a list of approved users or have it make a backend call to retrieve the list.

You might be able to just copy the JH auth subclass and add some group validation logic to the authenticate function (around [here](https://github.com/dask/dask-gateway/blob/dbcb7269fe070fd54cdb220231c8d777a9437094/dask-gateway-server/dask_gateway_server/auth.py#L393)). There might be a way to let JH handle the groups as well.

As far as adjusting options based on users. All of that is configurable via the DG options form. You can present one set of options to group A, and a different set of options (more CPU, ram, etc.) to group B.

**Comment by kyri-petrou** [comment]
Thanks for your response. I'm trying to avoid creating a custom authenticator class just to avoid having to change it whenever the Jupyterhub authenticator class changes. But I suppose there might not be another way to do this. Would it be possible perhaps to add this feature in the next release?

Also, I was wondering, would it be possible to add a backend call in the extraConfig which would get the name of the user? Then subsequently raise an error if the user is not in a list of users (list of users can also go in the config)? I've been trying to figure whether it's possible but haven't got anywhere.

**Comment by droctothorpe** [comment]
If JH auth updates, the DG JH auth class will need to change as well and then you could just pull those changes in. IMHO, it's hard to imagine it going through breaking changes often enough to present a real issue. Implementing a custom auth class is pretty simple, and you would basically just be adding a few lines to the JH auth class. 

Username is available to the auth class so I would do the backend group validation call there. Curious to hear what other people say though. There may be a way to handle this in JH.

**Comment by kyri-petrou** [comment]
I attempted creating a custom class, but unfortunately I couldn't get it to work, I ended up forking the repo and did [these changes](https://github.com/dask/dask-gateway/compare/master...kyri-petrou:feature/restrict-users) to the JH auth class.

I didn't spend a lot of time thinking through the description and naming, but feel free to use (or I can create a PR) if it's something that is of interest to other users as well. Similarly, a blacklist could also be added if needed,

In case anyone found themselves here that deploys dask-gateway-server through Helm on Kubernetes, I also did the following:
1. Build the updated code into a docker image and stored it in a private repo
2. Updated the dask-gateway helm `values.yaml` as:

```
gateway:
  image:
    name: <image location>
    tag: <image tag>
  extraConfig:
    allowedUsers: |
      c.DaskGateway.JupyterHubAuthenticator.whitelisted_users = [
          "username_1",
          "username_2",
    ]
```

NOTE: I haven't tested this with groups yet, but I think it will work.

**Comment by droctothorpe** [comment]
Glad to hear you have a working solution! I think you can save yourself the trouble of managing your own image and just use the upstream by subclassing the `JupyterHubAuthenticator` class, updating the authenticate method, and passing in your custom auth class. I think this will work, but take my input with a grain of salt, heh. 

```yaml
gateway:
  auth:
    type: custom
    custom:
      class: JupyterHubAuthenticatorCustom

  extraConfig: |
    class JupyterHubAuthenticatorCustom(JupyterHubAuthenticator):
         async def authenticate(self, request):
            # Add your modifications here
```
You can also side-load the custom auth class as a module if you don't want a bunch of Python code in your values yaml per the instructions [here](https://github.com/dask/dask-gateway/blob/master/resources/helm/dask-gateway/extensions/README.rst).
