### ISSUE TITLE
Default cluster options for the helm chart?

### ISSUE THREAD

**Issue by cyrilcros** [dask/dask-gateway#371]
Hi, I installed dask-gateway as part of the daskhub Helm chart on Kubernetes. 
I see here (https://gateway.dask.org/configuration-user.html) that there is a `gateway.cluster.options`, is it possible to do the same thing in the Helm chart? Set x workers /  y cores / z GB of memory as a default?

**Comment by droctothorpe** [comment]
Yep. You can add cluster options server-side by injecting them into the dask hub helm chart values yaml around [here](https://github.com/dask/helm-chart/blob/master/daskhub/values.yaml#L59). 

Check out:
https://gateway.dask.org/cluster-options.html

And:
https://gateway.dask.org/cluster-options.html

**Comment by cyrilcros** [comment]
Thanks!
