### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/dask-gateway#381]
I'm currently blocked on needing some unreleased changes so would really appreciate a release soon.

@jcrist I know your time is limited so if there's anything I can do to help please let me know!

**Comment by rsignell-usgs** [comment]
Particularly looking forward to seeing https://github.com/dask/dask-gateway/pull/353 in a new release!

**Comment by jacobtomlinson** [comment]
> Plus it would be cool to have version 1.0.0

I expect `dask-gateway` will follow the other Dask projects and adopt CalVer.

**Comment by rsignell-usgs** [comment]
@jacobtomlinson , good point!   I guess that should take the pressure off a new release then!  😺

**Comment by TomAugspurger** [comment]
Jim's probably a bit busy these days (check his Twitter 😄).

But Jim, when you're back, I'd be happy to help out with release stuff. I think the first time it'd be helpful to pair on the release so that we can figure out the processes together.

**Comment by jacobtomlinson** [comment]
> I think the first time it'd be helpful to pair on the release so that we can figure out the processes together.

This is also what has put me off doing a release here. 

I'd also be keen to help out.

**Comment by consideRatio** [comment]
I'd also be happy to be onboarded to contribute to this process and in general contribute to helping dask-gateway stay alive - especially with anything related to the k8s Helm chart.

**Comment by AndreaGiardini** [comment]
Same here! Happy to help

**Comment by droctothorpe** [comment]
+1

**Comment by adamdrozdz** [comment]
+1

**Comment by dku-xyt** [comment]
+1

**Comment by kyprifog** [comment]
Noticed this stalled a bit, anything I can do to push it over the finish line?

**Comment by kyprifog** [comment]
Noticed this stalled a bit, anything I can do to push it over the finish line?

**Comment by AndreaGiardini** [comment]
Hey everyone! Any update on this? I am willing to help

**Comment by TomAugspurger** [comment]
Thanks for the offer. There's some work in https://github.com/dask/dask-gateway/pull/408 fixing up the CI and failing tests. I'm not sure if @aktech could use any help there.

Other than that, we should have all the help we need. We just need to find a time where Jim can do some knowledge transfer to the other Dask maintainers about the release process.

**Comment by consideRatio** [comment]
If someone has time to do some code review, it would make me very happy but could probably also help nudge us towards a release :)

- https://github.com/dask/helm-chart/pull/208
- #423
- #429
- #431

**Comment by TomAugspurger** [comment]
@jcrist this came up on the pangeo call today. Do you have any availability over the next couple weeks to month to push out a release?

If you aren't able to, then I'll start to work through the steps in https://github.com/dask/dask-gateway/issues/296. I likely won't have time until after Thanksgiving though. I'll post here with places where Jim is a sole-owner on some resource.

- [ ]: https://pypi.org/project/dask-gateway/ (fix at https://pypi.org/manage/project/kbatch/collaboration/)

**Comment by jacobtomlinson** [comment]
I'm still keen to sync up while this is being done to spread the knowledge.

**Comment by TomAugspurger** [comment]
Sounds good. I plan to work on this Friday the 3rd. I'm busy 8:00 - 9:00 Central, but am free afterwards. I might be on an hour or two earlier if I get a chance. @jacobtomlinson is there sometime on Friday that you would want to sync up?

I'll be taking notes (using https://github.com/dask/dask-gateway/issues/296 as a starting point) and will automate things where possible.

@jcrist are you able to add another maintainer on PyPI for dask-gateaway (https://pypi.org/manage/project/dask-gateway/collaboration/) and dask-gateway-server (https://pypi.org/manage/project/dask-gateway-server/collaboration/)

Another possible single-point-of-failure is uploading docker images to DockerHub (https://hub.docker.com/r/daskgateway/dask-gateway-server). I think https://hub.docker.com/orgs/daskgateway would be the right link to add people (I'm tomaugspurger on DockerHub). We could also explore publishing those images to GitHub container registry, so that we can re-use GitHub's permissions.

**Comment by consideRatio** [comment]
> I think https://hub.docker.com/orgs/daskgateway would be the right link to add people (I'm tomaugspurger on DockerHub).

Unless you pay for dockerhub at this point, you can't add maintainers as we could before. They have limited their free services to an unusable state. The jupyterhub team is moving to use quay.io in general whenever we rework things at this point.

**Comment by jacobtomlinson** [comment]
There is a discussion around moving away from Docker Hub in dask/dask-docker/issues/177. I've used Quay in the past and GitHub has a registry too. @consideRatio I'd be keen to know if you could share the decision process behind selecting Quay?

@TomAugspurger I'm afraid I'm on PTO Friday-Monday. But would be glad to sync up Tuesday.

**Comment by martindurant** [comment]
I would love to be in the sync as an observer, if possible.

**Comment by consideRatio** [comment]
@jacobtomlinson I responded in dask/dask-docker/issues/177!

I can't join efforts on thursday/friday though, and should avoid scheduling additional things on monday/tuesday as I have an important deadline 7th (tuesday). I'd love to be part helping this project come to life again though, so please feel free to involve me in any way I can contribute!

**Comment by jcrist** [comment]
Apologies for dropping the ball here for so long. This started as a "I don't have time, but I'd love to get to this eventually" thing (new baby and all), and as the community pressure increased my mental well-being around this issue decreased. I really _wanted_ to help, but even when I had free time I could not get myself to even respond here, much less do any work. Since I'm not longer paid to work on this project, this is all a free time thing, and doing high pressure OSS as a hobby clearly isn't sustainable for me.

That said, knowing how the release process goes I should definitely help out here. It'd be best if we could pair on this @TomAugspurger  (and others) whenever you're free too. I'm free after 12 on Friday, as well as most afternoons next week.

That said, there is at least one blocking issue (#414) that needs to be resolved before the next release. This shouldn't be a complicated fix, but it does need to be resolved. We should also verify the helm chart works with the latest distributed/dask releases (the tests are good but not sufficient).

As far as release locations, now would be a good time to switch off of dockerhub. No thoughts on a good alternative, quay.io seems fine, github has a thing too now I think? No strong thoughts.

**Comment by consideRatio** [comment]
Thanks @jcrist for sharing this, I can really empathize with your situation. I recognize especially the "even respond" part, I find it is often the first step to get hooked into doing more work or having a bad feeling about not doing more work, so it can be a big deal to respond.

I hope your response above felt like a starting point for relaxing any built up tension. I would really like you to have a good feeling about where this project goes going onwards and that you can stay in touch with it in a low pressure kind of way.

---

> We should also verify the helm chart works with the latest distributed/dask releases (the tests are good but not sufficient).

I can and will test that on wednesday 8th december! On 8th december and onwards, I'll be able to make it to any meetings or similar about dask-gateway as well.

**Comment by TomAugspurger** [comment]
No worries Jim! I really, really don't want to add more pressure to an already high-pressure situation.

I'll plan to work on #144 / do a bit of pre-release prep Thursday / Friday morning. Then maybe we sync up on https://whereby.com/dask-dev around 1:30 or 2:00 on Friday? It'd be good to chat about stuff, even if it's not release related :)

**Comment by jcrist** [comment]
Thanks Tom & Erik! That sounds good to me, lets shoot for 1:30 central on Friday.

**Comment by martindurant** [comment]
Would appreciate an invite or ping nearer the time, else I'm really likely to miss the time slot :)

**Comment by choldgraf** [comment]
Just want to show some love for @jcrist. Thanks for being awesome - open source maintenance is super hard and we all empathize :-)

**Comment by jacobtomlinson** [comment]
Totally agree with @choldgraf, thanks for driving this project to this point @jcrist! Sorry that this has become a source of stress, I totally empathise. Also totally agree with @consideRatio that hopefully, this is an opportunity for us to help you remove that stress.

Also thank you for openly talking about how it has affected your mental health. It's a big deal opening up about that topic so thank you for setting a great example. Seeing all the responses here really gives me good feelings about how supportive the Dask community is of each other.

**Comment by TomAugspurger** [comment]
Short update here: The only outstanding work items for the release are merging the changelog (https://github.com/dask/dask-gateway/pull/467) and possibly an update to the docker images from @jcrist (bumping the version of Debian & possibly conda used).

We're blocked on upload to PyPI right now (waiting for help with some account issues). Once we get that sorted out, hopefully in the next week or two, we'll be able to release.

In the meantime, I'll do a bit of work on release automation, including migrating to GitHub container registry (https://github.com/dask/dask-gateway/pull/466) and building / uploading the sdist and wheels from GitHub actions using cibuildwheel. Merging those will likely wait until just after the release.

**Comment by jacobtomlinson** [comment]
@TomAugspurger did the PyPI issues get resolved?

**Comment by TomAugspurger** [comment]
I'm not sure. @jcrist, do you know?

**Comment by mmccarty** [comment]
@jcrist Would it be possible to add another owner to PyPi so they can get it resolved? I'm also happy organize a call to coordinate, divide up tasks, and share knowledge among those expressing interest on this issue.

**Comment by martindurant** [comment]
ping to other interested people in this thread, incase you didn't get a notification: @consideRatio @TomAugspurger @jacobtomlinson @choldgraf 

@jcrist , we are happy to take over and I think we have enough manpower to follow through.

**Comment by mmccarty** [comment]
@jcrist @consideRatio @TomAugspurger @jacobtomlinson @choldgraf @martindurant I made a [doodle poll](https://doodle.com/poll/fvafd9yxgwgrzm4e?utm_source=poll&utm_medium=link) for times next week to get together to coordinate on a release.

**Comment by TomAugspurger** [comment]
The blocker from last time was uploading to PyPI. I don't know if Jim has had a chance to get his credentials sorted out, but IMO it's not worth scheduling something till we're able to do that.

**Comment by mmccarty** [comment]
Jim mentioned yesterday at the maintainers sync that he got that sorted out.

**Comment by consideRatio** [comment]
I'm opened #543 to track some remaining action points towards a release, I'll go ahead and close this issue in favor of it with concrete action points!

**Comment by consideRatio** [comment]
A release has been made! PyPI package and Helm chart is available but the conda-forge packages remains to be released still.

If someone has experience with conda-forge feedstocks it can become helpful as at least I personally have a lacking experience and know that we will need to make some changes. See https://github.com/conda-forge/dask-gateway-feedstock/pull/22#event-6458906322 for details!
