### ISSUE TITLE
Verify that Read the Docs is building after master -> main

### ISSUE THREAD

**Issue by jsignell** [dask/dask-gateway#382]
Spotted on https://github.com/dask/dask-cloudprovider/issues/244#issuecomment-795310925. Read The Docs was still building `latest` from the `master` branch and builds were failing. It was configured to build from the default branch, but had cached the value `master` somewhere. Manually pointing it to  `main` in the RtD control panel fixed things.

**Comment by martindurant** [comment]
@jcrist , can you give me RTD rights?

**Comment by jcrist** [comment]
Dask-gateway doesn't use readthedocs, rather it uses doctr and travis-ci to build and GitHub pages to host. I personally prefer GitHub pages to readthedocs, but we should transition off travis-ci to GitHub actions.

**Comment by martindurant** [comment]
OK, thanks.

The CI transition might be a headache, we'll look into it.  

I see the `doctr deploy` section of .travis.yml, so we'll need to provide the secure credentials in a way that gha understands.
