### ISSUE TITLE
Secret mirroring with kubed

### ISSUE THREAD

**Issue by droctothorpe** [dask/dask-gateway#384]
This might be overkill, but I think that kubed could work as a secret mirroring solution for dynamic namespaces. The secret would just require an annotation. Curious to hear your thoughts. 

https://appscode.com/products/kubed/v0.12.0/guides/config-syncer/intra-cluster/

**Comment by jacobtomlinson** [comment]
What secrets would you want to be synced between namespaces?

**Comment by droctothorpe** [comment]
The secret generated in each dynamic namespace to support client to scheduler mtls, but this is probably premature security optimization since the API can just be configured to read secrets from all namespaces. Closing.
