### ISSUE TITLE
Helm chart: expose worker_threads configuration

### ISSUE THREAD

**Issue by Kirill888** [dask/dask-gateway#397]
I would like to configure number of worker threads separately from `worker.cores.{request|limit}`.

But generated code here:

https://github.com/dask/dask-gateway/blob/c81c71fa6e1e1f2257e43261e7965849f2e6cb7a/resources/helm/dask-gateway/templates/gateway/configmap.yaml#L55-L75

does not expose `worker_threads` [configuration option](https://gateway.dask.org/api-server.html#c.KubeClusterConfig.worker_threads). I think this should be easy to add?

I'd like to run 8 threads on an 8 core node, but I need to request fewer cores from k8s to fit pod into the node, with the current helm we end up with 7 threads worker on an 8 core instance and I don't think k8s needs one whole core for service processes.

**Comment by aktech** [comment]
I believe this was added in [#413](https://github.com/dask/dask-gateway/pull/413/files#diff-6a39f974b7a00b6860a3dee3a028145e3d2ede44dd78309f428b122af99f13aeR69)
