### ISSUE TITLE
paywalling of cloudera repo

### ISSUE THREAD

**Issue by martindurant** [dask/dask-gateway#401]
The CI dockerfile for Yarn fails with 404-unautheriized. This appears to be because of the paywalling by Cloudera described in:
https://www.cloudera.com/downloads/paywall-expansion.html

**Comment by quasiben** [comment]
It's a bit out of date but I was able to test some yarn things with Jim's https://jcristharif.com/hadoop-test-cluster/ .  There are also images for 
- cdh5: a CDH 5 installation of Hadoop 2.6 (image at jcrist/hadoop-testing-cdh5)
- cdh6: a CDH 6 installation of Hadoop 3.0 (image at jcrist/hadoop-testing-cdh6)

**Comment by martindurant** [comment]
Yes indeed, and the actual gateway project images are still available on dockerhub, but this will be a problem in the future. There are other implementations we could piggyback on, though, such as https://github.com/big-data-europe/docker-hadoop (which I just successfully tried with dask-yarn).

**Comment by consideRatio** [comment]
I want to address this, but I'm really not happy about doing it by using `FROM: <very old docker image we can't rebuild>` though.

> The original apache hadoop installer is complete, but with less config out of the box and all different paths.

I'll figure I'll work from this assumption, if anyone have advance on a starting point or similar to go from I'd appreciate it. A quick google led me to this post: https://programming.vip/docs/docker-x-hadoop-use-docker-to-build-hadoop-clusters-from-scratch.html

**Comment by martindurant** [comment]
Yes, that's fine BUT: what most of these setup walk-throughs skip (because it's very hard) is kerberos and encryption. Do we want to explicitly test those for gateway, or can we possibly trust that the work of gateway is decoupled from skein's security settings? Can we get skein to test them separately?

**Comment by consideRatio** [comment]
Thanks @martindurant for helping me navigate this! I'm clueless currently, but that helps me learn what I need to learn to start grasping things of relevance here. I'll need to keep processing this a bit before I can think somewhat clearly.

## Today I've learned some about

- `skein`
  - [GitHub](https://github.com/jcrist/skein#readme)
  - [Documentation](https://jcristharif.com/skein/).
- Hadoop YARN: "A framework for job scheduling and cluster resource management."
  - [GitHub](https://github.com/apache/hadoop)
  - [Documentation](https://hadoop.apache.org/)
- [Kerberos](https://en.wikipedia.org/wiki/Kerberos_(protocol)): a authentication protocol
  - V5, the current version of the protocol declared 2005 in [RFC 4120](https://datatracker.ietf.org/doc/html/rfc4120)
  - Kerberos server, usually called Key Distribution Center (KDC)
  - Kerberos database or KDB5
  - Associated utilities like `kadmin` and `kdb5_util` are documented [here](https://web.mit.edu/kerberos/krb5-1.12/doc/admin/admin_commands/index.html)
  - [keytab](https://web.mit.edu/kerberos/krb5-devel/doc/basic/keytab_def.html)
  - [Kerberos glossary](https://web.mit.edu/kerberos/krb5-1.5/krb5-1.5.4/doc/krb5-user/Kerberos-Glossary.html#Kerberos-Glossary)
- [`alternatives`](https://www.redhat.com/sysadmin/alternatives-command) command.
  https://github.com/dask/dask-gateway/blob/7d1659db8b2122d1a861ea820a459fd045fc3f02/continuous_integration/docker/hadoop/files/root/setup-hadoop.sh#L5-L9

**Comment by martindurant** [comment]
https://steveloughran.gitbooks.io/kerberos_and_hadoop/content/sections/kerberos_the_madness.html

**Comment by consideRatio** [comment]
@martindurant I think I managed, it took ages to get it right though. I've opened https://github.com/dask/dask-gateway/pull/519 which is ready for review but is kind of blocked by making published ghcr.io images public so that the hadoop/slurm/pbs tests in #519 can run properly.

Martin can you check if you can get the images to become public? See https://github.com/dask/dask-gateway/issues/484#issuecomment-1086737441 for links to try that and a comment on why this is needed.
