### ISSUE TITLE
Default thread count for k8s workers

### ISSUE THREAD

**Issue by martindurant** [dask/dask-gateway#414]
> By default the worker should use as many threads as cores (which has a pre-configured default). A user shouldn't be forced to configure the number of threads unless they want it to differ from the number of cores. I think we want worker_threads to set allow_none=True, then fix the logic in the k8s backend to use worker_cores if worker_threads is None.

Posting from https://github.com/dask/dask-gateway/pull/413#discussion_r678388095

Currently, if you don't specify the worker threads, you get
```
The value of the 'worker_threads' trait of a KubeClusterConfig instance should not be less than 1, but a value of 0 was specified.
```

**Comment by jcrist** [comment]
Note this is a major regression added in #353, and should be fixed before the next release.
