### ISSUE TITLE
Questions about Job Queue systems

### ISSUE THREAD

**Issue by jcrist** [dask/dask-gateway#42]
I've been working on adding support for Job Queue (PBS, Slurm) systems to `dask-gateway`, and have the following questions:

- How do users distribute software throughout the cluster (if at all)?

  For other cluster systems there's a clear artifact (docker image, tar archive, etc...) that should be used by the cluster manager (YARN, kubernetes, etc...) for distributing software to all nodes. How do people accomplish this for job queueing systems? Rely on a networked file system, and store custom software there? Manually `scp` during the job? Rely on the cluster manager's concept of `stagein` files (PBS has this, Slurm doesn't seem to)? Rely on administrators?

- How should log files be handled?

  Other systems have tools for managing log files externally to the users (e.g. YARN stores them on HDFS in an admin managed directory). Job queueing systems seem to default to outputting the log files in a user owned directory. I'm fine doing this (currently they're stored in `~/.dask-gateway/<cluster-id>/*`), but am worried that this may require users to periodically clean out their log files to avoid ever-growing disk usage. Ideally the gateway wouldn't be in the business of managing log files, and would leave that to the backing system.

- In what directory should jobs be run?

  To match the behavior of other cluster manager's, I'd prefer this directory to have the following attributes:

  - Readable only by the user who submitted the job
  - Temporary - user's shouldn't have to manually cleanup after the job, they should rely on the system to handle this (that system could be `dask-gateway` if the cluster backend doesn't support this option)
  - Fast disk (i.e. probably not on a networked file system)

  PBS has the `-Wsandbox=PRIVATE` attribute to create a temporary directory to run the job in (admin configurable). For other systems right now I'm running in `~/.dask-gateway/<cluster-id>/`, which may be on a network file system and isn't ideal.

  One option that could be consistent across all job queue backends is to provide a configurable `local_directory` that has fast storage, and manually create a user-owned sub-directory of this on scheduler/worker startup (and clean it up on shutdown). I'm not sure what a good default for this should be (`/tmp`? `~/.dask-gateway`?), or if it would require templating by user information (e.g. `"{user_home}/.dask-gateway"`)

**Comment by jcrist** [comment]
cc @guillaumeeb, @lesteve, @jhamman, and @mrocklin (major `dask-jobqueue` contributors) for any thoughts/comments you might have.

**Comment by guillaumeeb** [comment]
Here are my inputs on what we do on our system:

> How do users distribute software throughout the cluster (if at all)?

They either use the softwares provided by administrator, which can be linux packages deployed on all nodes, but generally are softwares installed on a networked file system. Users have the ability to install software on this networked file system (typically conda environements), as long as it doesn't require admin rights 

> How should log files be handled?

So yes, the default is to copy stderr and stdout files at the end of a job in the directory from which the user submitted the job, or to whatever the user asked for in the job spec. This led to tons of output files appearing in working directory when using dask-jobqueue at the beginning. Obviously you did a better job than us! 

In your case, I'm not sure what should be done, you do'nt have a lot of choices:

- Just put it in some user directory as your doing now, but yes, at one point they may have to do some cleaning.
- Mirror YARN behavior, have some shared directory where you ask the cluster manager to put all log files. Cleaning is the admins responsibility then.
- Just drop all the files by default! Not nice for debugging.

> In what directory should jobs be run?

I'd go for somewhere in the HOME directory by default. Users are used to have their jobs running from a networked shared folder. But some other advices:

- You should provide some mean to configure this.
- You must be able to specify the local-directory worker arg, or easilly disable spilling. I think most scheduler provides some environment variable for a tmp directory local to the computing node if it exists. 

But you can also force the worker to run from this tmp directory if it exists.

PBS Pro typically specifies $TMPDIR variable when inside a job, which goes to /tmp/pbs-$JOBID folder created for the given job and which only the submitting user has access to.

**Comment by jcrist** [comment]
Thanks @guillaumeeb, this information is really helpful.

One last thing - in your experience how long on average does a single worker job take to start (trying to pick a good default timeout). My test cluster is only used by me, and probably starts artificially quickly :).

**Comment by guillaumeeb** [comment]
Our cluster is pretty busy during the day, but there is always some free slots. I typically use workers with 4 cores for testing and demo, and I can always start a few jobs almost instantly (a few seconds at most).

However, I imagine this depends a lot on the HPC cluster configuration and occupation, and also on the workers configuration. If I asked for full nodes workers, I'll probably wait longer. If the queue I use was full, it could take some time for a slot to be freed, say minutes to hours.

**Comment by mrocklin** [comment]
My experience is similar.  I would say it's bimodal with one peak at around
10s and another at 30-120m.

**Comment by mrocklin** [comment]
The peak around 10s is larger.
