### ISSUE TITLE
Update to use `mamba` instead of `conda` in Dockerfiles

### ISSUE THREAD

**Issue by consideRatio** [dask/dask-gateway#432]
### Update

No consensus to make a shift to use `mamba` instead of `conda` currently within these Dockerfiles.

### Original proposal

I suggest we update to use `mambaforge` to setup `conda` and such in our Dockerfiles. It helps speed up installation by being a conda replacement with higher performance.

There have been some quirks about a Python version updated that I'll be on the lookup in the unlikely case it would happen, otherwise it has been a great success to transition to use `mamba` in projects like docker-stacks and repo2docker with very significant performance improvements to build images.

**Comment by consideRatio** [comment]
> Can you expand on your motivation here for this switch? Are image build times measurably too slow?

`mamba` is so much faster to work with in general, so if end users depend on either `conda` or `mamba`, it would be beneficial for them to transition to `mamba` as well I think - but of course, it would be something they would have to learn about.

The build time in a CI system is not so critical.

Using an alias can probably go wrong because not exactly everything is compatible with mamba, for example `conda config` or similar if i recall correctly.

**Comment by consideRatio** [comment]
I suggest we close this issue as we didn't reach consensus to start using `mamba`, let's reopen it if we want to evaluate if we think its worth to use `mamba` later down the line. I'll go for a close on it myself in a week if nobody objects.

**Comment by consideRatio** [comment]
I'd like to re-open this issue at this point for re-evaluation. In #489, there was a request to be able to configure how we install conda/mamba to enable opting away from the installation we now go with. While it would be possible to allow that to be configurable etc, I wondered if we could avoid adding complexity by simply switching to a new installer at this point.

If there is agreement to switch, I'd be very happy to get it done.

1. @holzman raised a point about anaconda license change, @holzman can you clarify what change you refer to?
2. Mamba has become so widely accepted that its being integrated in `conda`: https://www.anaconda.com/blog/a-faster-conda-for-a-growing-community.
3. `mamba` performance is so much better, that the time to build images etc can improve, which can reduces test run duration. Currently our k8s/helm tests are the slowest due to building images among a few other slow things.
4. `mamba` has been out for a longer time now and has matured further and been more widely adopted since we considered it before.

**Comment by holzman** [comment]
@consideRatio: to be accurate, the TOS changed in 2020, but it is beginning to affect us now: https://github.com/dask/dask-gateway/issues/489#issuecomment-1074077668.
