### ISSUE TITLE
Add documentation about networking within the Helm chart

### ISSUE THREAD

**Issue by consideRatio** [dask/dask-gateway#435]
@jcrist made this excellent writeup about networking that I hope to retain in documentation somewhere and not loose track of: https://github.com/dask/dask-gateway/issues/360#issuecomment-741767913

**Comment by rigzba21** [comment]
Hi! I'd love to help out with this, as I've been troubleshooting networking with my team's helm chart deployment lately, and would like to contribute to the docs to assist with newcomers to the stack.

**Comment by consideRatio** [comment]
Closed by #454!
