### ISSUE TITLE
[Helm] Please make a new dask-gateway release

### ISSUE THREAD

**Issue by cyrilcros** [dask/dask-gateway#459]
Kubernetes 1.22 is out with some deprecations like `apiextensions.k8s.io/v1beta1` (https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22), which affect the Trafik CRDs for example. The chart no longer works for this version, while 1.21 was still okay.

The current  dask-gateway chart version, 0.9.0, is one year old, and you already have done the required changes. Please either cut a new release or consider making a `nightly` release...
Thanks for all your work!

PS pinging @consideRatio @jcrist

**Comment by TomAugspurger** [comment]
I'm setting some time aside the week after Thanksgiving in the US to work on this. See https://github.com/dask/dask-gateway/issues/381 if you want updates.
