### ISSUE TITLE
Helm chart: offload dependency updates of python packages in the chart's Dockerfiles

### ISSUE THREAD

**Issue by consideRatio** [dask/dask-gateway#475]
### Summary

I'd like to help automate parts of maintaining this project, and due to that I'm considering how to bump dependencies installed in the Helm chart's Dockerfiles.

The Helm chart relies on two Dockerfiles ([dask-gateway](https://github.com/dask/dask-gateway/blob/main/dask-gateway/Dockerfile) / [dask-gateway-server](https://github.com/dask/dask-gateway/blob/main/dask-gateway-server/Dockerfile)) that both install some python packages that could benefit from some regular updates, while also benefit from being pinned as that helps us track changes.

### How JupyterHub Helm chart address this

The JupyterHub Helm chart solution to this includes the following parts.

1. A [`requirements.in`](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/main/images/hub/requirements.in) file with unpinned dependencies
2. A [`requirements.txt`](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/main/images/hub/requirements.txt) file with pinned/frozen dependencies
3. A [Dependabot configuration](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/main/.github/dependabot.yaml) to make Dependabot automatically open PRs updating the pinned/frozen dependencies
4. A [`dependencies`](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/main/images/hub/requirements.txt) script that can be run locally to automatically generate the `requirements.txt` file from scratch using the python module `pip-tools` included CLI called `pip-compile`.
   - A reason for having a script etc, is that by using the script, you run `pip-compile` from within the Dockerfile which ensure you get version reasonable for that context.
   - This has turned out to not be so important as soon as we started using Dependabot though, but with a requirements.in and requirements.txt, dependabot will only update dependencies in requirements.txt that are listed in requirements.in - not any dependency of those. If one would want to update all dependencies of the dependencies, one would need to run `pip-compile` again.

### Considerations

1. We currently use `conda` to install packages, and then `pip-tools` and the jupyterhub solution won't work.
2. Dependabot can probably use an `environment.yaml` file in a similar way - I lack experience with it though - would it include pinned versions that are changed by dependabot?
3. Is there agreement towards going for a dedicated dependency file to be maintained by Dependabot?
4. Is there a wish to retain use of `conda` in favor of `pip` to install the dependencies in these two images?

**Comment by martindurant** [comment]
I am somewhat in favour of having an environment file to be included in the docker build process, for the purpose of both being explicit and allowing for automatic updates.

> Is there a wish to retain use of conda in favor of pip to install the dependencies in these two images?

Anaconda tools tend to? Is there a good argument to switch for pip, does it result in a smaller image or some other benefit? Naturally, within the image, we only have exactly one environment.

**Comment by consideRatio** [comment]
Closing this in favor of #437 with a more explicit title.

We now have standalone requirements.txt files which would enable us to have a frozen requirements.txt etc generated and maintained from requirements.in.
