### ISSUE TITLE
CI: avoid and fix ci failure, either by relying on pre-commit.ci or running pre-commit in a github workflow

### ISSUE THREAD

**Issue by consideRatio** [dask/dask-gateway#476]
### Issue summary

The `main` job in the `test` workflow [fail in a step](https://github.com/dask/dask-gateway/runs/5167437773?check_suite_focus=true) running `black . --check` because of the latest version of black is used, while it don't fail when using `pre-commit` which has a config with a pinned version. If we relied on pre-commit to run checks, instead of manually running `flake8` and `black` - the pinned versions would be used and this wouldn't happen.

### More than a solution to this

I'd like to propose a fix that does a bit ore than just fixing this.

In the jupyterhub ecosystem we started relying on running the pre-commit checks with the pre-commit.ci service which does three things - of which a github workflow would only easily do one.

1. It runs pre-commit.ci based on the .pre-commit-config.yaml file (very fast)
2. It automatically submit PRs if a version needs to be updated in a .pre-commit-config.yaml file
3. It automatically adds a commit to a PR with autoformatting changes if needed

An example all of of this in https://github.com/jupyterhub/jupyterhub/pull/3784 is when pre-commit.ci has:
- Created a PR to automatically update versions in a .pre-commit-config.yaml file
  ![image](https://user-images.githubusercontent.com/3837114/153716868-b7870911-6c5a-490b-9ab2-ab7d96804cdd.png)
- Automatically added a commit to a PR by having run pre-commit and letting it do autoformatting work (in this case, with new config)
  ![image](https://user-images.githubusercontent.com/3837114/153716890-36b8f59a-6a58-4c57-820a-88a1c2bbbb3a.png)
- Automatically run tests and reported results
  ![image](https://user-images.githubusercontent.com/3837114/153716906-be9b06ef-d3dd-4a66-aba9-1993aa396beb.png)

### Reference to related code

https://github.com/dask/dask-gateway/blob/bee9255e5ea0d77f456985cd91b2622bb3776dbb/.github/workflows/test.yaml#L46-L49

https://github.com/dask/dask-gateway/blob/bee9255e5ea0d77f456985cd91b2622bb3776dbb/.pre-commit-config.yaml#L1-L11

### Suggested action points

- [x] Activate pre-commit.ci as a service for this project.
   This is done by visiting the pre-commit.ci GitHub app and making it available for the dask GitHub organization to use: https://results.pre-commit.ci/
   And declare it to be used specifically on this github repository at: https://github.com/organizations/dask/settings/installations
   This means it would...
   - a) automatically runs a pre-commit CI/CD check like a github workflow would
   - b) automatically create PRs updating the version of pre-commit hooks defined in .pre-commit-config.yaml when new versions are out - at most once a week.
   - c) automatically add commits to PRs with autoformatting changes based on the .pre-commit-config.yaml file if needed
- [ ] Merge a PR, such as #477, removing the manual test step [here](https://github.com/dask/dask-gateway/blob/bee9255e5ea0d77f456985cd91b2622bb3776dbb/.github/workflows/test.yaml#L46-L49) and instead rely on pre-commit.ci to report if running pre-commit led to a failure.

**Comment by consideRatio** [comment]
@jacobtomlinson perhaps we can pilot this in dask/helm-chart? The value could be demonstrated here, were a commit would have been added automatically: https://github.com/dask/helm-chart/pull/225#pullrequestreview-884388130

**Comment by jacobtomlinson** [comment]
We commonly use the [pre-commit GitHub Action](https://github.com/dask/dask/blob/main/.github/workflows/pre-commit.yml), rather than the CI. I would be more in favour of using that to be consistent with other Dask projects, rather than introducing another external CI.

**Comment by jacobtomlinson** [comment]
Looking at your screenshots above I see the Precommit CI pushes back commits to auto-fix things. That does seem like a nice benefit.

**Comment by martindurant** [comment]
If Jupyter is using it, we can trial it here and perhaps port it to other dask projects if we find it convincing?

**Comment by jacobtomlinson** [comment]
Ok let's do it! I've enabled pre-commit CI for this repo.

@consideRatio could you update #477 to also remove the existing black checks? Then we can merge and see how things go.

I would suggest opening an issue on dask/community to discuss rolling this out to other parts of Dask would be a good next step.

**Comment by consideRatio** [comment]
@jacobtomlinson @martindurant thanks for considering this and agreeing to pilot this.

@jacobtomlinson nice catch, I forgot to push the commit doing that.

**Comment by jacobtomlinson** [comment]
Ok merged! @consideRatio would you mind opening the community issue to describe the benefits of making this change and to let folks know we are trialing on `dask-gateway`?

Also happy to make this change on the helm chart too, the autofix would be especially nice there because not many folks are used to running `frigate`.

**Comment by consideRatio** [comment]
@jacobtomlinson thanks for taking the leap, this is a quality of life improvement for me! I hesitated initially within JupyterHub as well, but were convinced by seeing it piloted in a repo - as championed by @manics if I recall correctly :) Thanks @manics!!!

https://github.com/dask/community/issues/222
