### ISSUE TITLE
Installing Dask-gateway using Helm failed for Kubernetes v1.22.1

### ISSUE THREAD

**Issue by tejinc** [dask/dask-gateway#487]
**Command run**:
helm install --version 2022.2.1 dhub dask/daskhub --namespace dhub --create-namespace
or
helm install --version 0.9.0 dhub dask/dask-gateway --namespace dhub --create-namespace

**What happened**:
Installation failed with the following output:
Error: INSTALLATION FAILED: failed to install CRD crds/daskclusters.yaml: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1".

According to https://kubernetes.io/docs/reference/using-api/deprecation-guide/: 
The apiextensions.k8s.io/v1beta1 API version of CustomResourceDefinition is no longer served as of v1.22.

**What you expected to happen**:
Upgrade the API version to apiextensions.k8s.io/v1

**Minimal Complete Verifiable Example**:
Install Kubernetes v1.22.1, install helm, and run the above installation commands. 

**Environment**:

- Dask-Gateway version: 0.9.0
- Kubernetes: 1.22

**Comment by martindurant** [comment]
Please see https://github.com/dask/dask-gateway/pull/479 : you will need to use the new CRDs from this repo's main until we have a release.

**Comment by rigzba21** [comment]
@tejinc see https://github.com/dask/dask-gateway/issues/486#issuecomment-1069248773 for an example of the manual file updates I had to make in my helm chart. 

I hope this helps!

**Comment by consideRatio** [comment]
There is no remaining action point for this besides cutting a release I think. I figure it makes sense to close it for now - anyone that sees this, note that you need a version > 0.9.0
