### ISSUE TITLE
Make conda/mamba flavor a build arg

### ISSUE THREAD

**Issue by holzman** [dask/dask-gateway#489]
I know there was some discussion of using mamba in #432.  Due to the change in anaconda.org's licensing agreements, we prefer to use miniforge/mambaforge whenever possible.

A patch like this: https://github.com/holzman/dask-gateway/commit/96b714515a528836f71d4a2c58adf10649af9d71 seems like it should make everyone happy.

**Comment by dhirschfeld** [comment]
Maybe just start with the official base images instead of duplicating config?
https://github.com/conda-forge/miniforge-images

**Comment by holzman** [comment]
Sure, we could do something like this instead: https://github.com/holzman/dask-gateway/commit/c2c54e084b2091182f72d83af364ec049521e4e9.  One downside - since the base image is bigger, the derived image is larger by about 130 MB.

**Comment by consideRatio** [comment]
I'd like to avoid changing the base image, it includes too much potential unwanted consequences etc.

I think providing a configurable arg is reasonable if needed, but I'd like some clarity about the reason to change you describe.

> Due to the change in anaconda.org's licensing agreements, we prefer to use miniforge/mambaforge whenever possible.

Do you have a reference to this?

**Comment by martindurant** [comment]
> Due to the change in anaconda.org's licensing agreements, we prefer to use miniforge/mambaforge whenever possible.

(I am not a lawyer...) Conda and the anaconda installers are wholly free and open source. However, use of the anaconda repository is only unlimited free for certain categories, and enterprises may be required to purchase [Commercial Edition](https://www.anaconda.com/blog/anaconda-commercial-edition-faq) or other product. Note that (mini-, micro-...)mamba uses the same repos as conda, and that conda-forge's repo data and metadata are hosted by anaconda, so the terms are (I think) the same.

**Comment by holzman** [comment]
The licensing change dates from 2020 (https://www.anaconda.com/blog/sustaining-our-stewardship-of-the-open-source-data-science-community).  Recently, anaconda.org decided that my organization - which *is* a 501(c)(3) research institution - fell under "commercial activities" and would require purchasing licenses to use the default channels.

@martindurant: The default channel is not unlimited/free, but conda-forge is: https://conda-forge.org/blog/posts/2020-11-20-anaconda-tos/

**Comment by martindurant** [comment]
Hm, OK then I suppose I am confused too, along with everyone else. None of the open source projects I am connected with (some without any anaconda involvement) seems to have a problem.

Obviously, I have no idea how it is decided whether a organisation counts as commercial or not. I would be happy to ask.

**Comment by holzman** [comment]
@consideRatio: Hopefully that's enough justification for this change? I didn't know if you need more detail on Fermilab and Anaconda.

**Comment by consideRatio** [comment]
@holzman in #524 I'm proposing to change the image significantly, which involves installing a more primitive image and encourage users to maintain their own images to be work against the dask-gateway helm chart.

This project has a need for maintenance sustainability, this is a proper step in that direction. Like this, you end up responsible for building an image for your scheduler/worker pods. I'm curious to hear what do you think about this @holzman, it is always tricky to balance things when maintaining open source projects and I think your input could be helpful for this balance!
