### ISSUE TITLE
Drop support for python 3.7

### ISSUE THREAD

**Issue by consideRatio** [dask/dask-gateway#498]
At this point Python 3.6 has reached end of life. If we wish to support it, we may need to not use modern versions of libraries etc as they may no longer support Python 3.6.

Due to that, given agreement, I suggest we drop support for Python 3.6 at this point if there is agreement about it.

**Comment by jacobtomlinson** [comment]
We only support `3.8` and above. I would suggest we should be consistent here too.

dask/community#213

**Comment by consideRatio** [comment]
In #501 I've now added a commit to drop Python 3.6 and require Python 3.7+.

To drop support for Python 3.7 without breaking our test suite etc, some additional work needs to be done.

### Action points
- [ ] Drop support for Python 3.6 (#501)
- [ ] Drop support for Python 3.7
