### ISSUE TITLE
Refresh dask-gateway-server/dask-gateway-proxy with modern golang practices

### ISSUE THREAD

**Issue by consideRatio** [dask/dask-gateway#506]
With the current versions of golang (1.17, 1.18), golang has established some practices on how to handle dependencies etc that wasn't around in the past. To run the tests against golang 1.16-1.18 I had to make a small change in #505 for example.

I'd like for the golang code we maintain as part of this project to catch up and follow common golang code practices to help it be easy to comprehend in the context of modern golang documentation and practices etc. Due to that, I suggest we try to refactor the source code in dask-gateway-server/dask-gateway-proxy to follow a common practice for how the project is structured: https://github.com/golang-standards/project-layout#go-directories

I'd be happy to do this, but I need to learn more about Golang first, which will take quite a bit of time. I think if anyone wants to contribute a PR to refactor our golang source code to follow common practices such as how to organize files etc, that would be great!

**Comment by martindurant** [comment]
Aside from one of us becoming expert at go, other possible options are to rewrite in something else (rust is popular), or just requiring traefik as a running local process. The latter is a big binary, but has the advantage of more similar config across backends and lower maintenance.

**Comment by jcrist** [comment]
The go proxy is pretty simple and works well as is. I don't think it makes sense to invest any time in rewriting it in a different language. I wrote this as my first real go project and it didn't take me long to get up to speed, I wouldn't expect this to be large maintenance burden or to prevent further development of dask-gateway.
