### ISSUE TITLE
ci: open-source alternative to cloudera's now commercial distribution of hadoop?

### ISSUE THREAD

**Issue by consideRatio** [dask/dask-gateway#520]
I tried to rebuild [continuous_integration/docker/hadoop/Dockerfile](https://github.com/dask/dask-gateway/blob/main/continuous_integration/docker/hadoop/Dockerfile) which we have used as a backend that `dask-gateway-server` can work against to create Hadoop based Dask clusters.

The rebuild failed because the Cloudera distribution of Hadoop is no longer free but instead require username/password associated with an active paid subscription.

Is there an open-source option that someone would recommend? The old image has Python 3.7 in it, which we consider dropping supporting for in #498.

## Related

- _From https://docs.cloudera.com/documentation/enterprise/6/release-notes/topics/rg_cm_6_version_download.html_
  ![image](https://user-images.githubusercontent.com/3837114/161268767-d19e0926-e718-4c53-8c04-47d7f8ce9383.png)

- Installation instructions that include username:password when trying to access the `yum` or `apt-get` package repository to install the cloudera based hadoop distribution: https://docs.cloudera.com/documentation/enterprise/6/6.3/topics/configure_cm_repo.html#cm_repo__section_gsx_ydw_wm

**Comment by martindurant** [comment]
I had an issue about this. The original apache hadoop installer is complete, but with less config out of the box and all different paths.

You could, however, use the existing image as the base instead of rebuilding from scratch. The base hadoop system would not change and follow latest releases, but maybe that's ok.

**Comment by consideRatio** [comment]
Thanks @martindurant! This is #401! I see no reason to keep this issue open alongside it so I'll close this one in favor of #401.
