### ISSUE TITLE
Remaining pre-release (DONE) and post-release tasks

### ISSUE THREAD

**Issue by consideRatio** [dask/dask-gateway#543]
## Remaining pre-release tasks

- [x] Validate the workflow to publish a helm chart and images work all the way
  - [x] Resolve the situation of the dask-gateway image failing to build for arm64 because of `distributed` depends on `psutils` that doesn't provide a wheel, yet, and requires `gcc` and `python-devel` to build.
    - Build failure: https://github.com/dask/dask-gateway/runs/6086317500?check_suite_focus=true
    - A PR suggesting to build a wheel for aarch64: https://github.com/giampaolo/psutil/pull/2070
    - Disabled arm64 for the dask/dask-gateway sample image for schedulers/workers: https://github.com/dask/dask-gateway/pull/545
  - Version `0.9.0-n076.h7abb97f` is released - you are most welcome to test and report if things work out or not using that version!
- [x] Create a RELEASE.md file describing how to make a release
  - Related: #296
  - #549
- [x] Add helm chart upgrade test
  - Related: #480
  - #551
- [x] Resolve upgrade failure caused by CRDs not being upgraded by `helm`
  - Related: #553
- [x] Upgrade Traefik CRDs
  - #554
- [x] Validate the workflow to publish sdist and built wheels to PyPI
  - Doing this means to cut a 2022.4.0-beta.1 release.
  - NOTE: I did a mistake, where I failed to add all version changes. I ended up publishing a mix of 0.9.0-beta.1 and 2022.4.0-beta.1. This probably isn't going to cause problems.
- [x] Add/update changelog
  - Related: #331
  - #547
- [x] Make end to end test of the k8s helm chart
  Following the changelogs currently proposed strategy worked, no trouble experienced!
- [x] Make a release
  Done, see https://github.com/dask/dask-gateway/pull/547#issuecomment-1105503465
  
## Remaining post-release tasks

- [ ] Update https://github.com/dask/helm-chart to list the dask-gateway helm chart in badges etc in the README.md file.
- [x] Update conda-forge recipe
  - https://github.com/conda-forge/dask-gateway-feedstock/pull/22
  - https://github.com/conda-forge/dask-gateway-feedstock/tree/main/recipe
  - https://github.com/conda-forge/dask-gateway-feedstock/issues/27
  - https://github.com/conda-forge/dask-gateway-feedstock/pull/28

**Comment by consideRatio** [comment]
Closing this, we have not made a conda-forge release and I'm surrendering to attempting to get it done as I ended up struggling too much with the conda-forge feedstock, see https://github.com/conda-forge/dask-gateway-feedstock/issues/27.

**Comment by TomAugspurger** [comment]
Thanks for the write-up. I can give it a shot sometime in the next few weeks.
