### ISSUE TITLE
Proposal to remove/rework dev-environment.yml?

### ISSUE THREAD

**Issue by consideRatio** [dask/dask-gateway#546]
@rigzba21 I've worked quite a bit to make the various dependencies part of this project a bit easier to manage as a maintainer of this project. As part of that, I've worked to avoid duplications of where dependencies are declared.

With that in mind, I've focused on requirements.txt files rather than conda environment.yml files because those are dependencies that can be referenced by setup.py directly.

Now that this work has completed, this file is the final piece where a list of dependencies are duplicated and adds maintenance burden to keep it updated. Due to that, I'd like to remove it again. Your work is not wasted, it has helped drive development efforts towards no longer having dependencies declared in multiple places by creating this summary.

My suggestion is that this file is removed, but documentation is updated to summarize how to install development dependencies with the requirements.txt files instead. We now have four:

1. one for `dask-gateway`'s setup.py install_requires
2. one for `dask-gateway-servers`'s setup.py install_requires
3. one for "build documentation" dependencies (docs/requirements.txt)
4. one for "run tests" dependencies (tests/requirements.txt)

Everything we have in this repo now relies on these.

My main goal isn't in practice to remove dev-environment.yml, but to not run the risk of needing to update dependencies in two locations. Perhaps the most sensible idea is to make it reference the requirements.txt files of relevance, but also retain installation of for example `golang`?

**Comment by rigzba21** [comment]
This makes sense to me! I'm all for reducing dependency duplication and helping make the development setup more clear and easy to understand!
