### ISSUE TITLE
'VBox' object has no attribute '_ipython_display_'

### ISSUE THREAD

**Issue by viniciusdc** [dask/dask-gateway#607]
**What happened**:

Received `AttributeError: 'VBox' object has no attribute '_ipython_display_'` when calling `cluster_options` from within a Jupyter notebook.
![image (1)](https://user-images.githubusercontent.com/51954708/191081045-74f9e8bb-deee-4d76-bcc7-778d7ce1af0b.png)

**What you expected to happen**:

The options widget should be shown correctly, as expected.

**Minimal Complete Verifiable Example**:

```python
from dask_gateway import Gateway

gt = Gateway()
options = gt.cluster_options()
options
```

**Anything else we need to know?**:

**Environment**:

- dask-gateway: 2022.4.0
- Dask version: 2022.4.2
- Python version: 3.9.13
- Operating System: Linux
- Install method (conda, pip, source): conda

## Extra

The reason for the above issue seems to be that Ipywidgets latest available version `8.0.0` removed the `on_display` method in place of `_repr_mimebundle_` (see [ref.](https://github.com/jupyter-widgets/ipywidgets/pull/2021)) and the Dask-gateway client still uses the old call: 
https://github.com/dask/dask-gateway/blob/376b4a29622ed6cdb0fe9707d589ec625be5d079/dask-gateway/dask_gateway/client.py#L1222-L1230

**Comment by martindurant** [comment]
I think your assessment is right, also seen in https://github.com/python-streamz/streamz/pull/454 and probably elsewhere.

**Comment by viniciusdc** [comment]
I am happy to contribute with a PR for this, but I would like to know what would be the best solution here.
