### ISSUE TITLE
Regression with distributed 2022.11.0 and 2022.11.1?

### ISSUE THREAD

**Issue by consideRatio** [dask/dask-gateway#648]
The test code below is failing since ~2 weeks ago, see [working test run](https://github.com/dask/dask-gateway/actions/runs/3469191692) and [broken test run](https://github.com/dask/dask-gateway/actions/runs/3478505382) from 15 and 16th November.

https://github.com/dask/dask-gateway/blob/7f50b5456a0b254a6badb25059ada40b40998329/tests/test_local_backend.py#L19-L30

![image](https://user-images.githubusercontent.com/3837114/204494991-d6d4634e-1998-466e-b345-7e72a4cbc00c.png)

In that time, the following dependencies changed.

![image](https://user-images.githubusercontent.com/3837114/204491074-a940d5cf-b64e-49e4-95c2-278f6269fc2f.png)

I suspect the reason is that `distributed` went from 2022.10.2 to 2022.11.0. Distributed [changelog](https://distributed.dask.org/en/stable/changelog.html) does not make it apparent what has changed causing this, but I've concluded 2022.11.1 also fails so its not a fixed regression.

Help to resolve this is greatly appreciated! Just understanding what has caused this would be a big deal towards resolving it.

**Comment by fjetter** [comment]
what exactly is `do_check_workers` checking/returning?

**Comment by consideRatio** [comment]
do_check_worker's intent is defined in a base class for dask-gateway backends to start workers:

https://github.com/dask/dask-gateway/blob/1cbb6a3c1d188ef97689dc734c6989c721e0cccf/dask-gateway-server/dask_gateway_server/backends/db_base.py#L1559-L1576

And the implementation know to be failing is the LocalBackend implementation, implemented like this:

https://github.com/dask/dask-gateway/blob/1cbb6a3c1d188ef97689dc734c6989c721e0cccf/dask-gateway-server/dask_gateway_server/backends/local.py#L298-L299

https://github.com/dask/dask-gateway/blob/1cbb6a3c1d188ef97689dc734c6989c721e0cccf/dask-gateway-server/dask_gateway_server/backends/local.py#L298-L299

https://github.com/dask/dask-gateway/blob/1cbb6a3c1d188ef97689dc734c6989c721e0cccf/dask-gateway-server/dask_gateway_server/backends/local.py#L40-L41

https://github.com/dask/dask-gateway/blob/1cbb6a3c1d188ef97689dc734c6989c721e0cccf/dask-gateway-server/dask_gateway_server/backends/local.py#L27-L37

Googling on kill signal 0 I found this: [man kill(2)](https://man7.org/linux/man-pages/man2/kill.2.html)
>       If sig is 0, then no signal is sent, but existence and permission
>       checks are still performed; this can be used to check for the
>       existence of a process ID or process group ID that the caller is
>       permitted to signal.

I conclude that whats checked is that local processes are terminated, and they represent the dask-gateway created workers.

So, the bug is higher up the chain I'd say, that the scaling event isn't awaited like before?

https://github.com/dask/dask-gateway/blob/7f50b5456a0b254a6badb25059ada40b40998329/tests/test_local_backend.py#L19-L30

My conclusion, is that the next thing to investigate is why this passed while processes were still running:

https://github.com/dask/dask-gateway/blob/7f50b5456a0b254a6badb25059ada40b40998329/tests/test_local_backend.py#L21-L22

**Comment by consideRatio** [comment]
## cluster.scale

https://github.com/dask/dask-gateway/blob/1cbb6a3c1d188ef97689dc734c6989c721e0cccf/dask-gateway/dask_gateway/client.py#L1091-L1099

https://github.com/dask/dask-gateway/blob/1cbb6a3c1d188ef97689dc734c6989c721e0cccf/dask-gateway/dask_gateway/client.py#L677-L687

https://github.com/dask/dask-gateway/blob/1cbb6a3c1d188ef97689dc734c6989c721e0cccf/dask-gateway/dask_gateway/client.py#L667-L675

## wait_for_workers

https://github.com/dask/dask-gateway/blob/1cbb6a3c1d188ef97689dc734c6989c721e0cccf/tests/utils_test.py#L114-L125

https://github.com/dask/dask-gateway/blob/1cbb6a3c1d188ef97689dc734c6989c721e0cccf/dask-gateway/dask_gateway/client.py#L971-L975

https://github.com/dask/dask-gateway/blob/1cbb6a3c1d188ef97689dc734c6989c721e0cccf/dask-gateway/dask_gateway/client.py#L1118-L1145

**Comment by consideRatio** [comment]
@fjetter it seems like the update to distributed>=2022.11.0 (2022.12.0 as well) led to a longer duration to shut down local worker processes.

A wait duration of 1 second was fine good enough before, but now we need 3 full seconds (between 2 and 3) in the test suite. So, something is slower to shut down perhaps?

**Comment by fjetter** [comment]
Thanks for letting me know. I do not understand why 2022.11.0 would slow down worker shutdown but I'll keep an eye out.

**Comment by consideRatio** [comment]
@fjetter thanks! Btw i ended up with a 10 second duration wait as four seconds were once found to not be sufficient.
