### ISSUE TITLE
fresh azure helm deploy stuck on ImagePullBackOff, chartpress did not run?

### ISSUE THREAD

**Issue by ZirconCode** [dask/dask-gateway#654]
I've deployed on an Azure k8 service, ran the helm command as described [here](https://gateway.dask.org/install-kube.html):

```
RELEASE=dask-gateway
NAMESPACE=kube-system

helm upgrade $RELEASE dask-gateway \
    --repo=https://helm.dask.org \
    --install \
    --namespace $NAMESPACE \
    --values path/to/your/config.yaml
```

I've changed one line in the recommended config.yaml: `password: "sometestingpwd"`.
I've also changed the namespace from `NAMESPACE=dask-gateway` to `NAMESPACE=kube-system`.
The deploy was successful, however the controller-dask-gateway and api-dask-gateway are stuck on status `ImagePullBackOff`.
Traefik was able to pull and is happy.

Diving into the .yaml of the two, I found `image: ghcr.io/dask/dask-gateway-server:set-by-chartpress`.
Is this the issue, or at least an issue? From what I understand, chartpress was supposed to run as part of the helm chart, is this a misunderstanding? If so, a note in the doc would be helpful. Thanks!

**Environment**:

- Dask version: 2022.11.0

**Comment by consideRatio** [comment]
Using this command, it seems like everything is good in the helm chart repo:

```
helm template dask-gateway --repo=https://helm.dask.org | grep "image: " 
          image: ghcr.io/dask/dask-gateway-server:2022.11.0
          image: ghcr.io/dask/dask-gateway-server:2022.11.0
          image: traefik:2.9.4
```

I suspect that you run into the following issue: https://github.com/helm/helm/issues/9244

Did you run the `helm upgrade` command from a location where there was a folder named `dask-gateway` that had a `Chart.yaml` within it with values like set-by-chartpress still?

**Comment by ZirconCode** [comment]
Thanks for the fast reply! To confirm, setting the version in the config by hand resolved the issue, so indeed it was chart-press.

I ran `helm upgrade` from the azure cloud shell, the folder I ran it from did not have such a local `dask-gateway` folder, however I suspect you are right and the cloud shell helm default paths or storage behavior might be the issue here.

**Comment by consideRatio** [comment]
@ZirconCode are you cloning the dask-gateway github repo or similar? There shouldn't be any reason for you to see set-by-chartpress unless you have cloned the github repo. You are supposed to consume a packaged helm chart directly from helm.dask.org, and not clone the github repository to get the helm chart. If you consume it directly from the github repo you end up with values.yaml having set-by-chartpress entries as well as no values.schema.json file bundled to help you catch config errors etc.

Looking at helm.dask.org's published helm chart version 2022.11.0, it contains no trace of "set-by-chartpress" or "chartpress" as it shouldn't after being published there.

```shell
helm show chart dask-gateway --repo=https://helm.dask.org | grep version
version: 2022.11.0

helm show chart dask-gateway --repo=https://helm.dask.org | grep chartpress
# nothing
helm show values dask-gateway --repo=https://helm.dask.org | grep chartpress
# nothing

helm template dask-gateway --repo=https://helm.dask.org | grep "image: " 
          image: ghcr.io/dask/dask-gateway-server:2022.11.0
          image: ghcr.io/dask/dask-gateway-server:2022.11.0
          image: traefik:2.9.4
```

**Comment by ZirconCode** [comment]
Ah, yes I provided my own `config.yaml ` which came from a cloned repo. Thanks also for the warning on `values.schema.json `. Will consume correctly now, thanks!

**Comment by consideRatio** [comment]
> Ah, yes I provided my own config.yaml  which came from a cloned repo.

Ah watch out for the practice of making a copy of the chart's values.yaml file, provide your own with default values overrides only!
