### ISSUE TITLE
Develop support for sqlalchemy 2 in dask-gateway-server

### ISSUE THREAD

**Issue by consideRatio** [dask/dask-gateway#679]
I just merged #678 that had failing test, so some dependency just introduced some breaking change.

**Comment by consideRatio** [comment]
Its sqlalchemy 2 which is used in `dask-gateway-server` in one single file:

https://github.com/dask/dask-gateway/blob/57c5aa8a4ec21e58855571ecd981fa21b3c743ad/dask-gateway-server/dask_gateway_server/backends/db_base.py#L9

**Comment by TomAugspurger** [comment]
Taking a look briefly.
